-- 2026-08-30 · case_message: the conversation between the insured and the analyst.
-- Apply before deploying the code (ddl-auto=validate). Idempotent.

BEGIN;

DO $$
DECLARE
    tenant TEXT;
BEGIN
    FOR tenant IN SELECT schema_name FROM arbiter_common.insurer LOOP

        EXECUTE format($ddl$
            CREATE TABLE IF NOT EXISTS %I.case_message (
                id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                case_id         BIGINT       NOT NULL REFERENCES %I.cases(id) ON DELETE CASCADE,
                sender_id       BIGINT       NOT NULL REFERENCES arbiter_common.users(id),
                sender_role     VARCHAR(30)  NOT NULL,
                body            TEXT         NOT NULL,
                created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
                read_at         TIMESTAMPTZ
            )$ddl$, tenant, tenant);

        EXECUTE format(
            'CREATE INDEX IF NOT EXISTS idx_case_message_case ON %I.case_message (case_id, created_at)',
            tenant);

    END LOOP;
END $$;

COMMIT;
