-- 2026-09-02 · Settlement authority (Annex II): a ceiling per branch in settlement_authority; above it
-- the referente signs, tracked on case_settlement. The case status does not change: what waits is the
-- settlement. Apply before deploying the code (ddl-auto=validate).

BEGIN;

-- 1 · settlement_authority. No row for a branch means no ceiling.
CREATE TABLE IF NOT EXISTS arbiter_bbva.settlement_authority (
    id          BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id   BIGINT        NOT NULL REFERENCES arbiter_common.branch(id),
    max_amount  NUMERIC(15,2) NOT NULL,
    updated_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT settlement_authority_branch_unique UNIQUE (branch_id),
    CONSTRAINT settlement_authority_amount_check CHECK (max_amount >= 0)
);

CREATE TABLE IF NOT EXISTS arbiter_provincia.settlement_authority (
    id          BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id   BIGINT        NOT NULL REFERENCES arbiter_common.branch(id),
    max_amount  NUMERIC(15,2) NOT NULL,
    updated_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT settlement_authority_branch_unique UNIQUE (branch_id),
    CONSTRAINT settlement_authority_amount_check CHECK (max_amount >= 0)
);

-- Seed branches get the same ceilings init seeds, sized to each branch's sums insured; branches added
-- later are left alone. No settled amount changes, only who signs from now on.
INSERT INTO arbiter_bbva.settlement_authority (branch_id, max_amount)
SELECT b.id, v.max_amount
  FROM arbiter_common.branch b
  JOIN (VALUES ('Celulares', 500000.00), ('Tecnología Portátil', 50000.00)) AS v(name, max_amount)
    ON v.name = b.name
 ON CONFLICT (branch_id) DO NOTHING;

INSERT INTO arbiter_provincia.settlement_authority (branch_id, max_amount)
SELECT b.id, v.max_amount
  FROM arbiter_common.branch b
  JOIN (VALUES ('Celulares', 500000.00), ('Tecnología Portátil', 50000.00)) AS v(name, max_amount)
    ON v.name = b.name
 ON CONFLICT (branch_id) DO NOTHING;

-- 2 · case_settlement status. Existing settlements default to AUTHORIZED: they were signed with no
-- ceiling, so there is no second signer to record.
ALTER TABLE arbiter_bbva.case_settlement
    ADD COLUMN IF NOT EXISTS status                VARCHAR(25) NOT NULL DEFAULT 'AUTHORIZED',
    ADD COLUMN IF NOT EXISTS authority_limit       NUMERIC(15,2),
    ADD COLUMN IF NOT EXISTS authorized_by_user_id BIGINT REFERENCES arbiter_common.users(id),
    ADD COLUMN IF NOT EXISTS authorized_at         TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS return_reason         TEXT,
    ADD COLUMN IF NOT EXISTS pending_justification TEXT;

ALTER TABLE arbiter_provincia.case_settlement
    ADD COLUMN IF NOT EXISTS status                VARCHAR(25) NOT NULL DEFAULT 'AUTHORIZED',
    ADD COLUMN IF NOT EXISTS authority_limit       NUMERIC(15,2),
    ADD COLUMN IF NOT EXISTS authorized_by_user_id BIGINT REFERENCES arbiter_common.users(id),
    ADD COLUMN IF NOT EXISTS authorized_at         TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS return_reason         TEXT,
    ADD COLUMN IF NOT EXISTS pending_justification TEXT;

ALTER TABLE arbiter_bbva.case_settlement
    DROP CONSTRAINT IF EXISTS case_settlement_status_check;
ALTER TABLE arbiter_bbva.case_settlement
    ADD CONSTRAINT case_settlement_status_check
        CHECK (status IN ('AUTHORIZED', 'PENDING_AUTHORIZATION', 'RETURNED'));

ALTER TABLE arbiter_provincia.case_settlement
    DROP CONSTRAINT IF EXISTS case_settlement_status_check;
ALTER TABLE arbiter_provincia.case_settlement
    ADD CONSTRAINT case_settlement_status_check
        CHECK (status IN ('AUTHORIZED', 'PENDING_AUTHORIZATION', 'RETURNED'));

-- Existing settlements get the ceiling in force frozen, which the screen uses to explain them.
UPDATE arbiter_bbva.case_settlement s
   SET authority_limit = a.max_amount
  FROM arbiter_bbva.cases c
  JOIN arbiter_common.claim_cause cc ON cc.id = c.claim_cause_id
  JOIN arbiter_bbva.settlement_authority a ON a.branch_id = cc.branch_id
 WHERE c.id = s.case_id AND s.authority_limit IS NULL;

UPDATE arbiter_provincia.case_settlement s
   SET authority_limit = a.max_amount
  FROM arbiter_provincia.cases c
  JOIN arbiter_common.claim_cause cc ON cc.id = c.claim_cause_id
  JOIN arbiter_provincia.settlement_authority a ON a.branch_id = cc.branch_id
 WHERE c.id = s.case_id AND s.authority_limit IS NULL;

COMMIT;

-- Check:
-- SELECT table_schema FROM information_schema.tables WHERE table_name = 'settlement_authority';
-- SELECT case_id, status, authority_limit, authorized_by_user_id FROM arbiter_provincia.case_settlement;
-- (the seeded row of case 1 stays AUTHORIZED, with ceiling and signer NULL)
