-- =============================================================================
-- 2026-08-17 · Antecedente de fraude del asegurado
--
-- Migración puntual y NO destructiva, para aplicar sobre una base que ya tiene
-- datos (Railway) sin pasar por el trío reset → init → seed.
--
-- Qué agrega:
--   · <tenant>.insured_fraud_record: el antecedente en sí.
--   · <tenant>.factor_weight: el factor de scoring `fraud_history`.
--   · <tenant>.insurer_rule: la política FRAUD_RECORD (ventana + veto de Fast Track).
--
-- Por qué: Arbiter tenía memoria del expediente pero no de la persona. Un
-- asegurado con fraude comprobado arrancaba su denuncia siguiente como si nada
-- hubiera pasado — `ClaimFrequencyEvaluator` contaba siniestros previos y era
-- ciego al desenlace, y `Case.fraudDetermined` existía en el DER sin que nadie
-- lo escribiera.
--
-- DEPENDE de 2026-08-17-peritaje.sql: la tabla referencia expert_assessment,
-- que crea esa migración. Aplicar en ese orden.
--
-- IMPORTANTE: los servicios corren con ddl-auto=validate. Apenas exista el
-- código que declara estas entidades, una base sin esta tabla hace que
-- classification-service NO levante. Aplicar esto ANTES de desplegar el código.
--
-- `init-multitenant.sql` ya quedó actualizado: una base creada de cero desde ese
-- script ya trae todo esto. Este archivo es solo para las bases que ya existían.
--
-- Idempotente: se puede correr más de una vez sin romper nada.
-- =============================================================================

BEGIN;

DO $$
DECLARE
    tenant TEXT;
BEGIN
    FOR tenant IN SELECT schema_name FROM arbiter_common.insurer LOOP

        -- ─── El antecedente ──────────────────────────────────────────────────
        -- Vive en classification-service (el módulo que ya guarda memoria entre
        -- denuncias con los embeddings de pgvector, y el que lo lee al scorear),
        -- aunque el analista lo confirme desde el expediente en cases-service.
        --
        -- Nunca se edita: es una afirmación sobre una persona, así que qué dice y
        -- quién lo dijo tienen que seguir siendo legibles años después (Disp. SSN
        -- 2/2023, Ley 25.326). Deja de contar por vencimiento de la ventana, no
        -- por edición ni por borrado.
        EXECUTE format($ddl$
            CREATE TABLE IF NOT EXISTS %I.insured_fraud_record (
                id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                -- El DNI y no insured_id: es la identidad con la que la persona
                -- viaja entre módulos y la que el motor tiene a mano cuando llega
                -- la denuncia siguiente.
                insured_dni              VARCHAR(20)  NOT NULL,
                source                   VARCHAR(20)  NOT NULL,
                reason                   TEXT         NOT NULL,
                declared_by_analyst_id   BIGINT       NOT NULL REFERENCES %I.claims_analyst(id),
                declared_by_analyst_name VARCHAR(255) NOT NULL,
                declared_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
                expert_assessment_id     BIGINT       REFERENCES %I.expert_assessment(id),
                case_id                  BIGINT       NOT NULL REFERENCES %I.cases(id) ON DELETE CASCADE,

                CONSTRAINT insured_fraud_record_case_unique UNIQUE (case_id),
                CONSTRAINT insured_fraud_record_source_valid CHECK (
                    source IN ('EXPERT_BACKED', 'ANALYST_DECLARED')),
                -- "Con respaldo pericial" tiene que tener un peritaje al que apuntar:
                -- es la única diferencia entre los dos orígenes (uno puntúa y veta, el
                -- otro solo se muestra), y sin esto sería nada más que una etiqueta.
                CONSTRAINT insured_fraud_record_backing_valid CHECK (
                    (source = 'EXPERT_BACKED'    AND expert_assessment_id IS NOT NULL)
                    OR (source = 'ANALYST_DECLARED' AND expert_assessment_id IS NULL))
            )$ddl$, tenant, tenant, tenant, tenant);

        EXECUTE format($ddl$
            CREATE INDEX IF NOT EXISTS idx_insured_fraud_record_dni
                ON %I.insured_fraud_record (insured_dni)
            $ddl$, tenant);

        -- ─── El factor de scoring ────────────────────────────────────────────
        -- Cierra el ciclo que claim_frequency deja abierto: ese factor cuenta
        -- cuántas veces denunció el asegurado y no mira cómo terminó cada denuncia.
        -- Se suma a TODA configuración de scoring existente; los ids no se fijan a
        -- mano (en una base con datos la secuencia asigna el próximo libre).
        EXECUTE format($sql$
            INSERT INTO %I.factor_weight (factor_code, weight, scoring_configuration_id)
            SELECT 'fraud_history', 0.60, sc.id
              FROM %I.scoring_configuration sc
             WHERE NOT EXISTS (
                SELECT 1 FROM %I.factor_weight fw
                 WHERE fw.scoring_configuration_id = sc.id
                   AND fw.factor_code = 'fraud_history')
            $sql$, tenant, tenant, tenant);

        -- ─── La política de la aseguradora ───────────────────────────────────
        -- Ventana de cinco años y veto de Fast Track. Una sola fila por aseguradora
        -- (branch_id y coverage_id NULL): el antecedente es de la persona, no de la
        -- cobertura que afectó. El effect es DERIVAR y nunca RECHAZAR — el
        -- antecedente no es "una causa legal o convencional de exclusión" de ESTE
        -- siniestro, es un motivo para que lo mire una persona.
        --
        -- Sin esta fila los antecedentes se registran y se ven igual, pero no
        -- puntúan ni vetan.
        EXECUTE format($sql$
            INSERT INTO %I.insurer_rule (active, valid_from, name, rule_type, effect, priority,
                                         blocks_fast_track, branch_id, coverage_id, configuration)
            SELECT TRUE, '2026-01-01 00:00:00+00', 'Antecedente de fraude del asegurado',
                   'FRAUD_RECORD', 'DERIVAR', 1, TRUE, NULL, NULL, '{"windowMonths":60}'
            WHERE NOT EXISTS (
                SELECT 1 FROM %I.insurer_rule
                 WHERE rule_type = 'FRAUD_RECORD' AND branch_id IS NULL AND coverage_id IS NULL)
            $sql$, tenant, tenant);

    END LOOP;
END $$;

COMMIT;
