-- 2026-10-05 · branch and claim_cause stop being a platform-wide catalog: each insurer gets its own
-- copy in its schema, so creating, renaming or deleting a branch no longer reaches the others.
--   · <tenant>.branch and <tenant>.claim_cause are created and filled from arbiter_common with the
--     SAME ids: rules keep claim cause ids inside insurer_rule.configuration, and every FK below
--     keeps pointing at the same number.
--   · branch gains external_name, what the insurer database calls the line (poliza.rama). It starts
--     equal to name; from here on a rename only touches name, so incoming policies still match.
--   · The FKs that pointed at the common tables (coverage, insurer_rule, document_requirement,
--     settlement_authority, cases, service_provider_branch) are repointed to the tenant's own,
--     keeping their names.
--   · arbiter_common.branch and arbiter_common.claim_cause are dropped last.
-- The deployed code reads the common tables until the new build is up: apply this WHILE deploying
-- cases-, classification-, rules- and reports-service, never ahead of it. Afterwards run the
-- CREATE OR REPLACE FUNCTION arbiter_common.create_tenant_schema block from init-multitenant.sql,
-- or onboarding a new insurer fails on the dropped tables. Idempotent.

BEGIN;

DO $$
DECLARE
    tenant      TEXT;
    con         RECORD;
    has_common  BOOLEAN := to_regclass('arbiter_common.branch') IS NOT NULL;
BEGIN
    FOR tenant IN SELECT schema_name FROM arbiter_common.insurer LOOP

        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS %I.branch (
                id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name            VARCHAR(100) NOT NULL UNIQUE,
                external_name   VARCHAR(100) UNIQUE
            )', tenant);

        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS %I.claim_cause (
                id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name        VARCHAR(100) NOT NULL,
                branch_id   BIGINT       NOT NULL REFERENCES %I.branch(id),

                CONSTRAINT claim_cause_branch_name_unique UNIQUE (branch_id, name)
            )', tenant, tenant);

        IF has_common THEN
            EXECUTE format(
                'INSERT INTO %I.branch (id, name, external_name)
                 SELECT id, name, name FROM arbiter_common.branch
                 ON CONFLICT DO NOTHING', tenant);
            EXECUTE format(
                'INSERT INTO %I.claim_cause (id, name, branch_id)
                 SELECT id, name, branch_id FROM arbiter_common.claim_cause
                 ON CONFLICT DO NOTHING', tenant);
        END IF;

        EXECUTE format(
            'SELECT setval(pg_get_serial_sequence(%L, ''id''), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL)
               FROM %I.branch', tenant || '.branch', tenant);
        EXECUTE format(
            'SELECT setval(pg_get_serial_sequence(%L, ''id''), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL)
               FROM %I.claim_cause', tenant || '.claim_cause', tenant);

        -- Found in the catalog rather than listed by hand, so a table that references the common
        -- catalog and isn't named in the header is repointed too instead of blocking the drop.
        IF has_common THEN
            FOR con IN
                SELECT c.conname, c.conrelid::regclass AS tbl, pg_get_constraintdef(c.oid) AS def
                  FROM pg_constraint c
                  JOIN pg_namespace n ON n.oid = c.connamespace
                 WHERE c.contype = 'f'
                   AND n.nspname = tenant
                   AND c.confrelid IN ('arbiter_common.branch'::regclass,
                                       'arbiter_common.claim_cause'::regclass)
            LOOP
                EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I', con.tbl, con.conname);
                EXECUTE format('ALTER TABLE %s ADD CONSTRAINT %I %s', con.tbl, con.conname,
                               replace(con.def, 'REFERENCES arbiter_common.',
                                       format('REFERENCES %I.', tenant)));
            END LOOP;
        END IF;

    END LOOP;
END $$;

-- No CASCADE on purpose: a reference left behind has to stop the migration, not vanish with it.
DROP TABLE IF EXISTS arbiter_common.claim_cause;
DROP TABLE IF EXISTS arbiter_common.branch;

COMMIT;
