-- =============================================================================
-- H0007 — lo que el modelo extrae de cada documento, completo
--
-- Dos cosas, y son distintas a propósito:
--
--   1. document_analysis suma brand/model. Son campos TIPADOS porque una regla los
--      compara: DocumentInconsistencyEvaluator cruza la marca del documento contra el
--      bien asegurado. Es el chequeo que el IMEI no puede hacer fuera de Celulares —
--      una póliza de Tecnología Portátil no tiene IMEI, así que sin esto la factura de
--      reparación de otra notebook no se cruza contra nada.
--
--   2. document_detail es la lista GENÉRICA nombre/valor para todo lo demás que el
--      documento diga y ninguna regla lea: nro. de factura, nro. de serie, comercio.
--      Existe para que sumar un dato nuevo no pida una migración cada vez.
--
-- La distinción importa y no es estética: un dato que una regla compara necesita el
-- tipo (una fecha se resta, un importe se compara con tolerancia). Y sobre todo,
-- necesita que el nombre sea un contrato. En document_detail el nombre es como lo
-- llamó el modelo, así que una regla que buscara ahí dejaría de encontrarlo el día que
-- el modelo lo redacte distinto — y fallaría EN SILENCIO, que en este motor se lee como
-- "no hay nada mal". Cuando un detalle empiece a alimentar una regla, se promueve a
-- columna tipada.
--
-- Idempotente. No borra ni reescribe nada: las dos columnas nacen NULL y las
-- extracciones viejas quedan como están — nadie las relee, y el próximo análisis del
-- mismo documento las completa (document_analysis se reemplaza en cada corrida).
--
-- Uso:
--   psql "$DATABASE_URL" -f db/migrations/2026-09-07-datos-documento.sql
-- =============================================================================

BEGIN;

DO $$
DECLARE
    tenant TEXT;
BEGIN
    FOR tenant IN
        SELECT schema_name
          FROM information_schema.schemata
         WHERE schema_name LIKE 'arbiter\_%'
           AND schema_name <> 'arbiter_common'
         ORDER BY schema_name
    LOOP
        -- Un esquema de aseguradora sin document_analysis sería uno a medio crear; se
        -- saltea en vez de romper la migración entera por él.
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.tables
             WHERE table_schema = tenant AND table_name = 'document_analysis'
        ) THEN
            RAISE NOTICE 'Skipping %: no document_analysis table', tenant;
            CONTINUE;
        END IF;

        EXECUTE format(
            'ALTER TABLE %I.document_analysis ADD COLUMN IF NOT EXISTS brand VARCHAR(100)', tenant);
        EXECUTE format(
            'ALTER TABLE %I.document_analysis ADD COLUMN IF NOT EXISTS model VARCHAR(100)', tenant);

        EXECUTE format($ddl$
            CREATE TABLE IF NOT EXISTS %I.document_detail (
                id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name            VARCHAR(100) NOT NULL,
                value           VARCHAR(500) NOT NULL,
                analysis_id     BIGINT       NOT NULL REFERENCES %I.document_analysis(id) ON DELETE CASCADE
            )$ddl$, tenant, tenant);

        RAISE NOTICE 'Migrated %', tenant;
    END LOOP;
END $$;

COMMIT;

-- ─── Verificación ────────────────────────────────────────────────────────────
--
-- 1. Las dos columnas nuevas en cada esquema de aseguradora (una fila por tenant):
--
-- SELECT table_schema, string_agg(column_name, ', ' ORDER BY column_name)
--   FROM information_schema.columns
--  WHERE table_name = 'document_analysis' AND column_name IN ('brand', 'model')
--  GROUP BY table_schema
--  ORDER BY table_schema;
--
-- 2. La tabla nueva en cada esquema:
--
-- SELECT table_schema
--   FROM information_schema.tables
--  WHERE table_name = 'document_detail'
--  ORDER BY table_schema;
--
-- 3. Después de reclasificar un expediente con adjuntos, que la extracción esté
--    completando lo nuevo. brand en NULL sobre una fila vieja es lo esperado; en una
--    recién escrita (extracted_at de hoy) sobre una factura, no:
--
-- SELECT a.id, a.extracted_at, a.item_description, a.brand, a.model,
--        (SELECT count(*) FROM arbiter_bbva.document_detail d WHERE d.analysis_id = a.id) AS detalles
--   FROM arbiter_bbva.document_analysis a
--  ORDER BY a.extracted_at DESC
--  LIMIT 20;
