-- 2026-08-18 · Data read from each document (H0031): document_analysis and document_visual_finding.
-- Apply before deploying the code (ddl-auto=validate). Idempotent.

BEGIN;

DO $$
DECLARE
    tenant TEXT;
BEGIN
    FOR tenant IN SELECT schema_name FROM arbiter_common.insurer LOOP

        -- Nullable on purpose: NULL means "the document does not say", never "it does not match".
        -- One row per document, overwritten on each reclassification.
        EXECUTE format($ddl$
            CREATE TABLE IF NOT EXISTS %I.document_analysis (
                id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                transcription       TEXT         NOT NULL,
                document_date       DATE,
                amount              NUMERIC(14,2),
                item_description    VARCHAR(255),
                imei                VARCHAR(20),
                affected_party      VARCHAR(20)  NOT NULL,
                extracted_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
                case_document_id    BIGINT       NOT NULL REFERENCES %I.case_documents(id) ON DELETE CASCADE,

                CONSTRAINT document_analysis_document_unique UNIQUE (case_document_id),
                CONSTRAINT document_analysis_affected_party_valid CHECK (
                    affected_party IN ('TITULAR', 'FAMILIAR', 'TERCERO', 'DESCONOCIDO'))
            )$ddl$, tenant, tenant);

        -- Empty is the normal case: most documents raise no finding.
        EXECUTE format($ddl$
            CREATE TABLE IF NOT EXISTS %I.document_visual_finding (
                id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                finding         TEXT   NOT NULL,
                analysis_id     BIGINT NOT NULL REFERENCES %I.document_analysis(id) ON DELETE CASCADE
            )$ddl$, tenant, tenant);

    END LOOP;
END $$;

COMMIT;

-- Rows fill in on the next classification; earlier extractions were never stored.
