-- =============================================================================
-- 2026-08-18 · Datos extraídos de cada documento (H0031)
--
-- Migración puntual y NO destructiva, para aplicar sobre una base que ya tiene
-- datos (Railway) sin pasar por el trío reset → init → seed.
--
-- Qué agrega:
--   · <tenant>.document_analysis: lo que el modelo de visión leyó de cada
--     adjunto — la transcripción más los mismos datos ya tipados.
--   · <tenant>.document_visual_finding: las señales de manipulación que notó
--     al mirar la imagen, una fila por hallazgo.
--
-- Por qué: classification-service YA calcula todo esto en cada clasificación
-- (`OllamaDocumentAnalyzer` → `DocumentExtraction`), lo usa para armar el prompt
-- y para alimentar `DocumentInconsistencyEvaluator`, y lo descarta apenas
-- termina la corrida. El analista nunca lo ve: sólo llega el resultado
-- indirecto (un factor de riesgo con el nombre del campo, sin el valor). La
-- solapa "Datos extraídos" del detalle del expediente esperaba exactamente esto.
--
-- IMPORTANTE: los servicios corren con ddl-auto=validate. Apenas exista el
-- código que declara estas entidades, una base sin estas tablas hace que
-- classification-service NO levante. Aplicar esto ANTES de desplegar el código.
--
-- `init-multitenant.sql` ya quedó actualizado: una base creada de cero desde ese
-- script ya trae las dos tablas. Este archivo es sólo para las que ya existían.
--
-- Idempotente: se puede correr más de una vez sin romper nada.
-- =============================================================================

BEGIN;

-- Un DO en vez de repetir el DDL por esquema: mañana hay una tercera aseguradora
-- y la lista sale de insurer, que es el registro de quién existe.
DO $$
DECLARE
    tenant TEXT;
BEGIN
    FOR tenant IN SELECT schema_name FROM arbiter_common.insurer LOOP

        -- Campos nullables a propósito: una foto del bien no tiene importe y una
        -- denuncia policial no tiene IMEI. NULL es "el documento no lo dice",
        -- nunca "no coincide" — un campo ausente jamás debe leerse como una
        -- inconsistencia.
        --
        -- Una fila por documento (UNIQUE): la extracción se rehace en cada
        -- reclasificación, así que se pisa en vez de acumular corridas. Distinto
        -- de llm_analysis, que es append-only porque lo auditado es la
        -- recomendación en sí.
        EXECUTE format($ddl$
            CREATE TABLE IF NOT EXISTS %I.document_analysis (
                id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                transcription       TEXT         NOT NULL,
                document_date       DATE,
                amount              NUMERIC(14,2),
                item_description    VARCHAR(255),
                imei                VARCHAR(20),
                affected_party      VARCHAR(20)  NOT NULL,
                extracted_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
                case_document_id    BIGINT       NOT NULL REFERENCES %I.case_documents(id) ON DELETE CASCADE,

                CONSTRAINT document_analysis_document_unique UNIQUE (case_document_id),
                CONSTRAINT document_analysis_affected_party_valid CHECK (
                    affected_party IN ('TITULAR', 'FAMILIAR', 'TERCERO', 'DESCONOCIDO'))
            )$ddl$, tenant, tenant);

        -- Vacío es lo normal, no una ausencia de dato: un documento común no tiene
        -- por qué levantar ninguna. Una fila por hallazgo, igual que llm_reason.
        EXECUTE format($ddl$
            CREATE TABLE IF NOT EXISTS %I.document_visual_finding (
                id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                finding         TEXT   NOT NULL,
                analysis_id     BIGINT NOT NULL REFERENCES %I.document_analysis(id) ON DELETE CASCADE
            )$ddl$, tenant, tenant);

    END LOOP;
END $$;

COMMIT;

-- Las filas se llenan solas en la próxima clasificación de cada expediente. Los
-- que ya estaban clasificados quedan sin datos extraídos hasta que se los
-- reclasifique: la extracción vieja no se guardó en ningún lado y no hay de
-- dónde recuperarla. La solapa simplemente no aparece para esos expedientes.
