-- 2026-08-17 · Insured fraud record: insured_fraud_record, the fraud_history factor and the FRAUD_RECORD policy.
-- Run after 2026-08-17-peritaje.sql and before deploying the code (ddl-auto=validate). Idempotent.

BEGIN;

DO $$
DECLARE
    tenant TEXT;
BEGIN
    FOR tenant IN SELECT schema_name FROM arbiter_common.insurer LOOP

        -- Never edited: a statement about a person must stay readable for years (SSN Disp. 2/2023,
        -- Law 25.326). It stops counting when its window expires.
        EXECUTE format($ddl$
            CREATE TABLE IF NOT EXISTS %I.insured_fraud_record (
                id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                -- The DNI, not insured_id: it is the identity that travels between modules.
                insured_dni              VARCHAR(20)  NOT NULL,
                source                   VARCHAR(20)  NOT NULL,
                reason                   TEXT         NOT NULL,
                declared_by_analyst_id   BIGINT       NOT NULL REFERENCES %I.claims_analyst(id),
                declared_by_analyst_name VARCHAR(255) NOT NULL,
                declared_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
                expert_assessment_id     BIGINT       REFERENCES %I.expert_assessment(id),
                case_id                  BIGINT       NOT NULL REFERENCES %I.cases(id) ON DELETE CASCADE,

                CONSTRAINT insured_fraud_record_case_unique UNIQUE (case_id),
                CONSTRAINT insured_fraud_record_source_valid CHECK (
                    source IN ('EXPERT_BACKED', 'ANALYST_DECLARED')),
                -- An expert-backed record must point at the assessment: that is what lets it score and veto.
                CONSTRAINT insured_fraud_record_backing_valid CHECK (
                    (source = 'EXPERT_BACKED'    AND expert_assessment_id IS NOT NULL)
                    OR (source = 'ANALYST_DECLARED' AND expert_assessment_id IS NULL))
            )$ddl$, tenant, tenant, tenant, tenant);

        EXECUTE format($ddl$
            CREATE INDEX IF NOT EXISTS idx_insured_fraud_record_dni
                ON %I.insured_fraud_record (insured_dni)
            $ddl$, tenant);

        -- Added to every existing scoring configuration; ids come from the sequence.
        EXECUTE format($sql$
            INSERT INTO %I.factor_weight (factor_code, weight, scoring_configuration_id)
            SELECT 'fraud_history', 0.60, sc.id
              FROM %I.scoring_configuration sc
             WHERE NOT EXISTS (
                SELECT 1 FROM %I.factor_weight fw
                 WHERE fw.scoring_configuration_id = sc.id
                   AND fw.factor_code = 'fraud_history')
            $sql$, tenant, tenant, tenant);

        -- One row per insurer: three-year window and Fast Track veto. It refers the case to a person,
        -- never rejects it. Without this row records still show but neither score nor veto.
        EXECUTE format($sql$
            INSERT INTO %I.insurer_rule (active, valid_from, name, rule_type, effect, priority,
                                         blocks_fast_track, branch_id, coverage_id, configuration)
            SELECT TRUE, '2026-01-01 00:00:00+00', 'Antecedente de fraude del asegurado',
                   'FRAUD_RECORD', 'DERIVAR', 1, TRUE, NULL, NULL, '{"windowMonths":36}'
            WHERE NOT EXISTS (
                SELECT 1 FROM %I.insurer_rule
                 WHERE rule_type = 'FRAUD_RECORD' AND branch_id IS NULL AND coverage_id IS NULL)
            $sql$, tenant, tenant);

    END LOOP;
END $$;

COMMIT;
