-- =============================================================================
-- 2026-09-02 · Atribuciones de liquidación (bloque 2)
--
-- Migración puntual y NO destructiva, para aplicar sobre una base que ya tiene
-- datos (Railway) sin pasar por el trío reset → init → seed.
--
-- Continúa 2026-09-01-determinacion-monto-a-pagar.sql: ahí el analista pasó a
-- determinar el monto; acá se le pone techo. Sale del Anexo II del procedimiento
-- de la compañía — "Aprobar liquidaciones hasta el límite del atributo asignado
-- por rama" —: por encima de ese monto la liquidación la autoriza el referente.
--
-- Dos cambios:
--   1. settlement_authority — el tope por ramo que configura el referente.
--   2. case_settlement      — en qué instancia está la liquidación, con quién la
--                             autorizó y el tope que regía cuando se confirmó.
--
-- Lo que NO cambia, a propósito: los estados del expediente. El que espera
-- autorización es la liquidación, no el expediente — el asegurado no tiene por
-- qué ver un intermedio administrativo, y así no se toca el enum CaseStatus ni
-- la trazabilidad que ya está andando.
--
-- IMPORTANTE: los servicios corren con ddl-auto=validate. Aplicar ANTES de
-- desplegar el código, o cases-service no levanta.
-- =============================================================================

BEGIN;

-- ─── 1 · settlement_authority: el tope por ramo ─────────────────────────────
-- Sin fila para un ramo NO hay tope, y el analista autoriza todo — que es como
-- venía funcionando hasta hoy.
CREATE TABLE IF NOT EXISTS arbiter_bbva.settlement_authority (
    id          BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id   BIGINT        NOT NULL REFERENCES arbiter_common.branch(id),
    max_amount  NUMERIC(15,2) NOT NULL,
    updated_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT settlement_authority_branch_unique UNIQUE (branch_id),
    CONSTRAINT settlement_authority_amount_check CHECK (max_amount >= 0)
);

CREATE TABLE IF NOT EXISTS arbiter_provincia.settlement_authority (
    id          BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id   BIGINT        NOT NULL REFERENCES arbiter_common.branch(id),
    max_amount  NUMERIC(15,2) NOT NULL,
    updated_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT settlement_authority_branch_unique UNIQUE (branch_id),
    CONSTRAINT settlement_authority_amount_check CHECK (max_amount >= 0)
);

-- Los dos ramos semilla se cargan con los mismos topes que ahora siembra
-- db/init-multitenant.sql, por lo mismo que en la migración anterior: si no, una
-- base migrada y una recién creada mandarían a firmar cosas distintas, y ese
-- desvío no lo detecta scripts/check-schema-consistency.py porque compara
-- estructura, no datos.
--
-- Los montos salen de las sumas aseguradas reales de cada ramo: en Celulares se
-- asegura del orden del millón y en Tecnología Portátil de las decenas de miles,
-- así que un tope único no separaría nada. No cambian ningún monto ya liquidado
-- —solo quién firma de acá en adelante—, y el referente los ajusta desde su
-- pantalla.
--
-- Solo esos dos ramos, por nombre: un ramo que la aseguradora haya agregado
-- después no lo dimensionó nadie acá, y ponerle un tope a ciegas le metería una
-- cola de autorizaciones que nadie pidió.
INSERT INTO arbiter_bbva.settlement_authority (branch_id, max_amount)
SELECT b.id, v.max_amount
  FROM arbiter_common.branch b
  JOIN (VALUES ('Celulares', 500000.00), ('Tecnología Portátil', 50000.00)) AS v(name, max_amount)
    ON v.name = b.name
 ON CONFLICT (branch_id) DO NOTHING;

INSERT INTO arbiter_provincia.settlement_authority (branch_id, max_amount)
SELECT b.id, v.max_amount
  FROM arbiter_common.branch b
  JOIN (VALUES ('Celulares', 500000.00), ('Tecnología Portátil', 50000.00)) AS v(name, max_amount)
    ON v.name = b.name
 ON CONFLICT (branch_id) DO NOTHING;

-- ─── 2 · case_settlement: en qué instancia está ─────────────────────────────
-- El default 'AUTHORIZED' es lo correcto hacia atrás: las liquidaciones que ya
-- existen se firmaron cuando no había tope, así que la firma del analista era
-- la autorización. authorized_by_user_id queda NULL en ellas por lo mismo — no
-- hubo un segundo firmante que registrar.
ALTER TABLE arbiter_bbva.case_settlement
    ADD COLUMN IF NOT EXISTS status                VARCHAR(25) NOT NULL DEFAULT 'AUTHORIZED',
    ADD COLUMN IF NOT EXISTS authority_limit       NUMERIC(15,2),
    ADD COLUMN IF NOT EXISTS authorized_by_user_id BIGINT REFERENCES arbiter_common.users(id),
    ADD COLUMN IF NOT EXISTS authorized_at         TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS return_reason         TEXT,
    ADD COLUMN IF NOT EXISTS pending_justification TEXT;

ALTER TABLE arbiter_provincia.case_settlement
    ADD COLUMN IF NOT EXISTS status                VARCHAR(25) NOT NULL DEFAULT 'AUTHORIZED',
    ADD COLUMN IF NOT EXISTS authority_limit       NUMERIC(15,2),
    ADD COLUMN IF NOT EXISTS authorized_by_user_id BIGINT REFERENCES arbiter_common.users(id),
    ADD COLUMN IF NOT EXISTS authorized_at         TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS return_reason         TEXT,
    ADD COLUMN IF NOT EXISTS pending_justification TEXT;

ALTER TABLE arbiter_bbva.case_settlement
    DROP CONSTRAINT IF EXISTS case_settlement_status_check;
ALTER TABLE arbiter_bbva.case_settlement
    ADD CONSTRAINT case_settlement_status_check
        CHECK (status IN ('AUTHORIZED', 'PENDING_AUTHORIZATION', 'RETURNED'));

ALTER TABLE arbiter_provincia.case_settlement
    DROP CONSTRAINT IF EXISTS case_settlement_status_check;
ALTER TABLE arbiter_provincia.case_settlement
    ADD CONSTRAINT case_settlement_status_check
        CHECK (status IN ('AUTHORIZED', 'PENDING_AUTHORIZATION', 'RETURNED'));

-- Las liquidaciones que ya existen se firmaron sin tope de por medio, pero ahora
-- el ramo tiene uno: se les congela el que rige, que es lo que la pantalla usa
-- para explicar por qué no necesitaron al referente.
UPDATE arbiter_bbva.case_settlement s
   SET authority_limit = a.max_amount
  FROM arbiter_bbva.cases c
  JOIN arbiter_common.claim_cause cc ON cc.id = c.claim_cause_id
  JOIN arbiter_bbva.settlement_authority a ON a.branch_id = cc.branch_id
 WHERE c.id = s.case_id AND s.authority_limit IS NULL;

UPDATE arbiter_provincia.case_settlement s
   SET authority_limit = a.max_amount
  FROM arbiter_provincia.cases c
  JOIN arbiter_common.claim_cause cc ON cc.id = c.claim_cause_id
  JOIN arbiter_provincia.settlement_authority a ON a.branch_id = cc.branch_id
 WHERE c.id = s.case_id AND s.authority_limit IS NULL;

COMMIT;

-- Verificación:
-- SELECT table_schema FROM information_schema.tables WHERE table_name = 'settlement_authority';
-- SELECT case_id, status, authority_limit, authorized_by_user_id FROM arbiter_provincia.case_settlement;
-- (la fila sembrada del case 1 tiene que quedar en AUTHORIZED, con límite y autorizante en NULL)
