-- 2026-09-01 · A policy has SEVERAL coverages: new policy_coverage, backfilled from the insurer database
-- (not from policy.coverage_id, which kept only the first one), and policy.coverage_id/sum_insured are
-- dropped. Apply before deploying the code (ddl-auto=validate). Idempotent.

BEGIN;

DO $$
DECLARE
    tenant     TEXT;
    insurer_db TEXT;
BEGIN
    FOR tenant IN
        SELECT schema_name FROM arbiter_common.insurer
    LOOP
        insurer_db := replace(tenant, 'arbiter_', 'aseguradora_');

        EXECUTE format($ddl$
            CREATE TABLE IF NOT EXISTS %I.policy_coverage (
                id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                policy_id       BIGINT        NOT NULL REFERENCES %I.policy(id) ON DELETE CASCADE,
                coverage_id     BIGINT        NOT NULL REFERENCES %I.coverage(id),
                display_order   INTEGER       NOT NULL DEFAULT 1,
                sum_insured     NUMERIC(15,2) NOT NULL,
                deductible_pct  NUMERIC(5,2),

                CONSTRAINT policy_coverage_unique UNIQUE (policy_id, coverage_id)
            )$ddl$, tenant, tenant, tenant);

        EXECUTE format(
            'CREATE INDEX IF NOT EXISTS idx_policy_coverage_policy ON %I.policy_coverage (policy_id)',
            tenant);

        -- 1. Backfill from the source, matched by coverage name like PolicySynchronizer. Coverages missing from
        --    the tenant's catalog are left out, as the sync does.
        IF to_regclass(insurer_db || '.cobertura') IS NOT NULL THEN
            EXECUTE format($dml$
                INSERT INTO %I.policy_coverage (policy_id, coverage_id, display_order, sum_insured, deductible_pct)
                SELECT p.id, c.id, cob.orden, cob.suma_asegurada, cob.franquicia_pct
                  FROM %I.policy p
                  JOIN %I.poliza pol    ON pol.numero = p.external_policy_number
                  JOIN %I.cobertura cob ON cob.poliza_id = pol.id
                  JOIN %I.coverage c    ON c.name = cob.nombre
                ON CONFLICT (policy_id, coverage_id) DO NOTHING
            $dml$, tenant, tenant, insurer_db, insurer_db, tenant);
        END IF;

        -- 2. Safety net: a policy left with no row would make filing fail with 422, so the old column is copied.
        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = tenant AND table_name = 'policy' AND column_name = 'coverage_id'
        ) THEN
            EXECUTE format($dml$
                INSERT INTO %I.policy_coverage (policy_id, coverage_id, display_order, sum_insured, deductible_pct)
                SELECT p.id, p.coverage_id, 1, p.sum_insured, c.deductible
                  FROM %I.policy p
                  JOIN %I.coverage c ON c.id = p.coverage_id
                 WHERE NOT EXISTS (
                       SELECT 1 FROM %I.policy_coverage pc WHERE pc.policy_id = p.id)
                ON CONFLICT (policy_id, coverage_id) DO NOTHING
            $dml$, tenant, tenant, tenant, tenant);

            EXECUTE format('ALTER TABLE %I.policy DROP COLUMN coverage_id', tenant);
            EXECUTE format('ALTER TABLE %I.policy DROP COLUMN sum_insured', tenant);
        END IF;
    END LOOP;
END $$;

COMMIT;

-- Check 1: each policy with its coverages (Celulares ones bring 2):
-- SELECT p.external_policy_number, c.name, pc.display_order, pc.sum_insured, pc.deductible_pct
--   FROM arbiter_bbva.policy p
--   JOIN arbiter_bbva.policy_coverage pc ON pc.policy_id = p.id
--   JOIN arbiter_bbva.coverage c ON c.id = pc.coverage_id
--  ORDER BY p.id, pc.display_order;
--
-- Check 2: no policy without coverages (filing would answer 422):
-- SELECT p.external_policy_number
--   FROM arbiter_bbva.policy p
--  WHERE NOT EXISTS (SELECT 1 FROM arbiter_bbva.policy_coverage pc WHERE pc.policy_id = p.id);
--
-- Check 3: existing cases whose coverage doesn't answer for their cause; not touched here
-- (docs/temas-a-discutir.md, point 3):
-- SELECT e.id, cc.name AS hecho, c.name AS cobertura_del_expediente
--   FROM arbiter_bbva.cases e
--   JOIN arbiter_common.claim_cause cc ON cc.id = e.claim_cause_id
--   JOIN arbiter_bbva.coverage c ON c.id = e.coverage_id
--  ORDER BY e.id;
