-- =============================================================================
-- 2026-08-30 · Conversación entre el asegurado y el analista
--
-- Migración puntual y NO destructiva, para aplicar sobre una base que ya tiene
-- datos (Railway) sin pasar por el trío reset → init → seed.
--
-- Qué agrega:
--   · <tenant>.case_message: el hilo de mensajes de un expediente, con quién lo
--     escribió y cuándo lo leyó el otro lado.
--
-- Por qué: cuando el analista necesita pedir una aclaración no tenía por dónde
-- pedirla, y el asegurado no tenía por dónde contestar. El mail de rechazo dice
-- textual "si querés conocer los motivos o no estás de acuerdo, podés
-- comunicarte con nosotros" y hasta ahora ese canal no existía.
--
-- IMPORTANTE: los servicios corren con ddl-auto=validate. Apenas exista el
-- código que declara la entidad CaseMessage, una base sin esta tabla hace que
-- cases-service NO levante. Aplicar esto ANTES de desplegar el código.
--
-- `init-multitenant.sql` ya quedó actualizado: una base creada de cero desde ese
-- script ya trae esto. Este archivo es solo para las bases que ya existían.
--
-- Idempotente: se puede correr más de una vez sin romper nada.
-- =============================================================================

BEGIN;

-- Un DO en vez de repetir el DDL por esquema: mañana hay una tercera aseguradora
-- y la lista sale de insurer, que es el registro de quién existe.
DO $$
DECLARE
    tenant TEXT;
BEGIN
    FOR tenant IN SELECT schema_name FROM arbiter_common.insurer LOOP

        EXECUTE format($ddl$
            CREATE TABLE IF NOT EXISTS %I.case_message (
                id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                case_id         BIGINT       NOT NULL REFERENCES %I.cases(id) ON DELETE CASCADE,
                sender_id       BIGINT       NOT NULL REFERENCES arbiter_common.users(id),
                sender_role     VARCHAR(30)  NOT NULL,
                body            TEXT         NOT NULL,
                created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
                read_at         TIMESTAMPTZ
            )$ddl$, tenant, tenant);

        EXECUTE format(
            'CREATE INDEX IF NOT EXISTS idx_case_message_case ON %I.case_message (case_id, created_at)',
            tenant);

    END LOOP;
END $$;

COMMIT;
