-- 2026-09-01 · Amount to pay, total loss (NSIN001 §5.2.1.2): settlement parameters on coverage, the
-- inputs frozen on policy_snapshot, case_settlement, and importe_cuota in the insurer databases.
-- The formula comes from the product manuals and clause 102 art. 5. Apply before deploying the code.

BEGIN;

-- 1 · coverage: settlement parameters. Defaults follow the Celulares manual; both deductions start
-- off because turning one on changes what the insured gets, and that is the referente's call.
ALTER TABLE arbiter_bbva.coverage
    ADD COLUMN IF NOT EXISTS settlement_basis            VARCHAR(30)  NOT NULL DEFAULT 'SUM_INSURED',
    ADD COLUMN IF NOT EXISTS second_event_percentage     NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS deduct_pending_installments BOOLEAN      NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS deduct_overdue_balance      BOOLEAN      NOT NULL DEFAULT FALSE;

ALTER TABLE arbiter_provincia.coverage
    ADD COLUMN IF NOT EXISTS settlement_basis            VARCHAR(30)  NOT NULL DEFAULT 'SUM_INSURED',
    ADD COLUMN IF NOT EXISTS second_event_percentage     NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS deduct_pending_installments BOOLEAN      NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS deduct_overdue_balance      BOOLEAN      NOT NULL DEFAULT FALSE;

ALTER TABLE arbiter_bbva.coverage
    DROP CONSTRAINT IF EXISTS coverage_settlement_basis_check;
ALTER TABLE arbiter_bbva.coverage
    ADD CONSTRAINT coverage_settlement_basis_check
        CHECK (settlement_basis IN ('SUM_INSURED', 'LESSER_OF_SUM_AND_REPLACEMENT'));

ALTER TABLE arbiter_provincia.coverage
    DROP CONSTRAINT IF EXISTS coverage_settlement_basis_check;
ALTER TABLE arbiter_provincia.coverage
    ADD CONSTRAINT coverage_settlement_basis_check
        CHECK (settlement_basis IN ('SUM_INSURED', 'LESSER_OF_SUM_AND_REPLACEMENT'));

-- Seed coverages 1 and 2 (Robo, Hurto) are aligned with what init now seeds, so a migrated and a new
-- database settle alike. Only those two: nobody modeled coverages created later.
UPDATE arbiter_bbva.coverage
   SET deduct_pending_installments = TRUE,
       deduct_overdue_balance      = TRUE,
       second_event_percentage     = CASE WHEN id = 1 THEN 50.00 ELSE NULL END
 WHERE id IN (1, 2) AND name IN ('Robo de celular', 'Hurto');

UPDATE arbiter_provincia.coverage
   SET deduct_pending_installments = TRUE,
       deduct_overdue_balance      = TRUE,
       second_event_percentage     = CASE WHEN id = 1 THEN 50.00 ELSE NULL END
 WHERE id IN (1, 2) AND name IN ('Robo de celular', 'Hurto');

-- Daño accidental pays the lower of sum insured and replacement value (clause 340 art. 7); a repair
-- doesn't end the policy, so no pending installments.
UPDATE arbiter_provincia.coverage
   SET settlement_basis            = 'LESSER_OF_SUM_AND_REPLACEMENT',
       second_event_percentage     = 50.00,
       deduct_pending_installments = FALSE,
       deduct_overdue_balance      = TRUE
 WHERE name = 'Daño accidental';

-- 2 · policy_snapshot: all nullable, older snapshots cannot be filled honestly; a gap shows as missing,
-- not as a zero nobody measured.
ALTER TABLE arbiter_bbva.policy_snapshot
    ADD COLUMN IF NOT EXISTS effective_to       TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS installment_amount NUMERIC(15,2),
    ADD COLUMN IF NOT EXISTS overdue_balance    NUMERIC(15,2),
    ADD COLUMN IF NOT EXISTS events_in_year     INTEGER;

ALTER TABLE arbiter_provincia.policy_snapshot
    ADD COLUMN IF NOT EXISTS effective_to       TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS installment_amount NUMERIC(15,2),
    ADD COLUMN IF NOT EXISTS overdue_balance    NUMERIC(15,2),
    ADD COLUMN IF NOT EXISTS events_in_year     INTEGER;

-- 3 · case_settlement: keeps the inputs next to the result, and calculated vs settled amount apart so a
-- manual adjustment stays visible.
CREATE TABLE IF NOT EXISTS arbiter_bbva.case_settlement (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id                     BIGINT        NOT NULL REFERENCES arbiter_bbva.cases(id),
    formula                     VARCHAR(20)   NOT NULL DEFAULT 'TOTAL_LOSS',
    sum_insured                 NUMERIC(15,2) NOT NULL,
    settlement_basis            VARCHAR(30)   NOT NULL,
    replacement_value           NUMERIC(15,2),
    deductible_rate             NUMERIC(5,2),
    event_ordinal               INTEGER       NOT NULL DEFAULT 1,
    event_percentage            NUMERIC(5,2)  NOT NULL DEFAULT 100,
    pending_installments        INTEGER       NOT NULL DEFAULT 0,
    installment_amount          NUMERIC(15,2),
    deductible_amount           NUMERIC(15,2) NOT NULL DEFAULT 0,
    pending_installments_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
    overdue_balance_amount      NUMERIC(15,2) NOT NULL DEFAULT 0,
    calculated_amount           NUMERIC(15,2) NOT NULL,
    settled_amount              NUMERIC(15,2) NOT NULL,
    adjustment_reason           TEXT,
    coverage_id                 BIGINT        NOT NULL REFERENCES arbiter_bbva.coverage(id),
    policy_snapshot_id          BIGINT        REFERENCES arbiter_bbva.policy_snapshot(id),
    analyst_id                  BIGINT        NOT NULL REFERENCES arbiter_bbva.claims_analyst(id),
    calculated_at               TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    confirmed_at                TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT case_settlement_case_unique UNIQUE (case_id),
    CONSTRAINT case_settlement_formula_check CHECK (formula IN ('TOTAL_LOSS')),
    CONSTRAINT case_settlement_basis_check
        CHECK (settlement_basis IN ('SUM_INSURED', 'LESSER_OF_SUM_AND_REPLACEMENT'))
);

CREATE TABLE IF NOT EXISTS arbiter_provincia.case_settlement (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id                     BIGINT        NOT NULL REFERENCES arbiter_provincia.cases(id),
    formula                     VARCHAR(20)   NOT NULL DEFAULT 'TOTAL_LOSS',
    sum_insured                 NUMERIC(15,2) NOT NULL,
    settlement_basis            VARCHAR(30)   NOT NULL,
    replacement_value           NUMERIC(15,2),
    deductible_rate             NUMERIC(5,2),
    event_ordinal               INTEGER       NOT NULL DEFAULT 1,
    event_percentage            NUMERIC(5,2)  NOT NULL DEFAULT 100,
    pending_installments        INTEGER       NOT NULL DEFAULT 0,
    installment_amount          NUMERIC(15,2),
    deductible_amount           NUMERIC(15,2) NOT NULL DEFAULT 0,
    pending_installments_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
    overdue_balance_amount      NUMERIC(15,2) NOT NULL DEFAULT 0,
    calculated_amount           NUMERIC(15,2) NOT NULL,
    settled_amount              NUMERIC(15,2) NOT NULL,
    adjustment_reason           TEXT,
    coverage_id                 BIGINT        NOT NULL REFERENCES arbiter_provincia.coverage(id),
    policy_snapshot_id          BIGINT        REFERENCES arbiter_provincia.policy_snapshot(id),
    analyst_id                  BIGINT        NOT NULL REFERENCES arbiter_provincia.claims_analyst(id),
    calculated_at               TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    confirmed_at                TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT case_settlement_case_unique UNIQUE (case_id),
    CONSTRAINT case_settlement_formula_check CHECK (formula IN ('TOTAL_LOSS')),
    CONSTRAINT case_settlement_basis_check
        CHECK (settlement_basis IN ('SUM_INSURED', 'LESSER_OF_SUM_AND_REPLACEMENT'))
);

-- 4 · Insurer database: amount of each premium installment
ALTER TABLE aseguradora_bbva.poliza
    ADD COLUMN IF NOT EXISTS importe_cuota NUMERIC(38,2);
ALTER TABLE aseguradora_provincia.poliza
    ADD COLUMN IF NOT EXISTS importe_cuota NUMERIC(38,2);

-- Same as seed-demo.sql: with unpaid installments the real balance rules; otherwise 2% of the sum
-- insured per month, as in the two reference BBVA policies.
UPDATE aseguradora_bbva.poliza p
   SET importe_cuota = CASE
           WHEN p.cuotas_impagas > 0 AND p.saldo_deuda > 0
               THEN ROUND(p.saldo_deuda / p.cuotas_impagas, 2)
           ELSE ROUND(COALESCE(c.suma_asegurada, 0) * 0.02, 2)
       END
  FROM (SELECT poliza_id, MAX(suma_asegurada) AS suma_asegurada
          FROM aseguradora_bbva.cobertura GROUP BY poliza_id) c
 WHERE c.poliza_id = p.id AND p.importe_cuota IS NULL;

UPDATE aseguradora_provincia.poliza p
   SET importe_cuota = CASE
           WHEN p.cuotas_impagas > 0 AND p.saldo_deuda > 0
               THEN ROUND(p.saldo_deuda / p.cuotas_impagas, 2)
           ELSE ROUND(COALESCE(c.suma_asegurada, 0) * 0.02, 2)
       END
  FROM (SELECT poliza_id, MAX(suma_asegurada) AS suma_asegurada
          FROM aseguradora_provincia.cobertura GROUP BY poliza_id) c
 WHERE c.poliza_id = p.id AND p.importe_cuota IS NULL;

COMMIT;

-- Check:
-- SELECT table_schema, column_name FROM information_schema.columns
--  WHERE table_name = 'coverage' AND column_name LIKE '%settlement%' OR column_name LIKE 'deduct_%';
-- SELECT table_schema FROM information_schema.tables WHERE table_name = 'case_settlement';
-- SELECT numero, cuotas_impagas, saldo_deuda, importe_cuota FROM aseguradora_bbva.poliza ORDER BY id;
