-- 2026-09-07 · H0007: document_analysis gets brand/model, typed because DocumentInconsistencyEvaluator
-- compares them; document_detail holds every other name/value the model reads. A detail that starts
-- feeding a rule becomes a typed column: matching a model-chosen name would fail silently. Idempotent.

BEGIN;

DO $$
DECLARE
    tenant TEXT;
BEGIN
    FOR tenant IN
        SELECT schema_name
          FROM information_schema.schemata
         WHERE schema_name LIKE 'arbiter\_%'
           AND schema_name <> 'arbiter_common'
         ORDER BY schema_name
    LOOP
        -- A tenant schema without document_analysis is half-created: skip it.
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.tables
             WHERE table_schema = tenant AND table_name = 'document_analysis'
        ) THEN
            RAISE NOTICE 'Skipping %: no document_analysis table', tenant;
            CONTINUE;
        END IF;

        EXECUTE format(
            'ALTER TABLE %I.document_analysis ADD COLUMN IF NOT EXISTS brand VARCHAR(100)', tenant);
        EXECUTE format(
            'ALTER TABLE %I.document_analysis ADD COLUMN IF NOT EXISTS model VARCHAR(100)', tenant);

        EXECUTE format($ddl$
            CREATE TABLE IF NOT EXISTS %I.document_detail (
                id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name            VARCHAR(100) NOT NULL,
                value           VARCHAR(500) NOT NULL,
                analysis_id     BIGINT       NOT NULL REFERENCES %I.document_analysis(id) ON DELETE CASCADE
            )$ddl$, tenant, tenant);

        RAISE NOTICE 'Migrated %', tenant;
    END LOOP;
END $$;

COMMIT;

-- ─── Verification ────────────────────────────────────────────────────────────
--
-- 1. The two new columns in every tenant schema (one row per tenant):
--
-- SELECT table_schema, string_agg(column_name, ', ' ORDER BY column_name)
--   FROM information_schema.columns
--  WHERE table_name = 'document_analysis' AND column_name IN ('brand', 'model')
--  GROUP BY table_schema
--  ORDER BY table_schema;
--
-- 2. The new table in every schema:
--
-- SELECT table_schema
--   FROM information_schema.tables
--  WHERE table_name = 'document_detail'
--  ORDER BY table_schema;
--
-- 3. After reclassifying a case with attachments: brand NULL is expected on old rows, not on a fresh
--    invoice row:
--
-- SELECT a.id, a.extracted_at, a.item_description, a.brand, a.model,
--        (SELECT count(*) FROM arbiter_bbva.document_detail d WHERE d.analysis_id = a.id) AS detalles
--   FROM arbiter_bbva.document_analysis a
--  ORDER BY a.extracted_at DESC
--  LIMIT 20;
