-- =============================================================================
-- 2026-08-17 · Derivación a peritaje
--
-- Migración puntual y NO destructiva, para aplicar sobre una base que ya tiene
-- datos (Railway) sin pasar por el trío reset → init → seed.
--
-- Qué agrega:
--   · arbiter_common.case_status: el estado PENDING_EXPERT_REPORT (id 7).
--   · <tenant>.expert_firm: catálogo de peritos externos por aseguradora.
--   · <tenant>.expert_assessment: la derivación y el informe que vuelve.
--   · <tenant>.insurer_rule: la política EXPERT_DERIVATION por ramo (monto mínimo).
--
-- Por qué: frente a indicios de fraude, rechazar directo apoyándose en una
-- sospecha del modelo no tiene respaldo — el estado SINIESTRO RECHAZADO exige
-- "una causa legal o convencional de exclusión", y un indicio no lo es. El
-- peritaje es el eslabón que convierte la sospecha en un hecho verificado
-- (procedimiento BBVA 2.6, "en caso de hallarse indicadores de fraude").
--
-- IMPORTANTE: los servicios corren con ddl-auto=validate. Apenas exista el
-- código que declara estas entidades, una base sin estas tablas hace que
-- cases-service NO levante. Aplicar esto ANTES de desplegar el código.
--
-- `init-multitenant.sql` y `seed-demo.sql` ya quedaron actualizados: una base
-- creada de cero desde esos scripts ya trae todo esto. Este archivo es solo
-- para las bases que ya existían.
--
-- Idempotente: se puede correr más de una vez sin romper nada.
-- =============================================================================

BEGIN;

-- ─── El estado nuevo ─────────────────────────────────────────────────────────
-- El asegurado ve 'En análisis': que su siniestro se haya derivado a un perito
-- es tráfico interno, y contárselo filtraría la sospecha que lo motivó.
INSERT INTO arbiter_common.case_status (id, name, description, insured_status, is_final) VALUES
    (7, 'PENDING_EXPERT_REPORT', 'Derivado a peritaje, esperando el informe', 'En análisis', FALSE)
ON CONFLICT (name) DO NOTHING;

SELECT setval(pg_get_serial_sequence('arbiter_common.case_status', 'id'),
              (SELECT MAX(id) FROM arbiter_common.case_status));

-- ─── Las tablas por tenant ───────────────────────────────────────────────────
-- Un DO en vez de repetir el DDL por esquema: mañana hay una tercera aseguradora
-- y la lista sale de insurer, que es el registro de quién existe.
DO $$
DECLARE
    tenant TEXT;
BEGIN
    FOR tenant IN SELECT schema_name FROM arbiter_common.insurer LOOP

        EXECUTE format($ddl$
            CREATE TABLE IF NOT EXISTS %I.expert_firm (
                id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name        VARCHAR(120) NOT NULL,
                email       VARCHAR(150) NOT NULL,
                zone        VARCHAR(80),
                active      BOOLEAN      NOT NULL DEFAULT TRUE,
                branch_id   BIGINT       REFERENCES arbiter_common.branch(id)
            )$ddl$, tenant);

        EXECUTE format($ddl$
            CREATE TABLE IF NOT EXISTS %I.expert_assessment (
                id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                expert_name         VARCHAR(120) NOT NULL,
                expert_email        VARCHAR(150) NOT NULL,
                reason              TEXT         NOT NULL,
                derived_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
                notified_at         TIMESTAMPTZ,
                report_received_at  TIMESTAMPTZ,
                verdict             VARCHAR(20),
                verdict_note        TEXT,
                derived_by          BIGINT       NOT NULL REFERENCES %I.claims_analyst(id),
                expert_firm_id      BIGINT       REFERENCES %I.expert_firm(id) ON DELETE SET NULL,
                report_document_id  BIGINT       REFERENCES %I.case_documents(id),
                case_id             BIGINT       NOT NULL REFERENCES %I.cases(id) ON DELETE CASCADE,

                CONSTRAINT expert_assessment_case_unique UNIQUE (case_id),
                CONSTRAINT expert_assessment_verdict_valid CHECK (
                    verdict IS NULL
                    OR verdict IN ('FRAUD_CONFIRMED', 'FRAUD_DISCARDED', 'INCONCLUSIVE')),
                CONSTRAINT expert_assessment_report_complete CHECK (
                    (report_received_at IS NULL     AND verdict IS NULL)
                    OR (report_received_at IS NOT NULL AND verdict IS NOT NULL))
            )$ddl$, tenant, tenant, tenant, tenant, tenant);

    END LOOP;
END $$;

-- ─── Peritos de demo ─────────────────────────────────────────────────────────
-- Los mismos que siembra seed-demo.sql, para que una base migrada y una creada
-- de cero queden idénticas. Sin al menos uno, el analista no tiene a quién derivar.
INSERT INTO arbiter_bbva.expert_firm (id, name, email, zone, active, branch_id) VALUES
    (1, 'Estudio Verifica S.R.L.',   'perito.arbiter@gmail.com', 'CABA y GBA', TRUE, NULL),
    (2, 'Peritajes Tecnológicos SA', 'perito.arbiter@gmail.com', 'CABA',       TRUE, 1)
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('arbiter_bbva.expert_firm', 'id'),
              (SELECT MAX(id) FROM arbiter_bbva.expert_firm));

INSERT INTO arbiter_provincia.expert_firm (id, name, email, zone, active, branch_id) VALUES
    (1, 'Peritos del Sur S.A.', 'perito.arbiter@gmail.com', 'La Plata', TRUE, NULL)
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('arbiter_provincia.expert_firm', 'id'),
              (SELECT MAX(id) FROM arbiter_provincia.expert_firm));

-- ─── Política de derivación, una por ramo ────────────────────────────────────
-- Sin esta fila el analista NO ve la opción de derivar: el peritaje es opt-in porque
-- abajo de cierto monto cuesta más que el siniestro. Los ids no se fijan a mano acá
-- (a diferencia de init, que crea el esquema vacío): en una base con datos ya hay
-- reglas cargadas y la secuencia asigna el próximo libre.
DO $$
DECLARE
    tenant TEXT;
BEGIN
    FOR tenant IN SELECT schema_name FROM arbiter_common.insurer LOOP
        EXECUTE format($sql$
            INSERT INTO %I.insurer_rule (active, valid_from, name, rule_type, effect, priority,
                                         blocks_fast_track, branch_id, coverage_id, configuration)
            SELECT TRUE, '2026-01-01 00:00:00+00',
                   'Derivar a peritaje desde $500.000 reclamados', 'EXPERT_DERIVATION', 'DERIVAR', 1,
                   FALSE, 1, NULL, '{"minClaimedAmount":500000}'
            WHERE NOT EXISTS (
                SELECT 1 FROM %I.insurer_rule
                WHERE rule_type = 'EXPERT_DERIVATION' AND branch_id = 1 AND coverage_id IS NULL)
            $sql$, tenant, tenant);

        EXECUTE format($sql$
            INSERT INTO %I.insurer_rule (active, valid_from, name, rule_type, effect, priority,
                                         blocks_fast_track, branch_id, coverage_id, configuration)
            SELECT TRUE, '2026-01-01 00:00:00+00',
                   'Derivar a peritaje desde $700.000 reclamados', 'EXPERT_DERIVATION', 'DERIVAR', 1,
                   FALSE, 2, NULL, '{"minClaimedAmount":700000}'
            WHERE NOT EXISTS (
                SELECT 1 FROM %I.insurer_rule
                WHERE rule_type = 'EXPERT_DERIVATION' AND branch_id = 2 AND coverage_id IS NULL)
            $sql$, tenant, tenant);
    END LOOP;
END $$;

COMMIT;
