-- 2026-08-17 · Referral to an expert: PENDING_EXPERT_REPORT, expert_firm, expert_assessment and the
-- EXPERT_DERIVATION policy. Apply before deploying the code (ddl-auto=validate). Idempotent.

BEGIN;

-- The insured sees 'En análisis': telling them about the expert would leak the suspicion.
INSERT INTO arbiter_common.case_status (id, name, description, insured_status, is_final) VALUES
    (7, 'PENDING_EXPERT_REPORT', 'Derivado a peritaje, esperando el informe', 'En análisis', FALSE)
ON CONFLICT (name) DO NOTHING;

SELECT setval(pg_get_serial_sequence('arbiter_common.case_status', 'id'),
              (SELECT MAX(id) FROM arbiter_common.case_status));

DO $$
DECLARE
    tenant TEXT;
BEGIN
    FOR tenant IN SELECT schema_name FROM arbiter_common.insurer LOOP

        EXECUTE format($ddl$
            CREATE TABLE IF NOT EXISTS %I.expert_firm (
                id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name        VARCHAR(120) NOT NULL,
                email       VARCHAR(150) NOT NULL,
                zone        VARCHAR(80),
                active      BOOLEAN      NOT NULL DEFAULT TRUE,
                branch_id   BIGINT       REFERENCES arbiter_common.branch(id)
            )$ddl$, tenant);

        EXECUTE format($ddl$
            CREATE TABLE IF NOT EXISTS %I.expert_assessment (
                id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                expert_name         VARCHAR(120) NOT NULL,
                expert_email        VARCHAR(150) NOT NULL,
                reason              TEXT         NOT NULL,
                derived_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
                notified_at         TIMESTAMPTZ,
                report_received_at  TIMESTAMPTZ,
                verdict             VARCHAR(20),
                verdict_note        TEXT,
                derived_by          BIGINT       NOT NULL REFERENCES %I.claims_analyst(id),
                expert_firm_id      BIGINT       REFERENCES %I.expert_firm(id) ON DELETE SET NULL,
                report_document_id  BIGINT       REFERENCES %I.case_documents(id),
                case_id             BIGINT       NOT NULL REFERENCES %I.cases(id) ON DELETE CASCADE,

                CONSTRAINT expert_assessment_case_unique UNIQUE (case_id),
                CONSTRAINT expert_assessment_verdict_valid CHECK (
                    verdict IS NULL
                    OR verdict IN ('FRAUD_CONFIRMED', 'FRAUD_DISCARDED', 'INCONCLUSIVE')),
                CONSTRAINT expert_assessment_report_complete CHECK (
                    (report_received_at IS NULL     AND verdict IS NULL)
                    OR (report_received_at IS NOT NULL AND verdict IS NOT NULL))
            )$ddl$, tenant, tenant, tenant, tenant, tenant);

    END LOOP;
END $$;

-- Same as seed-demo.sql; without one the analyst has nobody to refer to.
INSERT INTO arbiter_bbva.expert_firm (id, name, email, zone, active, branch_id) VALUES
    (1, 'Estudio Verifica S.R.L.',   'perito.arbiter@gmail.com', 'CABA y GBA', TRUE, NULL),
    (2, 'Peritajes Tecnológicos SA', 'perito.arbiter@gmail.com', 'CABA',       TRUE, 1)
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('arbiter_bbva.expert_firm', 'id'),
              (SELECT MAX(id) FROM arbiter_bbva.expert_firm));

INSERT INTO arbiter_provincia.expert_firm (id, name, email, zone, active, branch_id) VALUES
    (1, 'Peritos del Sur S.A.', 'perito.arbiter@gmail.com', 'La Plata', TRUE, NULL)
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('arbiter_provincia.expert_firm', 'id'),
              (SELECT MAX(id) FROM arbiter_provincia.expert_firm));

-- Without this row the analyst gets no referral option: it is opt-in because below some
-- amount an expert costs more than the claim. Ids come from the sequence.
DO $$
DECLARE
    tenant TEXT;
BEGIN
    FOR tenant IN SELECT schema_name FROM arbiter_common.insurer LOOP
        EXECUTE format($sql$
            INSERT INTO %I.insurer_rule (active, valid_from, name, rule_type, effect, priority,
                                         blocks_fast_track, branch_id, coverage_id, configuration)
            SELECT TRUE, '2026-01-01 00:00:00+00',
                   'Derivar a peritaje desde $500.000 reclamados', 'EXPERT_DERIVATION', 'DERIVAR', 1,
                   FALSE, 1, NULL, '{"minClaimedAmount":500000}'
            WHERE NOT EXISTS (
                SELECT 1 FROM %I.insurer_rule
                WHERE rule_type = 'EXPERT_DERIVATION' AND branch_id = 1 AND coverage_id IS NULL)
            $sql$, tenant, tenant);

        EXECUTE format($sql$
            INSERT INTO %I.insurer_rule (active, valid_from, name, rule_type, effect, priority,
                                         blocks_fast_track, branch_id, coverage_id, configuration)
            SELECT TRUE, '2026-01-01 00:00:00+00',
                   'Derivar a peritaje desde $700.000 reclamados', 'EXPERT_DERIVATION', 'DERIVAR', 1,
                   FALSE, 2, NULL, '{"minClaimedAmount":700000}'
            WHERE NOT EXISTS (
                SELECT 1 FROM %I.insurer_rule
                WHERE rule_type = 'EXPERT_DERIVATION' AND branch_id = 2 AND coverage_id IS NULL)
            $sql$, tenant, tenant);
    END LOOP;
END $$;

COMMIT;
