import { DOCUMENT } from '@angular/common';
import { HttpErrorResponse } from '@angular/common/http';
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  computed,
  inject,
  signal,
} from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { RouterLink } from '@angular/router';

import { clasificacionLabel, clasificacionTone } from '../../../core/models/clasificacion';
import { estadoLabel, estadoTone } from '../../../core/models/estado';
import { formatDateTime, todayIso } from '../../../core/util/datetime';
import { staggerReveal } from '../../../shared/animations';
import { BadgeComponent } from '../../../shared/ui/badge/badge.component';
import { ButtonComponent } from '../../../shared/ui/button/button.component';
import { CardComponent } from '../../../shared/ui/card/card.component';
import { EmptyStateComponent } from '../../../shared/ui/empty-state/empty-state.component';
import { InlineLoadingComponent } from '../../../shared/ui/inline-loading/inline-loading.component';
import { InputComponent } from '../../../shared/ui/input/input.component';
import { PaginationComponent } from '../../../shared/ui/pagination/pagination.component';
import { SelectComponent, SelectOption } from '../../../shared/ui/select/select.component';
import { TableComponent } from '../../../shared/ui/table/table.component';
import { ExpedienteService } from '../../expedientes/expediente.service';
import {
  ReportFormat,
  ResolutionReport,
  ResolutionReportParams,
  decisionLabel,
  formatDuration,
  periodError,
} from './resolution-report';
import { ResolutionReportService } from './resolution-report.service';

/**
 * Resolution report: the claims the insurer closed in a period, with times, classification and
 * decision. Preview in a table, and export to CSV or PDF — the file is generated by
 * reports-service, not here, so the download matches what an auditor would get from the API.
 */
@Component({
  selector: 'app-reportes',
  imports: [
    RouterLink,
    BadgeComponent,
    ButtonComponent,
    CardComponent,
    EmptyStateComponent,
    InlineLoadingComponent,
    InputComponent,
    PaginationComponent,
    SelectComponent,
    TableComponent,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  animations: [staggerReveal],
  templateUrl: './reportes.component.html',
  styleUrl: './reportes.component.scss',
})
export class ReportesComponent {
  private readonly reports = inject(ResolutionReportService);
  private readonly expedientes = inject(ExpedienteService);
  private readonly document = inject(DOCUMENT);
  private readonly destroyRef = inject(DestroyRef);

  protected readonly today = todayIso();
  // Default: the month so far — the question a referent asks most often.
  protected readonly from = signal(`${this.today.slice(0, 8)}01`);
  protected readonly to = signal(this.today);
  protected readonly claimCause = signal('');
  protected readonly claimCauseOptions = signal<SelectOption[]>([]);
  protected readonly periodError = computed(() => periodError(this.from(), this.to()));

  protected readonly report = signal<ResolutionReport | null>(null);
  protected readonly loading = signal(false);
  protected readonly exporting = signal<ReportFormat | null>(null);
  protected readonly error = signal<string | null>(null);

  protected readonly page = signal(0);
  protected readonly pageSize = signal(20);
  protected readonly rows = computed(() => this.report()?.rows ?? []);
  protected readonly totalPages = computed(() => Math.ceil(this.rows().length / this.pageSize()));
  protected readonly pageRows = computed(() => {
    const start = this.page() * this.pageSize();
    return this.rows().slice(start, start + this.pageSize());
  });
  protected readonly averageMinutes = computed(() => {
    const rows = this.rows();
    return rows.length === 0
      ? 0
      : Math.round(rows.reduce((sum, row) => sum + row.totalMinutes, 0) / rows.length);
  });

  protected readonly formatDateTime = formatDateTime;
  protected readonly formatDuration = formatDuration;
  protected readonly decisionLabel = decisionLabel;
  protected readonly estadoLabel = estadoLabel;
  protected readonly estadoTone = estadoTone;
  protected readonly clasificacionLabel = clasificacionLabel;
  protected readonly clasificacionTone = clasificacionTone;

  constructor() {
    this.expedientes
      .claimCauseNames()
      .pipe(takeUntilDestroyed())
      .subscribe({
        next: (names) => this.claimCauseOptions.set(names.map((name) => ({ value: name, label: name }))),
        // Without the catalog the filter still works as "Todos": not worth blocking the screen.
        error: () => this.claimCauseOptions.set([]),
      });
  }

  protected setFrom(value: string): void {
    this.from.set(value);
    this.discardPreview();
  }

  protected setTo(value: string): void {
    this.to.set(value);
    this.discardPreview();
  }

  protected setClaimCause(value: string): void {
    this.claimCause.set(value);
    this.discardPreview();
  }

  protected loadPreview(): void {
    if (this.periodError()) {
      return;
    }
    this.loading.set(true);
    this.error.set(null);
    this.reports
      .preview(this.params())
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: (report) => {
          this.report.set(report);
          this.page.set(0);
          this.loading.set(false);
        },
        error: (err: HttpErrorResponse) => {
          this.loading.set(false);
          this.error.set(errorMessage(err));
        },
      });
  }

  protected exportAs(format: ReportFormat): void {
    if (this.periodError() || this.exporting()) {
      return;
    }
    this.exporting.set(format);
    this.error.set(null);
    this.reports
      .export(this.params(), format)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: ({ blob, filename }) => {
          this.download(blob, filename);
          this.exporting.set(null);
        },
        error: (err: HttpErrorResponse) => {
          this.exporting.set(null);
          this.error.set(errorMessage(err));
        },
      });
  }

  protected setPageSize(size: number): void {
    this.pageSize.set(size);
    this.page.set(0);
  }

  private params(): ResolutionReportParams {
    return { from: this.from(), to: this.to(), claimCause: this.claimCause() };
  }

  /** A preview only describes the parameters it ran with; once one changes, it would mislead. */
  private discardPreview(): void {
    this.report.set(null);
    this.error.set(null);
  }

  private download(blob: Blob, filename: string): void {
    const url = URL.createObjectURL(blob);
    const link = this.document.createElement('a');
    link.href = url;
    link.download = filename;
    link.click();
    URL.revokeObjectURL(url);
  }
}

function errorMessage(err: HttpErrorResponse): string {
  switch (err.status) {
    case 400:
      return 'El período no es válido. Revisá las fechas e intentá de nuevo.';
    case 403:
      return 'Tu sesión no tiene acceso a los reportes de esta aseguradora.';
    default:
      return 'No se pudo generar el reporte. Probá de nuevo en unos minutos.';
  }
}
