import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { Params, RouterLink } from '@angular/router';
import { EChartsCoreOption } from 'echarts/core';
import { Observable } from 'rxjs';

import { clasificacionLabel, clasificacionTone } from '../../../core/models/clasificacion';
import { estadoLabel, estadoTone } from '../../../core/models/estado';
import { StatusTone } from '../../../core/models/status-tone';
import { bucketLabel, formatDate, formatDateTime } from '../../../core/util/datetime';
import { staggerReveal } from '../../../shared/animations';
import { RatePipe } from '../../../shared/pipes/rate.pipe';
import { BadgeComponent } from '../../../shared/ui/badge/badge.component';
import { CardComponent } from '../../../shared/ui/card/card.component';
import { ChartComponent } from '../../../shared/ui/chart/chart.component';
import { ChartTheme, baseChartOptions, readChartTheme } from '../../../shared/ui/chart/chart-theme';
import {
  DistributionComponent,
  DistributionItem,
} from '../../../shared/ui/distribution/distribution.component';
import { EmptyStateComponent } from '../../../shared/ui/empty-state/empty-state.component';
import { InfoTipComponent } from '../../../shared/ui/info-tip/info-tip.component';
import { InlineLoadingComponent } from '../../../shared/ui/inline-loading/inline-loading.component';
import { PaginationComponent } from '../../../shared/ui/pagination/pagination.component';
import { SelectComponent, SelectOption } from '../../../shared/ui/select/select.component';
import { StatTileComponent } from '../../../shared/ui/stat-tile/stat-tile.component';
import { TableComponent } from '../../../shared/ui/table/table.component';
import { ExpedienteService } from '../../expedientes/expediente.service';
import { ReportActionsComponent } from './report-actions.component';
import { ReportFile } from './report-download';
import { ReportFiltersComponent } from './report-filters.component';
import { ReportTab } from './report-tab';
import {
  ReportFormat,
  ResolutionReport,
  ResolutionReportParams,
  ResolutionReportRow,
  decisionLabel,
  fastTrackTrend,
  formatDuration,
  resolvedTrend,
  waitingBreakdown,
} from './resolution-report';
import { ResolutionReportService } from './resolution-report.service';

/**
 * Resolution report: the claims the insurer closed in a period, with times, classification and
 * decision. Preview in a table, and export to CSV or PDF — the file is generated by
 * reports-service, not here, so the download matches what an auditor would get from the API.
 *
 * <p>Period and branch come from {@link ReportFiltersStore} (shared with the fraud tab); the claim
 * cause is this report's own filter and resets with it.
 */
@Component({
  selector: 'app-resolution-report',
  imports: [
    RatePipe,
    RouterLink,
    BadgeComponent,
    CardComponent,
    ChartComponent,
    DistributionComponent,
    EmptyStateComponent,
    InfoTipComponent,
    InlineLoadingComponent,
    PaginationComponent,
    ReportActionsComponent,
    ReportFiltersComponent,
    SelectComponent,
    StatTileComponent,
    TableComponent,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  animations: [staggerReveal],
  templateUrl: './resolution-report.component.html',
  styleUrls: ['./report-params.scss', './report-tab.scss', './resolution-report.component.scss'],
})
export class ResolutionReportComponent extends ReportTab<
  ResolutionReportRow,
  ResolutionReport,
  ResolutionReportParams
> {
  private readonly reports = inject(ResolutionReportService);
  private readonly expedientes = inject(ExpedienteService);
  /** Los colores del design system, leídos una vez: ECharts no entiende `var(--status-ok)`. */
  private readonly theme: ChartTheme = readChartTheme();

  protected readonly claimCause = signal('');
  private readonly claimCauseCatalog = signal<SelectOption[]>([]);
  /**
   * The catalog plus the selected cause if it isn't in it (a link typed by hand, or no catalog):
   * without it the select would read "Todos" over a filtered request.
   */
  protected readonly claimCauseOptions = computed<SelectOption[]>(() => {
    const catalog = this.claimCauseCatalog();
    const selected = this.claimCause();
    return !selected || catalog.some((option) => option.value === selected)
      ? catalog
      : [...catalog, { value: selected, label: selected }];
  });

  /**
   * Straight from the backend rather than added up here: the exported file and the screen have to
   * agree, and two implementations of "average" are one bug away from disagreeing.
   */
  protected readonly summary = computed(() => this.report()?.summary ?? null);

  /** The status does carry the traffic light: from `estadoTone`, same as the table and the dashboard. */
  protected readonly statusItems = computed<DistributionItem[]>(() =>
    (this.summary()?.byStatus ?? []).map((bucket) => ({
      label: estadoLabel(bucket.label),
      count: bucket.count,
      tone: estadoTone(bucket.label),
    })),
  );

  /** The claim cause doesn't communicate state: no traffic light, same as the branch on the dashboard. */
  protected readonly claimCauseItems = computed<DistributionItem[]>(() =>
    (this.summary()?.byClaimCause ?? []).map((bucket) => ({
      label: bucket.label,
      count: bucket.count,
      tone: 'neutral' as StatusTone,
    })),
  );

  /**
   * Cuántos cerraron, y si eso subió o bajó contra el período anterior. La comparación la calcula
   * el backend sobre el período inmediatamente anterior con los mismos filtros: acá sólo se lee.
   */
  protected readonly resolvedSub = computed(() => {
    const current = this.report();
    if (!current) {
      return '';
    }
    const { summary, previousSummary } = current;
    const lapsed = summary.totalCases - summary.decidedCases;
    // Cuántos no decidió nadie sólo se dice cuando los hay: "0 caducados" es ruido.
    const detail = lapsed === 0 ? '' : `${summary.decidedCases} decididos · ${lapsed} caducados`;
    return [resolvedTrend(summary, previousSummary), detail].filter(Boolean).join(' · ');
  });

  /** Ídem para el Fast Track, en puntos porcentuales y sin perder de vista sobre cuántos se mide. */
  protected readonly fastTrackSub = computed(() => {
    const current = this.report();
    if (!current) {
      return '';
    }
    const { summary, previousSummary } = current;
    const detail = `${summary.fastTrackCases} de ${summary.totalCases}`;
    return [detail, fastTrackTrend(summary, previousSummary)].filter(Boolean).join(' · ');
  });

  /**
   * El tiempo promedio a lo largo del período: la línea es el mismo promedio de la tarjeta (sobre
   * los decididos) y las barras, cuántos expedientes cerraron en cada tramo.
   *
   * Las barras no son decoración: un promedio sobre dos expedientes y otro sobre cuarenta se
   * dibujan a la misma altura, y sin el volumen al lado la línea invita a leer como tendencia lo
   * que es el vaivén de tres casos. Los tramos donde nadie decidió cortan la línea en vez de bajar
   * a cero — no se resolvió "en cero minutos", no se resolvió nada.
   *
   * Los colores son los que la app ya usa acá: tinta para el volumen y el teal de "resuelto" para
   * el tiempo, igual que la línea de tiempo del tablero.
   */
  protected readonly timelineChart = computed<EChartsCoreOption>(() => {
    const current = this.report();
    const points = current?.timeline ?? [];
    const granularity = current?.granularity ?? 'DAY';
    const labels = points.map((point) => bucketLabel(point.bucket, granularity));
    const base = baseChartOptions(this.theme);
    return {
      ...base,
      tooltip: {
        ...(base['tooltip'] as object),
        trigger: 'axis',
        formatter: (params: unknown) => {
          const index = (params as { dataIndex: number }[])[0]?.dataIndex ?? 0;
          const point = points[index];
          if (!point) {
            return '';
          }
          const unit = point.resolved === 1 ? 'expediente cerrado' : 'expedientes cerrados';
          const average =
            point.averageMinutes === null
              ? 'sin decisiones en el tramo'
              : `promedio ${formatDuration(point.averageMinutes)} sobre ${point.decided}`;
          return `${labels[index]}<br>${point.resolved} ${unit}<br>${average}`;
        },
      },
      legend: {
        data: ['Tiempo promedio', 'Expedientes cerrados'],
        bottom: 0,
        textStyle: { color: this.theme.muted },
        icon: 'roundRect',
      },
      grid: { left: 8, right: 8, top: 16, bottom: 44, containLabel: true },
      xAxis: {
        type: 'category',
        data: labels,
        axisLine: { lineStyle: { color: this.theme.grid } },
        axisTick: { show: false },
        axisLabel: { color: this.theme.muted },
      },
      yAxis: [
        {
          type: 'value',
          // El eje va en minutos pero se rotula en la misma unidad que la tarjeta ("2 d", "5 h"):
          // "4320" no se lee, y forzar días aplasta contra el cero a los Fast Track de horas.
          axisLabel: {
            color: this.theme.muted,
            formatter: (value: number) => formatDuration(value),
          },
          splitLine: { lineStyle: { color: this.theme.grid } },
        },
        {
          type: 'value',
          minInterval: 1,
          axisLabel: { color: this.theme.muted },
          splitLine: { show: false },
        },
      ],
      series: [
        {
          name: 'Expedientes cerrados',
          type: 'bar',
          yAxisIndex: 1,
          data: points.map((point) => point.resolved),
          itemStyle: { color: this.theme.ink, opacity: 0.25, borderRadius: [3, 3, 0, 0] },
          barMaxWidth: 28,
        },
        {
          name: 'Tiempo promedio',
          type: 'line',
          yAxisIndex: 0,
          data: points.map((point) => point.averageMinutes),
          symbolSize: 6,
          lineStyle: { width: 2, color: this.theme.status.ok },
          itemStyle: { color: this.theme.status.ok },
        },
      ],
    };
  });

  /** Lo que el gráfico dice, en palabras: es lo que lee un lector de pantalla en vez del canvas. */
  protected readonly timelineDescription = computed(() => {
    const current = this.report();
    const points = current?.timeline ?? [];
    const granularity = current?.granularity ?? 'DAY';
    const parts = points.map((point) => {
      const average =
        point.averageMinutes === null ? 'sin decisiones' : formatDuration(point.averageMinutes);
      return `${bucketLabel(point.bucket, granularity)}: ${point.resolved} cerrados, promedio ${average}`;
    });
    return `Tiempo promedio de resolución a lo largo del período. ${parts.join('. ')}.`;
  });

  /** Por qué está agrupado así. Con poco volumen, el día a día es casi todo ceros. */
  protected readonly granularityNote = computed(() => {
    switch (this.report()?.granularity) {
      case 'WEEK':
        return 'Agrupado por semana: con este volumen, el detalle diario sería casi todo ceros';
      case 'MONTH':
        return 'Agrupado por mes';
      default:
        return 'Día a día';
    }
  });

  protected readonly formatDate = formatDate;
  protected readonly formatDateTime = formatDateTime;
  protected readonly formatDuration = formatDuration;
  protected readonly decisionLabel = decisionLabel;
  protected readonly waitingBreakdown = waitingBreakdown;
  protected readonly estadoLabel = estadoLabel;
  protected readonly estadoTone = estadoTone;
  protected readonly clasificacionLabel = clasificacionLabel;
  protected readonly clasificacionTone = clasificacionTone;

  constructor() {
    super();
    this.expedientes
      .claimCauseNames()
      .pipe(takeUntilDestroyed())
      .subscribe({
        next: (names) =>
          this.claimCauseCatalog.set(names.map((name) => ({ value: name, label: name }))),
        // Without the catalog the filter still works: claimCauseOptions names the selected one.
        error: () => this.claimCauseCatalog.set([]),
      });

    this.claimCause.set(this.route.snapshot.queryParamMap.get('claimCause')?.trim() ?? '');
    this.start();
  }

  protected setClaimCause(value: string): void {
    this.claimCause.set(value);
    this.discardPreview();
  }

  protected override fetchReport(params: ResolutionReportParams): Observable<ResolutionReport> {
    return this.reports.preview(params);
  }

  protected override fetchFile(
    params: ResolutionReportParams,
    format: ReportFormat,
  ): Observable<ReportFile> {
    return this.reports.export(params, format);
  }

  protected override tabParams(): Params {
    return { claimCause: this.claimCause() || undefined };
  }

  protected override params(): ResolutionReportParams {
    return {
      from: this.filters.from(),
      to: this.filters.to(),
      branchId: this.filters.branchId(),
      claimCause: this.claimCause(),
    };
  }
}
