import { DOCUMENT, PercentPipe } from '@angular/common';
import { HttpErrorResponse } from '@angular/common/http';
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  computed,
  effect,
  inject,
  signal,
} from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { RouterLink } from '@angular/router';

import { clasificacionLabel, clasificacionTone } from '../../../core/models/clasificacion';
import { estadoLabel, estadoTone } from '../../../core/models/estado';
import { StatusTone } from '../../../core/models/status-tone';
import { formatDateTime } from '../../../core/util/datetime';
import { staggerReveal } from '../../../shared/animations';
import { BadgeComponent } from '../../../shared/ui/badge/badge.component';
import { ButtonComponent } from '../../../shared/ui/button/button.component';
import { CardComponent } from '../../../shared/ui/card/card.component';
import {
  DistributionComponent,
  DistributionItem,
} from '../../../shared/ui/distribution/distribution.component';
import { EmptyStateComponent } from '../../../shared/ui/empty-state/empty-state.component';
import { InlineLoadingComponent } from '../../../shared/ui/inline-loading/inline-loading.component';
import { PaginationComponent } from '../../../shared/ui/pagination/pagination.component';
import { SelectComponent, SelectOption } from '../../../shared/ui/select/select.component';
import { StatTileComponent } from '../../../shared/ui/stat-tile/stat-tile.component';
import { TableComponent } from '../../../shared/ui/table/table.component';
import { ExpedienteService } from '../../expedientes/expediente.service';
import { downloadReport, reportErrorMessage } from './report-download';
import { ReportFiltersComponent } from './report-filters.component';
import { ReportFiltersStore } from './report-filters.store';
import {
  ReportFormat,
  ResolutionReport,
  ResolutionReportParams,
  decisionLabel,
  formatDuration,
} from './resolution-report';
import { ResolutionReportService } from './resolution-report.service';

/**
 * Resolution report: the claims the insurer closed in a period, with times, classification and
 * decision. Preview in a table, and export to CSV or PDF — the file is generated by
 * reports-service, not here, so the download matches what an auditor would get from the API.
 *
 * <p>Period and branch come from {@link ReportFiltersStore} (shared with the fraud tab); the claim
 * cause is this report's own filter and resets with it.
 */
@Component({
  selector: 'app-resolution-report',
  imports: [
    PercentPipe,
    RouterLink,
    BadgeComponent,
    ButtonComponent,
    CardComponent,
    DistributionComponent,
    EmptyStateComponent,
    InlineLoadingComponent,
    PaginationComponent,
    ReportFiltersComponent,
    SelectComponent,
    StatTileComponent,
    TableComponent,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  animations: [staggerReveal],
  templateUrl: './resolution-report.component.html',
  styleUrls: ['./report-params.scss', './resolution-report.component.scss'],
})
export class ResolutionReportComponent {
  private readonly reports = inject(ResolutionReportService);
  private readonly expedientes = inject(ExpedienteService);
  private readonly document = inject(DOCUMENT);
  private readonly destroyRef = inject(DestroyRef);
  protected readonly filters = inject(ReportFiltersStore);

  protected readonly claimCause = signal('');
  protected readonly claimCauseOptions = signal<SelectOption[]>([]);

  protected readonly report = signal<ResolutionReport | null>(null);
  protected readonly loading = signal(false);
  protected readonly exporting = signal<ReportFormat | null>(null);
  protected readonly error = signal<string | null>(null);

  protected readonly page = signal(0);
  protected readonly pageSize = signal(20);
  protected readonly rows = computed(() => this.report()?.rows ?? []);
  protected readonly totalPages = computed(() => Math.ceil(this.rows().length / this.pageSize()));
  protected readonly pageRows = computed(() => {
    const start = this.page() * this.pageSize();
    return this.rows().slice(start, start + this.pageSize());
  });
  /**
   * Straight from the backend rather than added up here: the exported file and the screen have to
   * agree, and two implementations of "average" are one bug away from disagreeing.
   */
  protected readonly summary = computed(() => this.report()?.summary ?? null);

  /** El estado sí comunica semáforo: sale de `estadoTone`, igual que en la tabla y en el tablero. */
  protected readonly statusItems = computed<DistributionItem[]>(() =>
    (this.summary()?.byStatus ?? []).map((bucket) => ({
      label: estadoLabel(bucket.label),
      count: bucket.count,
      tone: estadoTone(bucket.label),
    })),
  );

  /** El hecho generador no comunica estado: sin semáforo, igual que el ramo en el tablero. */
  protected readonly claimCauseItems = computed<DistributionItem[]>(() =>
    (this.summary()?.byClaimCause ?? []).map((bucket) => ({
      label: bucket.label,
      count: bucket.count,
      tone: 'neutral' as StatusTone,
    })),
  );

  protected readonly formatDateTime = formatDateTime;
  protected readonly formatDuration = formatDuration;
  protected readonly decisionLabel = decisionLabel;
  protected readonly estadoLabel = estadoLabel;
  protected readonly estadoTone = estadoTone;
  protected readonly clasificacionLabel = clasificacionLabel;
  protected readonly clasificacionTone = clasificacionTone;

  constructor() {
    this.expedientes
      .claimCauseNames()
      .pipe(takeUntilDestroyed())
      .subscribe({
        next: (names) =>
          this.claimCauseOptions.set(names.map((name) => ({ value: name, label: name }))),
        // Without the catalog the filter still works as "Todos": not worth blocking the screen.
        error: () => this.claimCauseOptions.set([]),
      });

    // The shared filters are edited outside this component, so discarding the stale preview has to
    // react to them rather than hang off a setter.
    effect(() => {
      this.filters.from();
      this.filters.to();
      this.filters.branchId();
      this.discardPreview();
    });
  }

  protected setClaimCause(value: string): void {
    this.claimCause.set(value);
    this.discardPreview();
  }

  protected loadPreview(): void {
    if (this.filters.periodError()) {
      return;
    }
    this.loading.set(true);
    this.error.set(null);
    this.reports
      .preview(this.params())
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: (report) => {
          this.report.set(report);
          this.page.set(0);
          this.loading.set(false);
        },
        error: (err: HttpErrorResponse) => {
          this.loading.set(false);
          this.error.set(reportErrorMessage(err));
        },
      });
  }

  protected exportAs(format: ReportFormat): void {
    if (this.filters.periodError() || this.exporting()) {
      return;
    }
    this.exporting.set(format);
    this.error.set(null);
    this.reports
      .export(this.params(), format)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: ({ blob, filename }) => {
          downloadReport(this.document, blob, filename);
          this.exporting.set(null);
        },
        error: (err: HttpErrorResponse) => {
          this.exporting.set(null);
          this.error.set(reportErrorMessage(err));
        },
      });
  }

  protected setPageSize(size: number): void {
    this.pageSize.set(size);
    this.page.set(0);
  }

  private params(): ResolutionReportParams {
    return {
      from: this.filters.from(),
      to: this.filters.to(),
      branchId: this.filters.branchId(),
      claimCause: this.claimCause(),
    };
  }

  /** A preview only describes the parameters it ran with; once one changes, it would mislead. */
  private discardPreview(): void {
    this.report.set(null);
    this.error.set(null);
  }
}
