import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ActivatedRoute, Params, RouterLink } from '@angular/router';
import { Observable } from 'rxjs';

import { clasificacionLabel, clasificacionTone } from '../../../core/models/clasificacion';
import { estadoLabel, estadoTone } from '../../../core/models/estado';
import { StatusTone } from '../../../core/models/status-tone';
import { formatDate, formatDateTime } from '../../../core/util/datetime';
import { staggerReveal } from '../../../shared/animations';
import { RatePipe } from '../../../shared/pipes/rate.pipe';
import { BadgeComponent } from '../../../shared/ui/badge/badge.component';
import { CardComponent } from '../../../shared/ui/card/card.component';
import {
  DistributionComponent,
  DistributionItem,
} from '../../../shared/ui/distribution/distribution.component';
import { EmptyStateComponent } from '../../../shared/ui/empty-state/empty-state.component';
import { InfoTipComponent } from '../../../shared/ui/info-tip/info-tip.component';
import { InlineLoadingComponent } from '../../../shared/ui/inline-loading/inline-loading.component';
import { PaginationComponent } from '../../../shared/ui/pagination/pagination.component';
import { SelectComponent, SelectOption } from '../../../shared/ui/select/select.component';
import { StatTileComponent } from '../../../shared/ui/stat-tile/stat-tile.component';
import { TableComponent } from '../../../shared/ui/table/table.component';
import { ExpedienteService } from '../../expedientes/expediente.service';
import { ReportActionsComponent } from './report-actions.component';
import { ReportFile } from './report-download';
import { ReportFiltersComponent } from './report-filters.component';
import { ReportFiltersStore } from './report-filters.store';
import { ReportTab } from './report-tab';
import {
  ReportFormat,
  ResolutionReport,
  ResolutionReportParams,
  ResolutionReportRow,
  decisionLabel,
  formatDuration,
  waitingBreakdown,
} from './resolution-report';
import { ResolutionReportService } from './resolution-report.service';

/**
 * Resolution report: the claims the insurer closed in a period, with times, classification and
 * decision. Preview in a table, and export to CSV or PDF — the file is generated by
 * reports-service, not here, so the download matches what an auditor would get from the API.
 *
 * <p>Period and branch come from {@link ReportFiltersStore} (shared with the fraud tab); the claim
 * cause is this report's own filter and resets with it.
 */
@Component({
  selector: 'app-resolution-report',
  imports: [
    RatePipe,
    RouterLink,
    BadgeComponent,
    CardComponent,
    DistributionComponent,
    EmptyStateComponent,
    InfoTipComponent,
    InlineLoadingComponent,
    PaginationComponent,
    ReportActionsComponent,
    ReportFiltersComponent,
    SelectComponent,
    StatTileComponent,
    TableComponent,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  animations: [staggerReveal],
  templateUrl: './resolution-report.component.html',
  styleUrls: ['./report-params.scss', './report-tab.scss', './resolution-report.component.scss'],
})
export class ResolutionReportComponent extends ReportTab<
  ResolutionReportRow,
  ResolutionReport,
  ResolutionReportParams
> {
  private readonly reports = inject(ResolutionReportService);
  private readonly expedientes = inject(ExpedienteService);

  protected readonly claimCause = signal('');
  private readonly claimCauseCatalog = signal<SelectOption[]>([]);
  /**
   * The catalog plus the selected cause if it isn't in it (a link typed by hand, or no catalog):
   * without it the select would read "Todos" over a filtered request.
   */
  protected readonly claimCauseOptions = computed<SelectOption[]>(() => {
    const catalog = this.claimCauseCatalog();
    const selected = this.claimCause();
    return !selected || catalog.some((option) => option.value === selected)
      ? catalog
      : [...catalog, { value: selected, label: selected }];
  });

  /**
   * Straight from the backend rather than added up here: the exported file and the screen have to
   * agree, and two implementations of "average" are one bug away from disagreeing.
   */
  protected readonly summary = computed(() => this.report()?.summary ?? null);

  /** The status does carry the traffic light: from `estadoTone`, same as the table and the dashboard. */
  protected readonly statusItems = computed<DistributionItem[]>(() =>
    (this.summary()?.byStatus ?? []).map((bucket) => ({
      label: estadoLabel(bucket.label),
      count: bucket.count,
      tone: estadoTone(bucket.label),
    })),
  );

  /** The claim cause doesn't communicate state: no traffic light, same as the branch on the dashboard. */
  protected readonly claimCauseItems = computed<DistributionItem[]>(() =>
    (this.summary()?.byClaimCause ?? []).map((bucket) => ({
      label: bucket.label,
      count: bucket.count,
      tone: 'neutral' as StatusTone,
    })),
  );

  protected readonly formatDate = formatDate;
  protected readonly formatDateTime = formatDateTime;
  protected readonly formatDuration = formatDuration;
  protected readonly decisionLabel = decisionLabel;
  protected readonly waitingBreakdown = waitingBreakdown;
  protected readonly estadoLabel = estadoLabel;
  protected readonly estadoTone = estadoTone;
  protected readonly clasificacionLabel = clasificacionLabel;
  protected readonly clasificacionTone = clasificacionTone;

  constructor() {
    super();
    this.expedientes
      .claimCauseNames()
      .pipe(takeUntilDestroyed())
      .subscribe({
        next: (names) =>
          this.claimCauseCatalog.set(names.map((name) => ({ value: name, label: name }))),
        // Without the catalog the filter still works: claimCauseOptions names the selected one.
        error: () => this.claimCauseCatalog.set([]),
      });

    this.claimCause.set(this.route.snapshot.queryParamMap.get('claimCause')?.trim() ?? '');
    this.start();
  }

  protected setClaimCause(value: string): void {
    this.claimCause.set(value);
    this.discardPreview();
  }

  protected override fetchReport(params: ResolutionReportParams): Observable<ResolutionReport> {
    return this.reports.preview(params);
  }

  protected override fetchFile(
    params: ResolutionReportParams,
    format: ReportFormat,
  ): Observable<ReportFile> {
    return this.reports.export(params, format);
  }

  protected override tabParams(): Params {
    return { claimCause: this.claimCause() || undefined };
  }

  protected override params(): ResolutionReportParams {
    return {
      from: this.filters.from(),
      to: this.filters.to(),
      branchId: this.filters.branchId(),
      claimCause: this.claimCause(),
    };
  }
}
