package ar.edu.utn.frba.arbiter.reports.support;

import org.springframework.jdbc.core.JdbcTemplate;

import java.sql.Timestamp;
import java.time.Instant;

/**
 * The tables of cases-service and classification-service that the resolution report reads. They
 * aren't entities of this module — that's the point of {@code ResolvedCaseRepository} — so
 * {@code ddl-auto=update} never creates them and the tests build them here, with the same shape as
 * {@code db/init-multitenant.sql} but only the columns the query touches.
 *
 * <p>Flat schema, like the rest of {@link AbstractPersistenceIT}: everything lands in
 * {@code public} instead of a tenant schema plus {@code arbiter_common}.
 */
public final class CaseTables {

    public static final long PENDING_REVIEW = 2;
    public static final long APPROVED = 5;
    public static final long REJECTED = 6;
    public static final long LAPSED = 8;

    public static final long ROBO_CELULARES = 2;
    public static final long HURTO_CELULARES = 3;
    public static final long HURTO_TECNOLOGIA = 8;

    public static final long LAURA = 1;
    public static final long JUAN = 2;

    private final JdbcTemplate jdbcTemplate;

    public CaseTables(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    /** DDL: call it once per class, outside any test transaction. */
    public void create() {
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS case_status (
                    id        BIGINT PRIMARY KEY,
                    name      VARCHAR(60) NOT NULL UNIQUE,
                    is_final  BOOLEAN     NOT NULL
                );
                CREATE TABLE IF NOT EXISTS branch (
                    id    BIGINT PRIMARY KEY,
                    name  VARCHAR(100) NOT NULL
                );
                CREATE TABLE IF NOT EXISTS claim_cause (
                    id         BIGINT PRIMARY KEY,
                    name       VARCHAR(100) NOT NULL,
                    branch_id  BIGINT NOT NULL REFERENCES branch(id)
                );
                CREATE TABLE IF NOT EXISTS insured (
                    id       BIGINT PRIMARY KEY,
                    name     VARCHAR(255) NOT NULL,
                    surname  VARCHAR(255) NOT NULL,
                    dni      VARCHAR(20)  NOT NULL
                );
                CREATE TABLE IF NOT EXISTS claims_analyst (
                    id       BIGINT PRIMARY KEY,
                    name     VARCHAR(255) NOT NULL,
                    surname  VARCHAR(255) NOT NULL
                );
                CREATE TABLE IF NOT EXISTS case_classification (
                    id          BIGINT PRIMARY KEY,
                    decision    VARCHAR(20) NOT NULL,
                    analyst_id  BIGINT NOT NULL REFERENCES claims_analyst(id)
                );
                CREATE TABLE IF NOT EXISTS cases (
                    id                 BIGINT PRIMARY KEY,
                    reported_at        TIMESTAMPTZ NOT NULL,
                    was_fast_track     BOOLEAN     NOT NULL DEFAULT FALSE,
                    current_status_id  BIGINT      NOT NULL REFERENCES case_status(id),
                    analyst_id         BIGINT      REFERENCES claims_analyst(id),
                    insured_id         BIGINT      NOT NULL REFERENCES insured(id),
                    claim_cause_id     BIGINT      NOT NULL REFERENCES claim_cause(id),
                    classification_id  BIGINT      REFERENCES case_classification(id)
                );
                CREATE TABLE IF NOT EXISTS case_status_history (
                    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    changed_at         TIMESTAMPTZ NOT NULL,
                    initial_status_id  BIGINT REFERENCES case_status(id),
                    final_status_id    BIGINT NOT NULL REFERENCES case_status(id),
                    case_id            BIGINT NOT NULL REFERENCES cases(id)
                );
                CREATE TABLE IF NOT EXISTS llm_analysis (
                    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    recommendation  VARCHAR(50) NOT NULL,
                    case_id         BIGINT NOT NULL REFERENCES cases(id)
                );
                """);
    }

    /** Empties everything and leaves the catalogs seeded. Call it before each test. */
    public void reset() {
        jdbcTemplate.execute("""
                TRUNCATE case_status_history, llm_analysis, cases, case_classification,
                         claims_analyst, insured, claim_cause, branch, case_status CASCADE
                """);
        jdbcTemplate.execute("""
                INSERT INTO case_status (id, name, is_final) VALUES
                    (2, 'PENDING_ANALYST_REVIEW', FALSE), (5, 'APPROVED', TRUE),
                    (6, 'REJECTED', TRUE), (8, 'LAPSED', TRUE);
                INSERT INTO branch (id, name) VALUES (1, 'Celulares'), (2, 'Tecnología Portátil');
                INSERT INTO claim_cause (id, name, branch_id) VALUES
                    (2, 'Robo en vía pública', 1), (3, 'Hurto', 1), (8, 'Hurto', 2);
                INSERT INTO insured (id, name, surname, dni) VALUES (1, 'Ana', 'Pérez', '30.111.222');
                INSERT INTO claims_analyst (id, name, surname) VALUES (1, 'Laura', 'Gómez'), (2, 'Juan', 'Ruiz');
                """);
    }

    public void insertCase(long id, String reportedAt, long statusId, long claimCauseId, boolean fastTrack,
                           Long analystId, Long classificationId) {
        jdbcTemplate.update("""
                INSERT INTO cases (id, reported_at, was_fast_track, current_status_id, analyst_id,
                                   insured_id, claim_cause_id, classification_id)
                VALUES (?, ?, ?, ?, ?, 1, ?, ?)
                """, id, Timestamp.from(Instant.parse(reportedAt)), fastTrack, statusId, analystId,
                claimCauseId, classificationId);
    }

    public void transition(long caseId, Long fromStatusId, long toStatusId, String changedAt) {
        jdbcTemplate.update("""
                INSERT INTO case_status_history (changed_at, initial_status_id, final_status_id, case_id)
                VALUES (?, ?, ?, ?)
                """, Timestamp.from(Instant.parse(changedAt)), fromStatusId, toStatusId, caseId);
    }

    public void recommendation(long caseId, String recommendation) {
        jdbcTemplate.update("INSERT INTO llm_analysis (recommendation, case_id) VALUES (?, ?)",
                recommendation, caseId);
    }

    public void decision(long id, String decision, long analystId) {
        jdbcTemplate.update("INSERT INTO case_classification (id, decision, analyst_id) VALUES (?, ?, ?)",
                id, decision, analystId);
    }
}
