package ar.edu.utn.frba.arbiter.reports.support;

import org.springframework.jdbc.core.JdbcTemplate;

import java.sql.Timestamp;
import java.time.Instant;

/**
 * The tables of cases-service and classification-service that the resolution report reads. They
 * aren't entities of this module — that's the point of {@code ResolvedCaseRepository} — so
 * {@code ddl-auto=update} never creates them and the tests build them here, with the same shape as
 * {@code db/init-multitenant.sql} but only the columns the query touches.
 *
 * <p>Flat schema, like the rest of {@link AbstractPersistenceIT}: everything lands in
 * {@code public} instead of a tenant schema plus {@code arbiter_common}.
 */
public final class CaseTables {

    public static final long PENDING_REVIEW = 2;
    /** One of CaseStatus.pausingTheTerm(): the case is waiting on somebody outside the insurer. */
    public static final long AWAITING_DOCUMENTATION = 3;
    public static final long APPROVED = 5;
    public static final long REJECTED = 6;
    public static final long LAPSED = 8;

    public static final long CELULARES = 1;
    public static final long TECNOLOGIA_PORTATIL = 2;

    public static final long ROBO_CELULARES = 2;
    public static final long HURTO_CELULARES = 3;
    public static final long HURTO_TECNOLOGIA = 8;

    public static final long LAURA = 1;
    public static final long JUAN = 2;

    public static final long ANA = 1;
    public static final long DIEGO = 2;

    private final JdbcTemplate jdbcTemplate;

    public CaseTables(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    /** DDL: call it once per class, outside any test transaction. */
    public void create() {
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS case_status (
                    id        BIGINT PRIMARY KEY,
                    name      VARCHAR(60) NOT NULL UNIQUE,
                    is_final  BOOLEAN     NOT NULL
                );
                CREATE TABLE IF NOT EXISTS branch (
                    id    BIGINT PRIMARY KEY,
                    name  VARCHAR(100) NOT NULL
                );
                CREATE TABLE IF NOT EXISTS claim_cause (
                    id         BIGINT PRIMARY KEY,
                    name       VARCHAR(100) NOT NULL,
                    branch_id  BIGINT NOT NULL REFERENCES branch(id)
                );
                CREATE TABLE IF NOT EXISTS insured (
                    id       BIGINT PRIMARY KEY,
                    name     VARCHAR(255) NOT NULL,
                    surname  VARCHAR(255) NOT NULL,
                    dni      VARCHAR(20)  NOT NULL
                );
                CREATE TABLE IF NOT EXISTS claims_analyst (
                    id       BIGINT PRIMARY KEY,
                    name     VARCHAR(255) NOT NULL,
                    surname  VARCHAR(255) NOT NULL
                );
                CREATE TABLE IF NOT EXISTS case_classification (
                    id          BIGINT PRIMARY KEY,
                    decision    VARCHAR(20) NOT NULL,
                    analyst_id  BIGINT NOT NULL REFERENCES claims_analyst(id)
                );
                CREATE TABLE IF NOT EXISTS cases (
                    id                 BIGINT PRIMARY KEY,
                    reported_at        TIMESTAMPTZ NOT NULL,
                    response_deadline  DATE        NOT NULL,
                    was_fast_track     BOOLEAN     NOT NULL DEFAULT FALSE,
                    fraud_determined   BOOLEAN     NOT NULL DEFAULT FALSE,
                    claimed_amount     NUMERIC(38,2),
                    current_status_id  BIGINT      NOT NULL REFERENCES case_status(id),
                    analyst_id         BIGINT      REFERENCES claims_analyst(id),
                    insured_id         BIGINT      NOT NULL REFERENCES insured(id),
                    claim_cause_id     BIGINT      NOT NULL REFERENCES claim_cause(id),
                    classification_id  BIGINT      REFERENCES case_classification(id),
                    risk_band          VARCHAR(20)
                );
                CREATE TABLE IF NOT EXISTS case_status_history (
                    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    changed_at         TIMESTAMPTZ NOT NULL,
                    initial_status_id  BIGINT REFERENCES case_status(id),
                    final_status_id    BIGINT NOT NULL REFERENCES case_status(id),
                    case_id            BIGINT NOT NULL REFERENCES cases(id)
                );
                CREATE TABLE IF NOT EXISTS case_settlement (
                    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    settled_amount              NUMERIC(15,2) NOT NULL,
                    deductible_amount           NUMERIC(15,2) NOT NULL DEFAULT 0,
                    pending_installments_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
                    overdue_balance_amount      NUMERIC(15,2) NOT NULL DEFAULT 0,
                    status                      VARCHAR(25)   NOT NULL,
                    confirmed_at                TIMESTAMPTZ   NOT NULL,
                    case_id                     BIGINT        NOT NULL UNIQUE REFERENCES cases(id)
                );
                CREATE TABLE IF NOT EXISTS expert_assessment (
                    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    provider_type       VARCHAR(20)  NOT NULL,
                    verdict             VARCHAR(20),
                    repair_outcome      VARCHAR(20),
                    derived_at          TIMESTAMPTZ  NOT NULL,
                    report_received_at  TIMESTAMPTZ,
                    case_id             BIGINT       NOT NULL REFERENCES cases(id)
                );
                CREATE TABLE IF NOT EXISTS insurer_rule (
                    id    BIGINT PRIMARY KEY,
                    name  VARCHAR(150) NOT NULL
                );
                CREATE TABLE IF NOT EXISTS rule_result (
                    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    rule_type  VARCHAR(40) NOT NULL,
                    result     VARCHAR(20) NOT NULL,
                    rule_id    BIGINT REFERENCES insurer_rule(id),
                    case_id    BIGINT NOT NULL REFERENCES cases(id)
                );
                CREATE TABLE IF NOT EXISTS llm_analysis (
                    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    recommendation  VARCHAR(50) NOT NULL,
                    case_id         BIGINT NOT NULL REFERENCES cases(id)
                );
                CREATE TABLE IF NOT EXISTS case_documents (
                    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    type     VARCHAR(255) NOT NULL,
                    case_id  BIGINT NOT NULL REFERENCES cases(id)
                );
                CREATE TABLE IF NOT EXISTS image_analysis (
                    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    is_suspicious     BOOLEAN NOT NULL DEFAULT FALSE,
                    case_document_id  BIGINT  NOT NULL REFERENCES case_documents(id)
                );
                CREATE TABLE IF NOT EXISTS risk_analysis (
                    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    risk_breakdown  JSONB NOT NULL,
                    analyzed_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    case_id         BIGINT NOT NULL REFERENCES cases(id)
                );
                """);
    }

    /** Empties everything and leaves the catalogs seeded. Call it before each test. */
    public void reset() {
        jdbcTemplate.execute("""
                TRUNCATE case_status_history, llm_analysis, case_settlement, expert_assessment,
                         rule_result, insurer_rule, image_analysis, risk_analysis, case_documents,
                         cases, case_classification, claims_analyst, insured, claim_cause, branch,
                         case_status CASCADE
                """);
        jdbcTemplate.execute("""
                INSERT INTO case_status (id, name, is_final) VALUES
                    (2, 'PENDING_ANALYST_REVIEW', FALSE), (3, 'AWAITING_DOCUMENTATION', FALSE),
                    (5, 'APPROVED', TRUE),
                    (6, 'REJECTED', TRUE), (8, 'LAPSED', TRUE);
                INSERT INTO branch (id, name) VALUES (1, 'Celulares'), (2, 'Tecnología Portátil');
                INSERT INTO claim_cause (id, name, branch_id) VALUES
                    (2, 'Robo en vía pública', 1), (3, 'Hurto', 1), (8, 'Hurto', 2);
                INSERT INTO insured (id, name, surname, dni) VALUES
                    (1, 'Ana', 'Pérez', '30.111.222'), (2, 'Diego', 'Ferreyra', '28.904.115');
                INSERT INTO claims_analyst (id, name, surname) VALUES (1, 'Laura', 'Gómez'), (2, 'Juan', 'Ruiz');
                """);
    }

    /**
     * El vencimiento del art. 56 se siembra como lo siembra cases-service al dar de alta la
     * denuncia: 30 días desde ese día. Los tests que miden cumplimiento lo pisan con
     * {@link #deadline}, que es lo que hace el sistema real cuando el plazo se reinicia.
     */
    public void insertCase(long id, String reportedAt, long statusId, long claimCauseId, boolean fastTrack,
                           Long analystId, Long classificationId) {
        jdbcTemplate.update("""
                INSERT INTO cases (id, reported_at, response_deadline, was_fast_track,
                                   current_status_id, analyst_id, insured_id, claim_cause_id,
                                   classification_id)
                VALUES (?, ?, (? AT TIME ZONE 'UTC')::date + 30, ?, ?, ?, 1, ?, ?)
                """, id, Timestamp.from(Instant.parse(reportedAt)),
                Timestamp.from(Instant.parse(reportedAt)), fastTrack, statusId, analystId,
                claimCauseId, classificationId);
    }

    /** La fecha límite del expediente, cuando el test necesita una distinta de la del alta. */
    public void deadline(long caseId, String date) {
        jdbcTemplate.update("UPDATE cases SET response_deadline = ?::date WHERE id = ?", date, caseId);
    }

    public void transition(long caseId, Long fromStatusId, long toStatusId, String changedAt) {
        jdbcTemplate.update("""
                INSERT INTO case_status_history (changed_at, initial_status_id, final_status_id, case_id)
                VALUES (?, ?, ?, ?)
                """, Timestamp.from(Instant.parse(changedAt)), fromStatusId, toStatusId, caseId);
    }

    /** Lo que el asegurado reclamó, que no es obligatorio en la denuncia y por eso no va en el alta. */
    public void claimed(long caseId, String amount) {
        jdbcTemplate.update("UPDATE cases SET claimed_amount = ?::numeric WHERE id = ?", amount, caseId);
    }

    /** La banda que escribió el motor de scoring. Sin llamarla, el expediente queda sin evaluar. */
    public void riskBand(long caseId, String band) {
        jdbcTemplate.update("UPDATE cases SET risk_band = ? WHERE id = ?", band, caseId);
    }

    /** insertCase siembra siempre a Ana; esto lo pasa a otro asegurado (ver {@link #DIEGO}). */
    public void insuredOf(long caseId, long insuredId) {
        jdbcTemplate.update("UPDATE cases SET insured_id = ? WHERE id = ?", insuredId, caseId);
    }

    /** Un adjunto del expediente con su análisis forense de imagen ya corrido. */
    public void image(long caseId, String documentType, boolean suspicious) {
        Long documentId = jdbcTemplate.queryForObject("""
                INSERT INTO case_documents (type, case_id) VALUES (?, ?) RETURNING id
                """, Long.class, documentType, caseId);
        jdbcTemplate.update(
                "INSERT INTO image_analysis (is_suspicious, case_document_id) VALUES (?, ?)",
                suspicious, documentId);
    }

    /**
     * Un run del motor de scoring con el factor {@code document_inconsistency} en el desglose —
     * con hallazgo si {@code rationale} no es null, limpio si lo es. Corridas más nuevas pisan a
     * las más viejas para la señal, igual que hace el motor real con {@code cases.risk_band}: la
     * última es la que cuenta.
     */
    public void riskAnalysis(long caseId, String rationale, String analyzedAt) {
        double rawScore = rationale == null ? 0.0 : 1.0;
        String cleanRationale = rationale == null
                ? "Los datos de los documentos coinciden con los del siniestro"
                : rationale.replace("\"", "\\\"");
        String breakdown = ("[{\"factorId\":\"document_inconsistency\",\"rawScore\":%s,"
                + "\"weight\":0.45,\"weightedContribution\":%s,\"rationale\":\"%s\"}]")
                .formatted(rawScore, rawScore * 0.45, cleanRationale);
        jdbcTemplate.update(
                "INSERT INTO risk_analysis (case_id, risk_breakdown, analyzed_at) VALUES (?, ?::jsonb, ?)",
                caseId, breakdown, Timestamp.from(Instant.parse(analyzedAt)));
    }

    /** El analista determinó que el siniestro era fraudulento. */
    public void fraudDetermined(long caseId) {
        jdbcTemplate.update("UPDATE cases SET fraud_determined = TRUE WHERE id = ?", caseId);
    }

    public void settlement(long caseId, String settledAmount, String status, String confirmedAt,
                           String deductible, String installments, String overdue) {
        jdbcTemplate.update("""
                INSERT INTO case_settlement (settled_amount, deductible_amount,
                                             pending_installments_amount, overdue_balance_amount,
                                             status, confirmed_at, case_id)
                VALUES (?::numeric, ?::numeric, ?::numeric, ?::numeric, ?, ?, ?)
                """, settledAmount, deductible, installments, overdue, status,
                Timestamp.from(Instant.parse(confirmedAt)), caseId);
    }

    /** Una derivación ya devuelta: salió en {@code derivedAt} y contestó en {@code receivedAt}. */
    public void assessment(long caseId, String providerType, String verdict, String repairOutcome,
                           String derivedAt, String receivedAt) {
        jdbcTemplate.update("""
                INSERT INTO expert_assessment (provider_type, verdict, repair_outcome, derived_at,
                                               report_received_at, case_id)
                VALUES (?, ?, ?, ?, ?, ?)
                """, providerType, verdict, repairOutcome, Timestamp.from(Instant.parse(derivedAt)),
                receivedAt == null ? null : Timestamp.from(Instant.parse(receivedAt)), caseId);
    }

    /** Una regla configurada de la aseguradora, para que el resultado tenga nombre. */
    public void rule(long id, String name) {
        jdbcTemplate.update("INSERT INTO insurer_rule (id, name) VALUES (?, ?)", id, name);
    }

    /** Una regla evaluada sobre un expediente. {@code ruleId} nulo = no es fila de insurer_rule. */
    public void ruleResult(long caseId, Long ruleId, String ruleType, String result) {
        jdbcTemplate.update(
                "INSERT INTO rule_result (rule_type, result, rule_id, case_id) VALUES (?, ?, ?, ?)",
                ruleType, result, ruleId, caseId);
    }

    public void recommendation(long caseId, String recommendation) {
        jdbcTemplate.update("INSERT INTO llm_analysis (recommendation, case_id) VALUES (?, ?)",
                recommendation, caseId);
    }

    public void decision(long id, String decision, long analystId) {
        jdbcTemplate.update("INSERT INTO case_classification (id, decision, analyst_id) VALUES (?, ?, ?)",
                id, decision, analystId);
    }
}
