package ar.edu.utn.frba.arbiter.rules.services;

import ar.edu.utn.frba.arbiter.rules.config.tenant.TenantContext;
import ar.edu.utn.frba.arbiter.rules.dto.CatalogOption;
import ar.edu.utn.frba.arbiter.rules.exceptions.BranchNameConflictException;
import ar.edu.utn.frba.arbiter.rules.support.AbstractPersistenceIT;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Each insurer owns its branches: what a referent does to the catalog in one schema must not show
 * up in another. Two real schemas, because the isolation is the {@code search_path}'s doing and a
 * mocked repository can't prove it.
 */
@SpringBootTest
class BranchTenantIsolationTests extends AbstractPersistenceIT {

    private static final String BBVA = "arbiter_it_bbva";
    private static final String PROVINCIA = "arbiter_it_provincia";

    @Autowired
    private BranchCatalogService service;

    @Autowired
    private JdbcTemplate jdbc;

    /** Both start from the same catalog with the same ids, like two insurers after onboarding. */
    @BeforeEach
    void twoInsurersWithTheSameStartingCatalog() {
        for (String schema : List.of(BBVA, PROVINCIA)) {
            jdbc.execute("DROP SCHEMA IF EXISTS " + schema + " CASCADE");
            jdbc.execute("CREATE SCHEMA " + schema);
            jdbc.execute("""
                    CREATE TABLE %1$s.branch (
                        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name            VARCHAR(100) NOT NULL UNIQUE,
                        external_name   VARCHAR(100) UNIQUE
                    )""".formatted(schema));
            jdbc.execute("""
                    CREATE TABLE %1$s.claim_cause (
                        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name        VARCHAR(100) NOT NULL,
                        branch_id   BIGINT       NOT NULL REFERENCES %1$s.branch(id),
                        CONSTRAINT claim_cause_branch_name_unique UNIQUE (branch_id, name)
                    )""".formatted(schema));
            jdbc.execute("INSERT INTO %s.branch (id, name, external_name) VALUES (1, 'Celulares', 'Celulares')"
                    .formatted(schema));
            jdbc.execute("SELECT setval(pg_get_serial_sequence('%s.branch', 'id'), 1)".formatted(schema));
        }
    }

    @AfterEach
    void clearTenant() {
        TenantContext.clear();
    }

    @Test
    void renamingABranchLeavesTheOtherInsurersUntouched() {
        TenantContext.set(PROVINCIA);
        service.rename(1L, "Equipos Móviles");

        TenantContext.set(BBVA);
        assertThat(service.list()).containsExactly(new CatalogOption(1L, "Celulares"));

        TenantContext.set(PROVINCIA);
        assertThat(service.list()).containsExactly(new CatalogOption(1L, "Equipos Móviles"));
        // The rename is display-only: policies of the insurer database keep matching.
        assertThat(jdbc.queryForObject(
                "SELECT external_name FROM " + PROVINCIA + ".branch WHERE id = 1", String.class))
                .isEqualTo("Celulares");
    }

    @Test
    void creatingAndDeletingABranchStaysInsideTheInsurer() {
        TenantContext.set(BBVA);
        CatalogOption home = service.create("Hogar");

        TenantContext.set(PROVINCIA);
        assertThat(service.list()).extracting(CatalogOption::name).containsExactly("Celulares");
        service.delete(1L);

        TenantContext.set(BBVA);
        assertThat(service.list()).containsExactly(new CatalogOption(1L, "Celulares"), home);
    }

    @Test
    void theSameNameCanExistInBothInsurersButOnlyOncePerInsurer() {
        TenantContext.set(BBVA);
        service.create("Hogar");

        TenantContext.set(PROVINCIA);
        assertThat(service.create("Hogar").name()).isEqualTo("Hogar");
        assertThatThrownBy(() -> service.create("Hogar")).isInstanceOf(BranchNameConflictException.class);
    }
}
