package ar.edu.utn.frba.arbiter.cases.models.repositories;

import ar.edu.utn.frba.arbiter.cases.models.entities.Case;
import ar.edu.utn.frba.arbiter.cases.models.entities.Policy;
import ar.edu.utn.frba.arbiter.cases.support.AbstractPersistenceIT;
import ar.edu.utn.frba.arbiter.cases.support.CaseFixtures;
import ar.edu.utn.frba.arbiter.common.enums.CaseStatus;
import ar.edu.utn.frba.arbiter.common.enums.Classification;
import ar.edu.utn.frba.arbiter.common.models.entities.Branch;
import ar.edu.utn.frba.arbiter.common.models.entities.CaseState;
import ar.edu.utn.frba.arbiter.common.models.entities.ClaimCause;
import ar.edu.utn.frba.arbiter.common.models.entities.tenant.Coverage;
import ar.edu.utn.frba.arbiter.common.models.entities.tenant.Insured;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Contra Postgres real (Testcontainers), no con {@link CaseAnalysisRepository} mockeado. Cierra el
 * gap #1 del handoff multi-tenant: {@code llm_analysis}/{@code llm_reason}/{@code risk_analysis} no
 * son entidades JPA de este módulo (las escribe classification-service), así que
 * {@code ddl-auto=update} nunca las crea — sin este test, la lógica real del repositorio (el
 * {@code DISTINCT ON}, el parseo de JSONB, el join de factores) no se ejercita nunca contra
 * Postgres, y así pasó desapercibido el bug donde las queries se armaban sobre una conexión del
 * pool en vez de la de Hibernate (ver el comentario de {@link CaseAnalysisRepository}).
 *
 * <p>Las tablas se crean por SQL crudo en {@link #createAnalysisTables()} — mismo shape que
 * {@code db/init-multitenant.sql}, sin la lógica multi-esquema (acá todo es {@code public}).
 *
 * <p>Nombre con sufijo {@code Tests}, no {@code IT}: Surefire (el único plugin de test wireado en
 * este proyecto, sin Failsafe) excluye {@code *IT.java} por default — así corre en {@code mvn test}
 * como el resto de los tests contra Testcontainers de este módulo.
 */
@SpringBootTest
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class CaseAnalysisRepositoryTests extends AbstractPersistenceIT {

    @Autowired
    private CaseAnalysisRepository caseAnalysisRepository;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private CaseRepository caseRepository;

    @Autowired
    private CaseStateRepository caseStateRepository;

    @Autowired
    private BranchRepository branchRepository;

    @Autowired
    private ClaimCauseRepository claimCauseRepository;

    @Autowired
    private InsuredRepository insuredRepository;

    @Autowired
    private PolicyRepository policyRepository;

    @Autowired
    private CoverageRepository coverageRepository;

    @Autowired
    private PolicyCoverageRepository policyCoverageRepository;

    @Autowired
    private UserRepository userRepository;

    /** DDL, no DML: corre una sola vez, fuera de cualquier transacción de test. */
    @BeforeAll
    void createAnalysisTables() {
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS llm_analysis (
                    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    recommendation VARCHAR(50)  NOT NULL,
                    model          VARCHAR(100) NOT NULL,
                    prompt_version VARCHAR(50)  NOT NULL,
                    confidence     NUMERIC(5,3),
                    latency_ms     INTEGER,
                    analyzed_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
                    case_id        BIGINT       NOT NULL REFERENCES cases(id) ON DELETE CASCADE
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS llm_reason (
                    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    reason      TEXT   NOT NULL,
                    analysis_id BIGINT NOT NULL REFERENCES llm_analysis(id) ON DELETE CASCADE
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS risk_analysis (
                    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    risk_score     NUMERIC(4,3) NOT NULL,
                    risk_band      VARCHAR(20)  NOT NULL,
                    risk_breakdown JSONB        NOT NULL,
                    analyzed_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
                    case_id        BIGINT       NOT NULL REFERENCES cases(id) ON DELETE CASCADE
                )
                """);
    }

    @BeforeEach
    void cleanAnalysisTables() {
        // TRUNCATE, no DELETE: @Transactional no envuelve este @BeforeEach porque las tablas de
        // arriba viven fuera del EntityManager, así que cada test limpia lo que dejó el anterior
        // a mano en vez de depender del rollback de Spring.
        jdbcTemplate.execute("TRUNCATE llm_reason, llm_analysis, risk_analysis");
    }

    private CaseState state(CaseStatus status) {
        return caseStateRepository.findByName(status.name())
                .orElseGet(() -> caseStateRepository.save(CaseState.builder()
                        .name(status.name())
                        .description(status.name())
                        .insuredState("En análisis")
                        .isFinal(false)
                        .build()));
    }

    private ClaimCause claimCause(String branchName, String causeName) {
        Branch branch = branchRepository.findByName(branchName)
                .orElseGet(() -> branchRepository.save(CaseFixtures.branch(branchName)));
        return claimCauseRepository.findByBranchIdAndName(branch.getId(), causeName)
                .orElseGet(() -> claimCauseRepository.save(
                        ClaimCause.builder().name(causeName).branch(branch).build()));
    }

    private Insured insured(String dni, String name, String surname) {
        return insuredRepository.findByDni(dni)
                .orElseGet(() -> {
                    Insured person = CaseFixtures.insured(dni, name, surname);
                    person.setUser(userRepository.save(CaseFixtures.user(dni + "@example.com")));
                    return insuredRepository.save(person);
                });
    }

    private Long seedCase(String dni, LocalDate eventDate) {
        Insured owner = insured(dni, "Test", "Insured");
        Policy policy = policyRepository.findByExternalPolicyNumber("POL-IT-" + dni)
                .orElseGet(() -> {
                    Policy p = CaseFixtures.policy("POL-IT-" + dni, "Celular Protegido Básico");
                    p.setInsuredId(owner.getId());
                    return withCoverage(policyRepository.save(p));
                });
        Case entity = caseRepository.save(Case.builder()
                .claimCause(claimCause("Celulares", "Robo en vía pública"))
                .declaredItem("Samsung A56")
                .insured(owner)
                .policy(policy)
                .coverage(testCoverage())
                .description("Descripción de prueba")
                .occurredAt(eventDate.atStartOfDay())
                .eventAddress("CABA")
                .responseDeadline(eventDate.plusDays(30))
                .currentStatus(state(CaseStatus.PENDING_ANALYST_REVIEW))
                .build());
        return entity.getId();
    }

    private long insertLlmAnalysis(Long caseId, String recommendation, Double confidence) {
        return jdbcTemplate.queryForObject("""
                INSERT INTO llm_analysis (recommendation, model, prompt_version, confidence, case_id)
                VALUES (?, 'qwen3-vl', 'v1', ?, ?)
                RETURNING id
                """, Long.class, recommendation, confidence, caseId);
    }

    private void insertLlmReason(long analysisId, String reason) {
        jdbcTemplate.update(
                "INSERT INTO llm_reason (reason, analysis_id) VALUES (?, ?)", reason, analysisId);
    }

    private void insertRiskAnalysis(Long caseId, String riskBand, String riskBreakdownJson) {
        jdbcTemplate.update("""
                INSERT INTO risk_analysis (risk_score, risk_band, risk_breakdown, case_id)
                VALUES (0.5, ?, ?::jsonb, ?)
                """, riskBand, riskBreakdownJson, caseId);
    }

    @Test
    @Transactional
    void readsLatestAnalysis_confidenceAndFactors_forACase() {
        Long caseId = seedCase("50.111.111", LocalDate.of(2026, 6, 1));
        long analysisId = insertLlmAnalysis(caseId, "LLM_RECOMIENDA_APROBAR", 0.812);
        insertLlmReason(analysisId, "Denuncia coherente con la imagen");
        insertLlmReason(analysisId, "Sin siniestros previos");

        Map<Long, CaseAnalysisRepository.CaseAnalysis> result =
                caseAnalysisRepository.findByCaseIds(List.of(caseId));

        CaseAnalysisRepository.CaseAnalysis analysis = result.get(caseId);
        assertThat(analysis.classification()).isEqualTo(Classification.LLM_RECOMIENDA_APROBAR);
        // numeric(5,3): confirma que el BigDecimal->Double de queryAnalysis() lee bien la columna
        // real, no un stub — es justo el punto que el bug de CaseAnalysisRepository rompía.
        assertThat(analysis.confidence()).isEqualTo(0.812);
        assertThat(analysis.factors()).containsExactly(
                "Denuncia coherente con la imagen", "Sin siniestros previos");
    }

    @Test
    @Transactional
    void distinctOn_picksTheNewestRun_notTheFirst() {
        Long caseId = seedCase("50.111.112", LocalDate.of(2026, 6, 2));
        insertLlmAnalysis(caseId, "FALTA_DOCUMENTACION", null);
        long secondRun = insertLlmAnalysis(caseId, "LLM_RECOMIENDA_APROBAR", 0.9);
        insertLlmReason(secondRun, "Documentación completa en el reproceso");

        CaseAnalysisRepository.CaseAnalysis analysis =
                caseAnalysisRepository.findByCaseIds(List.of(caseId)).get(caseId);

        assertThat(analysis.classification()).isEqualTo(Classification.LLM_RECOMIENDA_APROBAR);
        assertThat(analysis.factors()).containsExactly("Documentación completa en el reproceso");
    }

    @Test
    @Transactional
    void parsesRiskBreakdownJsonb_intoStructuredItems() {
        Long caseId = seedCase("50.111.113", LocalDate.of(2026, 6, 3));
        insertRiskAnalysis(caseId, "LOW", """
                [{"factorId":"amount_ratio","rawScore":0.3,"weight":0.45,
                  "weightedContribution":0.135,"rationale":"Monto razonable"}]
                """);

        CaseAnalysisRepository.CaseAnalysis analysis =
                caseAnalysisRepository.findByCaseIds(List.of(caseId)).get(caseId);

        assertThat(analysis.riskBreakdown()).hasSize(1);
        assertThat(analysis.riskBreakdown().get(0).factorId()).isEqualTo("amount_ratio");
        assertThat(analysis.riskBreakdown().get(0).rationale()).isEqualTo("Monto razonable");
    }

    @Test
    @Transactional
    void caseWithNoAnalysisRow_readsAsNone_notAsAnError() {
        // El caso Fast Track: nunca escribe en llm_analysis (constraint de la tabla real lo
        // rechazaría), así que esto también prueba que el repositorio no asume que la fila existe.
        Long caseId = seedCase("50.111.114", LocalDate.of(2026, 6, 4));

        CaseAnalysisRepository.CaseAnalysis analysis =
                caseAnalysisRepository.findByCaseIds(List.of(caseId)).get(caseId);

        assertThat(analysis.classification()).isNull();
        assertThat(analysis.confidence()).isNull();
        assertThat(analysis.factors()).isEmpty();
    }

    @Test
    @Transactional
    void batchesAcrossSeveralCases_inOneRoundTrip() {
        Long caseA = seedCase("50.111.115", LocalDate.of(2026, 6, 5));
        Long caseB = seedCase("50.111.116", LocalDate.of(2026, 6, 6));
        insertLlmAnalysis(caseA, "LLM_RECOMIENDA_APROBAR", 0.7);
        insertLlmAnalysis(caseB, "LLM_NO_RECOMIENDA_APROBAR", 0.4);

        Map<Long, CaseAnalysisRepository.CaseAnalysis> result =
                caseAnalysisRepository.findByCaseIds(List.of(caseA, caseB));

        assertThat(result.get(caseA).classification()).isEqualTo(Classification.LLM_RECOMIENDA_APROBAR);
        assertThat(result.get(caseB).classification()).isEqualTo(Classification.LLM_NO_RECOMIENDA_APROBAR);
    }

    /**
     * La cobertura del catálogo del tenant. Idempotente, mismo patrón que {@code claimCause()}:
     * varias pólizas de un test comparten la definición, que es lo que pasa en la realidad.
     */
    private Coverage testCoverage() {
        return coverageRepository.findByName("Cobertura Celulares")
                .orElseGet(() -> coverageRepository.save(CaseFixtures.coverage("Celulares")));
    }

    /**
     * Deja la póliza con su cobertura contratada. Desde que una póliza tiene VARIAS coberturas, la
     * suma asegurada vive en {@code policy_coverage} y no en {@code policy}, así que sin esta fila
     * la póliza no tiene contra qué evaluarse.
     */
    private Policy withCoverage(Policy policy) {
        policyCoverageRepository.save(CaseFixtures.policyCoverage(policy.getId(), testCoverage(), 1));
        return policy;
    }
}
