-- =============================================================================
-- Arbiter — seed de datos de ASEGURADORAS (BD de la aseguradora, simulada)
--
-- Contexto separado de la BD del sistema (cases, classification_log, ...).
-- Simula la "base de datos de la aseguradora": compañías, pólizas, coberturas,
-- asegurados e historial. Cada fila lleva aseguradora_id (multi-tenant).
--
-- Alcance de negocio (acordado con el equipo): SOLO dos ramos —
--   · Celulares            → coberturas: "Robo de celular", "Hurto"
--   · Tecnología Portátil  → coberturas: "Robo de celular", "Hurto", "Daño accidental"
--
-- Modelo:
--   compania 1──* poliza 1──* cobertura   (la SUMA ASEGURADA vive en cobertura)
--   compania 1──* asegurado
--   poliza   1──* siniestro_historico     (alimenta claim_frequency)
--
-- Regla: TODO expediente (cases.policy_number) se corresponde con una poliza.
--
-- Uso (junto al init.sql del sistema):
--   docker exec -i arbiter-postgres-1 psql -U arbiter -d arbiter < db/datos-aseguradoras.sql
-- =============================================================================

BEGIN;

-- ─── Schema propio de la aseguradora (aislado de las tablas del sistema) ──────
DROP SCHEMA IF EXISTS aseguradora CASCADE;
CREATE SCHEMA aseguradora;

-- ─── compania (tenant) ───────────────────────────────────────────────────────
CREATE TABLE aseguradora.compania (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(255) NOT NULL,
    cuit            VARCHAR(20)  NOT NULL UNIQUE,
    ssn_registro    VARCHAR(20),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ─── asegurado (persona; pertenece a una compañía) ───────────────────────────
CREATE TABLE aseguradora.asegurado (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aseguradora_id  BIGINT       NOT NULL REFERENCES aseguradora.compania(id),
    documento       VARCHAR(20)  NOT NULL,   -- = cases.insured_id (respetar formato de origen)
    cuil            VARCHAR(20),
    nombre          VARCHAR(120) NOT NULL,
    apellido        VARCHAR(120) NOT NULL,
    email           VARCHAR(255),
    telefono        VARCHAR(50),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT asegurado_compania_doc_unique UNIQUE (aseguradora_id, documento)
);

-- ─── poliza (contrato; NO tiene suma asegurada: eso vive en cobertura) ───────
CREATE TABLE aseguradora.poliza (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aseguradora_id        BIGINT        NOT NULL REFERENCES aseguradora.compania(id),
    numero                VARCHAR(80)   NOT NULL,        -- = cases.policy_number
    nro_certificado       VARCHAR(80),
    titular_id            BIGINT        NOT NULL REFERENCES aseguradora.asegurado(id),
    rama                  VARCHAR(80)   NOT NULL,        -- = cases.branch (Celulares | Tecnología Portátil)
    producto              VARCHAR(160)  NOT NULL,        -- = cases.product
    moneda                VARCHAR(3)    NOT NULL DEFAULT 'ARS',
    vigencia_desde        DATE          NOT NULL,
    vigencia_hasta        DATE          NOT NULL,
    -- Estado / cobranza  → policy_standing
    estado_contrato       VARCHAR(20)   NOT NULL,        -- ACTIVA | BAJA | SUSPENDIDA
    estado_pago           VARCHAR(20)   NOT NULL,        -- AL_DIA | SUSPENDIDA | RESUELTA
    cuotas_pagas          INTEGER       NOT NULL DEFAULT 0,
    cuotas_impagas        INTEGER       NOT NULL DEFAULT 0,
    saldo_deuda           NUMERIC(38,2) NOT NULL DEFAULT 0,
    forma_pago            VARCHAR(60),
    -- Reglas de producto (candidatas a moverse al Motor de Reglas)
    max_eventos_anuales   INTEGER,
    segundo_evento_pct    NUMERIC(5,2),
    cubre_grupo_familiar  BOOLEAN       NOT NULL DEFAULT FALSE,
    -- Payload completo del proveedor (los muchos campos que hoy no usamos)
    datos_proveedor       JSONB,
    created_at            TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT poliza_compania_numero_unique UNIQUE (aseguradora_id, numero),
    CONSTRAINT poliza_rama_check CHECK (rama IN ('Celulares', 'Tecnología Portátil')),
    CONSTRAINT poliza_estado_pago_check CHECK (estado_pago IN ('AL_DIA','SUSPENDIDA','RESUELTA'))
);

CREATE INDEX idx_poliza_numero ON aseguradora.poliza (numero);

-- ─── cobertura (cada cobertura de la póliza con su propia suma asegurada) ─────
-- Catálogo acotado: "Robo de celular" y "Hurto" en ambos ramos; "Daño accidental" solo en
-- Tecnología Portátil.
CREATE TABLE aseguradora.cobertura (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aseguradora_id  BIGINT        NOT NULL REFERENCES aseguradora.compania(id),
    poliza_id       BIGINT        NOT NULL REFERENCES aseguradora.poliza(id) ON DELETE CASCADE,
    orden           INTEGER       NOT NULL DEFAULT 1,     -- cobertura1..cobertura20 en el origen
    nombre          VARCHAR(160)  NOT NULL,               -- "Robo de celular" | "Hurto" | "Daño accidental"
    suma_asegurada  NUMERIC(38,2) NOT NULL,               -- alimenta amount_ratio
    franquicia_pct  NUMERIC(5,2),                         -- franquicia deducible (cláusula 344)
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT cobertura_poliza_orden_unique UNIQUE (poliza_id, orden),
    CONSTRAINT cobertura_nombre_check CHECK (nombre IN ('Robo de celular', 'Hurto', 'Daño accidental'))
);

CREATE INDEX idx_cobertura_poliza ON aseguradora.cobertura (poliza_id);

-- ─── siniestro_historico (previos resueltos; alimenta claim_frequency) ───────
CREATE TABLE aseguradora.siniestro_historico (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aseguradora_id      BIGINT       NOT NULL REFERENCES aseguradora.compania(id),
    poliza_id           BIGINT       NOT NULL REFERENCES aseguradora.poliza(id),
    asegurado_id        BIGINT       NOT NULL REFERENCES aseguradora.asegurado(id),
    fecha_ocurrencia    DATE         NOT NULL,
    causa               VARCHAR(120) NOT NULL,
    estado_resolucion   VARCHAR(40)  NOT NULL,   -- LIQUIDADO | RECHAZADO | DESISTIDO | PRESCRIPTO
    monto_indemnizado   NUMERIC(38,2),
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_sinhist_asegurado ON aseguradora.siniestro_historico (asegurado_id);

-- =============================================================================
-- DATOS DE PRUEBA
--
-- Perfiles pensados para ejercitar cada factor de riesgo del scoring:
--   claim_frequency = min(1, previos/3)  → 0 · 1 · 2 · 3+ previos
--   policy_standing = 1.0 si la póliza está con mora, 0.0 si al día
--   amount_ratio    = monto reclamado / suma asegurada de la cobertura
-- =============================================================================

-- ─── Compañías (tenants) ─────────────────────────────────────────────────────
INSERT INTO aseguradora.compania (id, nombre, cuit, ssn_registro) VALUES
    (1, 'BBVA Seguros Argentina S.A.', '30-50006423-0', '0396'),
    (2, 'Provincia Seguros S.A.',      '30-57411408-6', '0326'),
    (3, 'La Segunda Seguros S.A.',     '30-50001328-8', '0331');

-- ─── Asegurados ──────────────────────────────────────────────────────────────
INSERT INTO aseguradora.asegurado (id, aseguradora_id, documento, cuil, nombre, apellido, email, telefono) VALUES
    ( 1, 1, '42.987.654', '27-42987654-1', 'Martina',  'Soteras',  'martina.soteras@example.com',  '11-5555-0001'),  -- 0 previos
    ( 2, 1, '30.555.777', '20-30555777-3', 'Julián',   'Pérez',    'julian.perez@example.com',     '11-5555-0002'),  -- 3 previos (reincidente)
    ( 3, 1, '44655366',   '20-44655366-9', 'Lucas',    'Martínez', 'lucas.martinez@example.com',   '11-5555-0003'),  -- 0 previos
    ( 4, 2, '35.111.222', '27-35111222-4', 'Carla',    'Gómez',    'carla.gomez@example.com',      '11-5555-0004'),  -- 0 previos
    ( 5, 1, '38.222.111', '20-38222111-5', 'Nicolás',  'Ferreyra', 'nicolas.ferreyra@example.com', '11-5555-0005'),  -- 1 previo
    ( 6, 1, '29.888.444', '27-29888444-2', 'Valeria',  'Ríos',     'valeria.rios@example.com',     '11-5555-0006'),  -- 2 previos
    ( 7, 1, '41.333.999', '20-41333999-7', 'Diego',    'Sosa',     'diego.sosa@example.com',       '11-5555-0007'),  -- 0 previos, póliza con mora
    ( 8, 2, '33.777.222', '27-33777222-8', 'Camila',   'Duarte',   'camila.duarte@example.com',    '11-5555-0008'),  -- 0 previos
    ( 9, 2, '28.444.666', '20-28444666-1', 'Federico', 'Aguirre',  'federico.aguirre@example.com', '11-5555-0009'),  -- 2 previos + mora
    (10, 3, '45.111.888', '27-45111888-3', 'Brenda',   'Molina',   'brenda.molina@example.com',    '11-5555-0010');  -- 0 previos (La Segunda)

-- ─── Pólizas ─────────────────────────────────────────────────────────────────
INSERT INTO aseguradora.poliza (id, aseguradora_id, numero, nro_certificado, titular_id, rama, producto,
                                vigencia_desde, vigencia_hasta, estado_contrato, estado_pago,
                                cuotas_pagas, cuotas_impagas, saldo_deuda, forma_pago,
                                max_eventos_anuales, segundo_evento_pct, cubre_grupo_familiar, datos_proveedor)
VALUES
    -- cases 1, 4 y 5 (Martina) — suma Robo = 1.300.000 reproduce los ratios de init.sql
    ( 1, 1, 'POL-CEL-2026-042', '621242',  1, 'Celulares', 'Celular Protegido Premium',
     '2026-01-01', '2027-01-01', 'ACTIVA', 'AL_DIA', 6, 0, 0.00, 'TARJETA DE CREDITO',
     NULL, NULL, TRUE, NULL),

    -- case 2 (Julián, reincidente) — suma Robo = 1.200.000
    ( 2, 1, 'POL-CEL-2025-099', '621243',  2, 'Celulares', 'Celular Protegido Premium',
     '2025-11-01', '2026-11-01', 'ACTIVA', 'AL_DIA', 8, 0, 0.00, 'TARJETA DE CREDITO',
     NULL, NULL, TRUE, NULL),

    -- case 3 (Lucas) — sumas bajas
    ( 3, 1, '2030405', '621244',  3, 'Celulares', 'Celular Protegido Básico',
     '2026-01-15', '2027-01-15', 'ACTIVA', 'AL_DIA', 5, 0, 0.00, 'DEBITO',
     NULL, NULL, TRUE, NULL),

    -- Provincia (Carla) — Tecnología Portátil, con deuda (cuota impaga) y payload de proveedor
    ( 4, 2, 'POL-TEC-2026-311', '700841',  4, 'Tecnología Portátil', 'Seguro de Tecnología Portátil',
     '2026-03-01', '2027-03-01', 'ACTIVA', 'AL_DIA', 4, 1, 3406.17, 'TARJETA DE CREDITO',
     2, 50.00, FALSE,
     '{"codRamaSegR":7,"nroPolizaR":2365301,"nroCertificadoR":621242,"descProductoR":"07 150 CELU CONS 4000","importePrimaTarifa":2762.5,"importePremio":3406.17,"clausulaAjuste":"AJUSTE TASA FIJA","codClausulaAjuste":105}'::jsonb),

    -- Nicolás: 1 previo, al día → riesgo bajo/medio según monto
    ( 5, 1, 'POL-CEL-2026-118', '621245',  5, 'Celulares', 'Celular Protegido Básico',
     '2026-02-01', '2027-02-01', 'ACTIVA', 'AL_DIA', 5, 0, 0.00, 'DEBITO',
     NULL, NULL, FALSE, NULL),

    -- Valeria: 2 previos, al día → empuja claim_frequency
    ( 6, 1, 'POL-CEL-2025-204', '621246',  6, 'Celulares', 'Celular Protegido Premium',
     '2025-09-01', '2026-09-01', 'ACTIVA', 'AL_DIA', 10, 0, 0.00, 'TARJETA DE CREDITO',
     NULL, NULL, TRUE, NULL),

    -- Diego: SIN previos pero póliza con mora → policy_standing = 1.0 (suma riesgo)
    ( 7, 1, 'POL-CEL-2026-077', '621247',  7, 'Celulares', 'Celular Protegido Premium',
     '2026-03-01', '2027-03-01', 'ACTIVA', 'SUSPENDIDA', 2, 3, 45000.00, 'TARJETA DE CREDITO',
     NULL, NULL, FALSE, NULL),

    -- Segunda póliza de Martina, ramo Tecnología Portátil → variedad de ramo, mismo asegurado
    ( 8, 1, 'POL-TEC-2026-050', '621248',  1, 'Tecnología Portátil', 'Seguro de Tecnología Portátil',
     '2026-01-01', '2027-01-01', 'ACTIVA', 'AL_DIA', 6, 0, 0.00, 'DEBITO',
     NULL, NULL, TRUE, NULL),

    -- Provincia (Camila) — Tecnología Portátil, al día
    ( 9, 2, 'POL-TEC-2026-412', '700842',  8, 'Tecnología Portátil', 'Seguro de Tecnología Portátil',
     '2026-04-01', '2027-04-01', 'ACTIVA', 'AL_DIA', 4, 0, 0.00, 'DEBITO',
     2, 50.00, FALSE, NULL),

    -- Provincia (Federico) — 2 previos + póliza con mora → perfil de riesgo ALTO
    (10, 2, 'POL-TEC-2025-380', '700843',  9, 'Tecnología Portátil', 'Seguro de Tecnología Portátil',
     '2025-08-01', '2026-08-01', 'ACTIVA', 'SUSPENDIDA', 3, 4, 8200.00, 'TARJETA DE CREDITO',
     2, 50.00, FALSE, NULL),

    -- La Segunda (Brenda) — tercer tenant, Celulares
    (11, 3, 'POL-CEL-2026-909', '900110', 10, 'Celulares', 'Celular Protegido Básico',
     '2026-05-01', '2027-05-01', 'ACTIVA', 'AL_DIA', 3, 0, 0.00, 'TARJETA DE CREDITO',
     NULL, NULL, FALSE, NULL);

-- ─── Coberturas (la suma asegurada vive acá) ─────────────────────────────────
-- Sumas de POL-CEL-2026-042 y POL-CEL-2025-099 elegidas para reproducir los ratios
-- de los cases de init.sql (285.000/1.300.000=21,9% · 950.000/1.200.000=79% · etc.).
INSERT INTO aseguradora.cobertura (aseguradora_id, poliza_id, orden, nombre, suma_asegurada, franquicia_pct) VALUES
    (1,  1, 1, 'Robo de celular', 1300000.00, 10.00),
    (1,  1, 2, 'Hurto',            650000.00, 10.00),

    (1,  2, 1, 'Robo de celular', 1200000.00, 10.00),

    (1,  3, 1, 'Robo de celular',  200000.00, 10.00),
    (1,  3, 2, 'Hurto',             50000.00,  0.00),

    -- Tecnología Portátil → suma "Daño accidental"
    (2,  4, 1, 'Robo de celular',  170000.00, 10.00),
    (2,  4, 2, 'Daño accidental',             90000.00, 10.00),

    (1,  5, 1, 'Robo de celular',  800000.00, 10.00),

    (1,  6, 1, 'Robo de celular', 1500000.00, 10.00),
    (1,  6, 2, 'Hurto',            400000.00, 15.00),

    (1,  7, 1, 'Robo de celular', 1100000.00, 10.00),

    (1,  8, 1, 'Robo de celular',  900000.00, 10.00),
    (1,  8, 2, 'Daño accidental',            120000.00, 10.00),

    (2,  9, 1, 'Robo de celular',  950000.00, 10.00),
    (2,  9, 2, 'Daño accidental',            100000.00, 10.00),

    (2, 10, 1, 'Robo de celular',  700000.00, 10.00),

    (3, 11, 1, 'Robo de celular',  600000.00, 10.00);

-- ─── Historial de siniestros previos (alimenta claim_frequency) ──────────────
INSERT INTO aseguradora.siniestro_historico (aseguradora_id, poliza_id, asegurado_id,
                                             fecha_ocurrencia, causa, estado_resolucion, monto_indemnizado)
VALUES
    -- Julián (2): 3 previos → claim_frequency = 1.0 (riesgo ALTO)
    (1,  2, 2, '2025-11-18', 'Robo en vía pública', 'LIQUIDADO', 640000.00),
    (1,  2, 2, '2026-02-05', 'Robo en vía pública', 'LIQUIDADO', 710000.00),
    (1,  2, 2, '2026-04-22', 'Robo en vía pública', 'RECHAZADO', NULL),
    -- Nicolás (5): 1 previo
    (1,  5, 5, '2026-03-20', 'Robo en vía pública', 'LIQUIDADO', 380000.00),
    -- Valeria (6): 2 previos
    (1,  6, 6, '2025-10-12', 'Hurto',               'LIQUIDADO', 520000.00),
    (1,  6, 6, '2026-01-30', 'Robo en vía pública', 'RECHAZADO', NULL),
    -- Federico (9, Provincia): 2 previos
    (2, 10, 9, '2025-09-15', 'Robo en vía pública', 'LIQUIDADO', 410000.00),
    (2, 10, 9, '2026-02-20', 'Robo en vía pública', 'LIQUIDADO', 480000.00);
-- Martina (1), Lucas (3), Carla (4), Diego (7), Camila (8) y Brenda (10): sin previos → claim_frequency = 0

-- ─── Resetear secuencias ─────────────────────────────────────────────────────
SELECT setval('aseguradora.compania_id_seq',            (SELECT MAX(id) FROM aseguradora.compania));
SELECT setval('aseguradora.asegurado_id_seq',           (SELECT MAX(id) FROM aseguradora.asegurado));
SELECT setval('aseguradora.poliza_id_seq',              (SELECT MAX(id) FROM aseguradora.poliza));
SELECT setval('aseguradora.cobertura_id_seq',           (SELECT MAX(id) FROM aseguradora.cobertura));
SELECT setval('aseguradora.siniestro_historico_id_seq', (SELECT MAX(id) FROM aseguradora.siniestro_historico));

COMMIT;

-- =============================================================================
-- OPCIONAL — atar cada expediente del sistema a su aseguradora de origen.
-- cases hoy solo tiene policy_number; conviene desnormalizar el tenant:
--
-- ALTER TABLE cases ADD COLUMN IF NOT EXISTS aseguradora_id BIGINT;
-- UPDATE cases c
--    SET aseguradora_id = p.aseguradora_id
--   FROM aseguradora.poliza p
--  WHERE p.numero = c.policy_number;
-- =============================================================================
