-- =============================================================================
-- Arbiter — script de inicialización de BD
-- Dropea tablas legacy + actuales, recrea el schema limpio y seedea datos de prueba.
--
-- Uso:
--   docker exec -i arbiter-postgres-1 psql -U arbiter -d arbiter < db/init.sql
-- =============================================================================

BEGIN;

-- ─── Limpiar tablas legacy y actuales ────────────────────────────────────────
DROP TABLE IF EXISTS adjunto CASCADE;
DROP TABLE IF EXISTS claim CASCADE;
DROP TABLE IF EXISTS clasificacion_log CASCADE;
DROP TABLE IF EXISTS siniestro CASCADE;
DROP TABLE IF EXISTS classification_log CASCADE;
DROP TABLE IF EXISTS case_status_history CASCADE;
DROP TABLE IF EXISTS case_documents CASCADE;
DROP TABLE IF EXISTS cases CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- ─── users (auth-service) ────────────────────────────────────────────────────
-- H0001 - Inicio de sesión. Login propio como paso transitorio hasta integrar Auth0
-- (ver CLAUDE.md, decisión #8).
CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(255) NOT NULL UNIQUE,
    password_hash   VARCHAR(255) NOT NULL,
    nombre          VARCHAR(255) NOT NULL,
    apellido        VARCHAR(255) NOT NULL,
    rol             VARCHAR(40)  NOT NULL,
    sector          VARCHAR(255),
    fecha_ingreso   DATE,
    insured_id      VARCHAR(255),
    failed_attempts INTEGER      NOT NULL DEFAULT 0,
    locked_until    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT users_rol_check CHECK (
        rol IN ('ASEGURADO', 'ANALISTA_SINIESTROS', 'REFERENTE_ASEGURADORA')
    )
);

-- ─── cases (cases-service) ───────────────────────────────────────────────────
CREATE TABLE cases (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch                  VARCHAR(255) NOT NULL,
    product                 VARCHAR(255) NOT NULL,
    claim_cause             VARCHAR(255) NOT NULL,
    insured_item            VARCHAR(255) NOT NULL,
    insured_id              VARCHAR(255) NOT NULL,
    insured_name            VARCHAR(255),
    policy_number           VARCHAR(255) NOT NULL,
    description             TEXT         NOT NULL,
    event_date              TIMESTAMP(6) NOT NULL,
    event_location          VARCHAR(255) NOT NULL,
    claimed_amount          NUMERIC(38,2),
    status                  VARCHAR(40)  NOT NULL,
    analysis_classification VARCHAR(40),
    analysis_confidence     DOUBLE PRECISION,
    analysis_detail         TEXT,
    deterministic_fast_track BOOLEAN,
    risk_score              DOUBLE PRECISION,
    risk_band               VARCHAR(20),
    risk_breakdown          TEXT,
    manual_adjustment_note  TEXT,
    classification_attempts INTEGER      NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_cases_risk_band ON cases (risk_band);

-- ─── case_documents (cases-service) ──────────────────────────────────────────
-- Adjuntos del expediente: un registro por tipo de documento por caso (upsert por tipo).
CREATE TABLE case_documents (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id         BIGINT       NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
    type            VARCHAR(80)  NOT NULL,
    filename        VARCHAR(255) NOT NULL,
    content_type    VARCHAR(255) NOT NULL,
    content         BYTEA        NOT NULL,
    uploaded_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT case_documents_case_type_unique UNIQUE (case_id, type)
);

-- ─── case_status_history (cases-service) ─────────────────────────────────────
-- Registro append-only de cada transición de estado del expediente (trazabilidad).
CREATE TABLE case_status_history (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id     BIGINT       NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
    from_status VARCHAR(40),
    to_status   VARCHAR(40)  NOT NULL,
    actor       VARCHAR(20)  NOT NULL,
    reason      VARCHAR(255) NOT NULL,
    changed_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ─── classification_log (classification-service) ─────────────────────────────
CREATE TABLE classification_log (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id             BIGINT,
    model               VARCHAR(80),
    prompt_version      VARCHAR(80),
    source              VARCHAR(40)  NOT NULL,
    classification      VARCHAR(40)  NOT NULL,
    confidence          NUMERIC(4,3),
    factors             TEXT         NOT NULL,
    latency_ms          BIGINT,
    risk_score          NUMERIC(4,3),
    risk_band           VARCHAR(20),
    risk_breakdown      TEXT,
    insured_name        VARCHAR(255),
    analyst_id          VARCHAR(80),
    decision            VARCHAR(20),
    decision_timestamp  TIMESTAMPTZ,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT classification_log_classification_check CHECK (
        classification IN (
            'FAST_TRACK',
            'FALTA_DOCUMENTACION',
            'LLM_RECOMIENDA_APROBAR',
            'LLM_NO_RECOMIENDA_APROBAR',
            'LLM_SOLICITA_REVISION_MANUAL'
        )
    )
);

-- ─── Datos de prueba: users ───────────────────────────────────────────────────
-- password_hash queda fijo/sin uso real: con AUTH_PROVIDER=auth0 el login valida contra Auth0,
-- no contra este hash (columna NOT NULL, se completa igual). Las contraseñas reales están
-- cargadas en el tenant de Auth0 con la convención '<rol>.arbiter123' (ej. analista.arbiter123).
-- Los emails usan un dominio real (gmail.com) porque el alta valida registros MX —
-- .test (RFC 2606) nunca resuelve, por eso no se usa más acá.
INSERT INTO users (id, email, password_hash, nombre, apellido, rol, sector, fecha_ingreso)
VALUES
    (2, 'analista.arbiter@gmail.com', '$2a$10$/hsOFJuuoiB23a3Gr.zgYO9UuOSopLRsiiu37CMAIIL1yMFr8EGlq',
     'Lucas', 'Gómez', 'ANALISTA_SINIESTROS', 'Siniestros Celulares', '2024-03-01'),
    (3, 'referente.arbiter@gmail.com', '$2a$10$/hsOFJuuoiB23a3Gr.zgYO9UuOSopLRsiiu37CMAIIL1yMFr8EGlq',
     'Sofía', 'Martínez', 'REFERENTE_ASEGURADORA', 'Administración', '2022-06-15');

SELECT setval('users_id_seq', (SELECT MAX(id) FROM users));

-- ─── Datos de prueba: cases ──────────────────────────────────────────────────
INSERT INTO cases (id, branch, product, claim_cause, insured_item, insured_id, insured_name, policy_number,
                   description, event_date, event_location, claimed_amount,
                   status, analysis_classification, analysis_confidence, analysis_detail,
                   deterministic_fast_track, risk_score, risk_band, risk_breakdown,
                   manual_adjustment_note, classification_attempts)
VALUES
    -- Case 1: Fast Track determinístico (rotura accidental, monto bajo, primer siniestro) → riesgo BAJO real (scoreado)
    (1, 'Celulares', 'Celular Protegido Premium', 'Rotura accidental',
     'Samsung Galaxy S25 Ultra', '42.987.654', 'Sofía Martínez', 'POL-CEL-2026-042',
     'Se me cayó el celular de las manos en mi casa. Se rompió la pantalla pero el equipo funciona normalmente',
     '2026-06-14 08:30:00', 'Casa', 285000.00,
     'PENDING_ANALYST_REVIEW', 'FAST_TRACK', 1.0,
     'Monto reclamado (21.9% de la suma asegurada) dentro del límite de Fast Track (50.0%), Póliza al día con sus pagos',
     TRUE,
     0.099, 'LOW',
     '[{"factorId":"amount_ratio","rawScore":0.2192,"weight":0.45,"weightedContribution":0.0986,"rationale":"Monto reclamado es 22% de la suma asegurada"},{"factorId":"claim_frequency","rawScore":0.0,"weight":0.35,"weightedContribution":0.0,"rationale":"Siniestros previos del asegurado: 0"},{"factorId":"policy_standing","rawScore":0.0,"weight":0.2,"weightedContribution":0.0,"rationale":"Póliza al día con sus pagos"}]',
     NULL, 0),

    -- Case 2: LLM no recomienda aprobar (reincidente, monto alto) → riesgo ALTO + nota del analista (no sobrescribe el score)
    (2, 'Celulares', 'Celular Protegido Premium', 'Robo en vía pública',
     'iPhone 16 Pro Max', '30.555.777', 'Marcelo Gómez', 'POL-CEL-2025-099',
     'Me robaron el celular pero no me acuerdo bien dónde ni cuándo. Fue el martes o miércoles pasado, creo que cerca de Palermo',
     '2026-06-10 23:00:00', 'Palermo o Belgrano (no precisa)', 950000.00,
     'PENDING_ANALYST_REVIEW', 'LLM_NO_RECOMIENDA_APROBAR', 0.95,
     'Más de 2 claims en los últimos 12 meses: el asegurado tiene 3 claims previos (Nov 2025, Feb 2026 y Abr 2026). La descripción del incidente presenta inconsistencias con el reporte policial.',
     FALSE,
     0.706, 'HIGH',
     '[{"factorId":"amount_ratio","rawScore":0.7917,"weight":0.45,"weightedContribution":0.3563,"rationale":"Monto reclamado es 79% de la suma asegurada"},{"factorId":"claim_frequency","rawScore":1.0,"weight":0.35,"weightedContribution":0.35,"rationale":"Siniestros previos del asegurado: 3"},{"factorId":"policy_standing","rawScore":0.0,"weight":0.2,"weightedContribution":0.0,"rationale":"Póliza al día con sus pagos"}]',
     'Score elevado por reincidencia; verifiqué las 3 denuncias previas — dos con resolución legítima. Mantengo el caso en revisión estándar, sin sobrescribir el valor calculado.', 0),

    -- Case 3: Falta documentación, póliza fuera del catálogo mock → SIN SCOREAR (riesgo NULL, no LOW) → sin nombre resuelto tampoco
    (3, 'Celulares', 'Bolso – Compra Protegida', 'Robo en vía pública',
     'Samsung Galaxy A50', '44655366', NULL, '2030405',
     'Estaba saliendo de la facultad y me robaron desde una moto.',
     '2026-06-30 00:00:00', 'Medrano 951', 120000.00,
     'AWAITING_DOCUMENTATION', 'FALTA_DOCUMENTACION', 1.0,
     'Falta documento requerido: police_report, Falta documento requerido: item_photo',
     FALSE, NULL, NULL, NULL, NULL, 0),

    -- Case 4: Falta documentación (sin foto del bien), monto muy alto → riesgo MEDIO
    (4, 'Celulares', 'Celular Protegido Premium', 'Robo en vía pública',
     'iPhone 16 Pro', '42.987.654', 'Sofía Martínez', 'POL-CEL-2026-042',
     'El celular desapareció pero no sé si me lo robaron o lo perdí. No estoy seguro qué pasó exactamente',
     '2026-06-12 18:30:00', 'Colectivo línea 159', 1200000.00,
     'AWAITING_DOCUMENTATION', 'FALTA_DOCUMENTACION', 1.0,
     'Falta documento requerido: item_photo',
     FALSE,
     0.415, 'MEDIUM',
     '[{"factorId":"amount_ratio","rawScore":0.9231,"weight":0.45,"weightedContribution":0.4154,"rationale":"Monto reclamado es 92% de la suma asegurada"},{"factorId":"claim_frequency","rawScore":0.0,"weight":0.35,"weightedContribution":0.0,"rationale":"Siniestros previos del asegurado: 0"},{"factorId":"policy_standing","rawScore":0.0,"weight":0.2,"weightedContribution":0.0,"rationale":"Póliza al día con sus pagos"}]',
     NULL, 0),

    -- Case 5: Pendiente de clasificación (recién ingresado) → aún sin scorear ni nombre resuelto (riesgo NULL)
    (5, 'Celulares', 'Celular Protegido Premium', 'Robo en vía pública',
     'iPhone 16 Pro', '42.987.654', NULL, 'POL-CEL-2026-042',
     'El celular desapareció pero no sé si me lo robaron o lo perdí. No estoy seguro qué pasó exactamente',
     '2026-06-12 18:30:00', 'Colectivo línea 159', 1200000.00,
     'PENDING_CLASSIFICATION', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);

-- Resetear la secuencia para que el próximo INSERT use id=6
SELECT setval('cases_id_seq', (SELECT MAX(id) FROM cases));

-- ─── Datos de prueba: classification_log ─────────────────────────────────────
INSERT INTO classification_log (id, case_id, model, prompt_version, source, classification,
                                confidence, factors, latency_ms, risk_score, risk_band, risk_breakdown,
                                insured_name, created_at)
VALUES
    -- Log 1: Fast Track por reglas (case 1) → riesgo BAJO
    (1, 1, NULL, NULL, 'RULES_FAST_TRACK', 'FAST_TRACK',
     1.000,
     '["Monto reclamado (21.9% de la suma asegurada) dentro del límite de Fast Track (50.0%)", "Póliza al día con sus pagos"]',
     5, 0.099, 'LOW',
     '[{"factorId":"amount_ratio","rawScore":0.2192,"weight":0.45,"weightedContribution":0.0986,"rationale":"Monto reclamado es 22% de la suma asegurada"},{"factorId":"claim_frequency","rawScore":0.0,"weight":0.35,"weightedContribution":0.0,"rationale":"Siniestros previos del asegurado: 0"},{"factorId":"policy_standing","rawScore":0.0,"weight":0.2,"weightedContribution":0.0,"rationale":"Póliza al día con sus pagos"}]',
     'Sofía Martínez', '2026-06-29 00:27:15.751928+00'),

    -- Log 2: LLM no recomienda (case 2, reincidente) → riesgo ALTO
    (2, 2, 'qwen3-vl', 'classification-v1', 'LLM', 'LLM_NO_RECOMIENDA_APROBAR',
     0.950,
     '["Más de 2 claims en los últimos 12 meses: el asegurado tiene 3 claims previos (Nov 2025, Feb 2026 y Abr 2026). Esto activa la regla ''derivad a investigación'' según las cláusulas de la póliza.", "La descripción del incidente presenta inconsistencias con el reporte policial."]',
     3079602, 0.706, 'HIGH',
     '[{"factorId":"amount_ratio","rawScore":0.7917,"weight":0.45,"weightedContribution":0.3563,"rationale":"Monto reclamado es 79% de la suma asegurada"},{"factorId":"claim_frequency","rawScore":1.0,"weight":0.35,"weightedContribution":0.35,"rationale":"Siniestros previos del asegurado: 3"},{"factorId":"policy_standing","rawScore":0.0,"weight":0.2,"weightedContribution":0.0,"rationale":"Póliza al día con sus pagos"}]',
     'Marcelo Gómez', '2026-06-29 01:21:21.157741+00'),

    -- Log 3: Falta documentación (case 3) → sin scorear ni nombre resuelto (póliza fuera del catálogo mock)
    (3, 3, 'qwen3-vl', 'classification-v1', 'LLM', 'FALTA_DOCUMENTACION',
     1.000,
     '["Falta documento requerido: police_report", "Falta documento requerido: item_photo"]',
     7, NULL, NULL, NULL, NULL, '2026-07-01 22:57:48.286276+00'),

    -- Log 4: Clasificación aislada (sin case, test endpoint) → sin scorear ni nombre
    (4, NULL, 'qwen3-vl', 'classification-v1', 'LLM', 'FALTA_DOCUMENTACION',
     1.000,
     '["Falta documento requerido: police_report", "Falta documento requerido: item_photo"]',
     1, NULL, NULL, NULL, NULL, '2026-07-01 23:13:37.365684+00'),

    -- Log 5: Falta documentación (case 4) → riesgo MEDIO
    (5, 4, 'qwen3-vl', 'classification-v1', 'LLM', 'FALTA_DOCUMENTACION',
     1.000,
     '["Falta documento requerido: item_photo"]',
     0, 0.415, 'MEDIUM',
     '[{"factorId":"amount_ratio","rawScore":0.9231,"weight":0.45,"weightedContribution":0.4154,"rationale":"Monto reclamado es 92% de la suma asegurada"},{"factorId":"claim_frequency","rawScore":0.0,"weight":0.35,"weightedContribution":0.0,"rationale":"Siniestros previos del asegurado: 0"},{"factorId":"policy_standing","rawScore":0.0,"weight":0.2,"weightedContribution":0.0,"rationale":"Póliza al día con sus pagos"}]',
     'Sofía Martínez', '2026-07-01 23:24:15.188195+00');

-- Resetear la secuencia
SELECT setval('classification_log_id_seq', (SELECT MAX(id) FROM classification_log));

-- ─── Datos de prueba: case_status_history ────────────────────────────────────
-- Línea de tiempo de estados por caso (alta + resultado de la clasificación).
INSERT INTO case_status_history (id, case_id, from_status, to_status, actor, reason, changed_at)
VALUES
    -- Case 1: alta → Fast Track a bandeja del analista
    (1, 1, NULL, 'PENDING_CLASSIFICATION', 'INSURED', 'denuncia registrada', '2026-06-29 00:27:10+00'),
    (2, 1, 'PENDING_CLASSIFICATION', 'PENDING_ANALYST_REVIEW', 'SYSTEM', 'clasificación: FAST_TRACK', '2026-06-29 00:27:16+00'),

    -- Case 2: alta → LLM no recomienda a bandeja del analista
    (3, 2, NULL, 'PENDING_CLASSIFICATION', 'INSURED', 'denuncia registrada', '2026-06-29 01:20:00+00'),
    (4, 2, 'PENDING_CLASSIFICATION', 'PENDING_ANALYST_REVIEW', 'SYSTEM', 'clasificación: LLM_NO_RECOMIENDA_APROBAR', '2026-06-29 01:21:21+00'),

    -- Case 3: alta → falta documentación (espera al asegurado)
    (5, 3, NULL, 'PENDING_CLASSIFICATION', 'INSURED', 'denuncia registrada', '2026-07-01 22:57:40+00'),
    (6, 3, 'PENDING_CLASSIFICATION', 'AWAITING_DOCUMENTATION', 'SYSTEM', 'clasificación: FALTA_DOCUMENTACION', '2026-07-01 22:57:48+00'),

    -- Case 4: alta → falta documentación (espera al asegurado)
    (7, 4, NULL, 'PENDING_CLASSIFICATION', 'INSURED', 'denuncia registrada', '2026-07-01 23:24:00+00'),
    (8, 4, 'PENDING_CLASSIFICATION', 'AWAITING_DOCUMENTATION', 'SYSTEM', 'clasificación: FALTA_DOCUMENTACION', '2026-07-01 23:24:15+00'),

    -- Case 5: recién ingresado, sin clasificar todavía
    (9, 5, NULL, 'PENDING_CLASSIFICATION', 'INSURED', 'denuncia registrada', '2026-07-02 10:00:00+00');

-- Resetear la secuencia
SELECT setval('case_status_history_id_seq', (SELECT MAX(id) FROM case_status_history));

COMMIT;
