-- =============================================================================
-- Arbiter — DB initialization script (multi-tenant by schema)
--
-- Source of truth: docs/arbiter der.mdj (36 entities, 54 relationships). Table and
-- column names are the English translation of the DER, following the project's code
-- convention (identifiers in English, Spanish only in business prose).
--
-- One DER entity is deliberately NOT created:
--   · factor — drawn without types or PK; it is an enum, not a table (the factor
--              codes live in classification-service's RiskFactorIds).
-- That leaves 34 tables: 10 shared + 24 per insurer.
--
-- `regla` is not created either: the DER still draws it, but there is no platform-wide
-- rule — every rule belongs to an insurer, so regla_aseguradora is the only one.
-- historial_regla_aseguradora and resultado_regla point at it.
--
-- Materializes architecture decision #10: one PostgreSQL instance, one schema per
-- insurer. NO tenant discriminator column anywhere in a tenant schema — the schema is
-- the tenant, and `insurer` exists only in the shared schema, as the registry that
-- says which tenants exist and which schema to route to.
--
-- Column sizes come from the DER where it states one. Where it only gives the base
-- type, a reasonable width is chosen here and flagged as such.
--
-- Schema layout:
--   arbiter_common         Tenant registry, identity, RBAC, global catalogs.
--   arbiter_bbva           Tenant schema — BBVA Seguros.
--   arbiter_provincia      Tenant schema — Provincia Seguros.
--   aseguradora_bbva       Simulated "BD Aseguradora" (external system) for BBVA.
--   aseguradora_provincia  Idem for Provincia.
--
-- REQUIRED runtime configuration — the services must resolve the tenant schema per
-- request. Set the connection's search_path to "<tenant>, arbiter_common, public" so
-- unqualified table names resolve tenant-first and fall back to the shared catalogs.
-- With that in place ddl-auto MUST be `validate`, never `update`: on `update`
-- Hibernate recreates the arbiter_common tables inside each tenant schema as soon as
-- it fails to find them qualified.
--
-- Usage (Railway):  psql "$DATABASE_URL" -f db/init-multitenant.sql
-- Usage (local):    docker exec -i arbiter-postgres-1 psql -U arbiter -d arbiter < db/init-multitenant.sql
-- =============================================================================

-- Creates only — no DROP anywhere. This script targets an empty database and fails
-- loudly (rather than silently wiping data) if run against one that isn't.
--
-- pgvector lives in `public` so every tenant schema can reference the `vector` type
-- through the search_path fallback. Extensions are database-wide objects: installing
-- it once here replaces the runtime CREATE EXTENSION in PgVectorConfig.
CREATE EXTENSION IF NOT EXISTS vector SCHEMA public;

BEGIN;

CREATE SCHEMA arbiter_common;

-- =============================================================================
-- ARBITER_COMMON — 10 tables
-- Tenant registry, centralized identity, RBAC and the platform-wide catalogs that
-- are identical for every insurer.
-- =============================================================================

-- ─── insurer / "aseguradora" ─────────────────────────────────────────────────
-- The tenant registry. Must be shared: it is what the tenant resolver reads before
-- it knows the tenant. schema_name is the routing key.
CREATE TABLE arbiter_common.insurer (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legal_name      VARCHAR(200) NOT NULL,          -- razon_social
    name            VARCHAR(150) NOT NULL,          -- nombre
    tax_id          VARCHAR(13)  NOT NULL UNIQUE,   -- cuit
    active          BOOLEAN      NOT NULL DEFAULT TRUE,
    schema_name     VARCHAR(60)  NOT NULL UNIQUE    -- nombre_esquema
);

-- ─── users / "usuario" ───────────────────────────────────────────────────────
-- Centralized identity backed by Auth0 (auth0_sub is the subject claim). Shared
-- because login happens before the tenant is known. Per the DER the user carries no
-- name: those live on the role profiles (insured / claims_analyst / insurer_referent),
-- which are per tenant.
CREATE TABLE arbiter_common.users (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Per the DER only token_invitacion is UNIQUE. Worth revisiting: auth0_sub and
    -- email are both login keys, and without a constraint two rows can claim the same
    -- identity.
    auth0_sub               VARCHAR(255) NOT NULL,
    email                   VARCHAR(255) NOT NULL,
    active                  BOOLEAN      NOT NULL DEFAULT TRUE,   -- activo
    failed_attempts         INTEGER      NOT NULL DEFAULT 0,
    locked_until            TIMESTAMPTZ,
    invite_token            VARCHAR(128) UNIQUE,
    invite_expires_at       TIMESTAMPTZ,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),  -- fecha_alta
    last_access_at          TIMESTAMPTZ,                          -- fecha_ultimo_acceso
    activated               BOOLEAN      NOT NULL DEFAULT FALSE
);

-- ─── role, permission, role_permission, user_role / RBAC ─────────────────────
-- Platform-wide: the same roles and permissions apply across every insurer.
CREATE TABLE arbiter_common.role (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code    VARCHAR(80)  NOT NULL UNIQUE,
    name    VARCHAR(255) NOT NULL
);

CREATE TABLE arbiter_common.permission (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE arbiter_common.role_permission (
    role_id       BIGINT NOT NULL REFERENCES arbiter_common.role(id),
    permission_id BIGINT NOT NULL REFERENCES arbiter_common.permission(id),
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE arbiter_common.user_role (
    user_id BIGINT NOT NULL REFERENCES arbiter_common.users(id),
    role_id BIGINT NOT NULL REFERENCES arbiter_common.role(id),
    PRIMARY KEY (user_id, role_id)
);

-- ─── user_insurer / "usuario_aseguradora" ────────────────────────────────────
-- Membership, and the routing table: joined against insurer.schema_name it tells the
-- resolver which schema to serve a request from.
CREATE TABLE arbiter_common.user_insurer (
    user_id     BIGINT NOT NULL REFERENCES arbiter_common.users(id),
    insurer_id  BIGINT NOT NULL REFERENCES arbiter_common.insurer(id),
    PRIMARY KEY (user_id, insurer_id)
);

-- ─── branch / "rama" ─────────────────────────────────────────────────────────
-- Global catalog of insurance lines. Which ones an insurer actually sells is
-- per-tenant: an insurer restricts them through its own document_requirement rows.
CREATE TABLE arbiter_common.branch (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(100) NOT NULL UNIQUE
);

-- ─── claim_cause / "hecho_generador" ─────────────────────────────────────────
-- Global catalog of claim causes. Which ones an insurer accepts, against which
-- coverage, is per-tenant (<tenant>.document_requirement / <tenant>.coverage).
CREATE TABLE arbiter_common.claim_cause (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Not globally unique: the same cause (a street robbery, a theft) applies to more
    -- than one branch, so the name repeats with a different branch_id. Unique within a
    -- branch, though — (branch_id, name) is the natural key.
    name        VARCHAR(100) NOT NULL,
    branch_id   BIGINT       NOT NULL REFERENCES arbiter_common.branch(id),

    CONSTRAINT claim_cause_branch_name_unique UNIQUE (branch_id, name)
);

-- ─── case_status / "estado_expediente" ───────────────────────────────────────
-- The DEFINITION of the case lifecycle states — a platform standard. Each case's
-- transitions are per-tenant (<tenant>.case_status_history).
-- insured_status is the simplified state shown to the insured, who must not see the
-- internal analyst-facing state.
CREATE TABLE arbiter_common.case_status (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(60)  NOT NULL UNIQUE,   -- = common-lib's CaseStatus enum
    description     VARCHAR(255) NOT NULL,
    insured_status  VARCHAR(60)  NOT NULL,          -- estado_asegurado
    is_final        BOOLEAN      NOT NULL DEFAULT FALSE
);

-- =============================================================================
-- ARBITER_COMMON — seed data
-- =============================================================================

INSERT INTO arbiter_common.insurer (id, legal_name, name, tax_id, active, schema_name) VALUES
    (1, 'BBVA Seguros Argentina S.A.', 'BBVA Seguros', '30-50006423-0', TRUE, 'arbiter_bbva'),
    (2, 'Provincia Seguros S.A.',      'Provincia Seguros', '30-57411408-6', TRUE, 'arbiter_provincia');

SELECT setval(pg_get_serial_sequence('arbiter_common.insurer', 'id'),
              (SELECT MAX(id) FROM arbiter_common.insurer));

-- auth0_sub follows the 'auth0|<id>' shape Auth0 issues; these are placeholders until
-- the real tenant is wired. Passwords are not stored here at all any more — that is
-- Auth0's job, per the DER.
INSERT INTO arbiter_common.users (id, auth0_sub, email, active, activated) VALUES
    (1, 'auth0|seed-asegurado',           'asegurado.arbiter@gmail.com',           TRUE, TRUE),
    (2, 'auth0|seed-analista',            'analista.arbiter@gmail.com',            TRUE, TRUE),
    (3, 'auth0|seed-referente',           'referente.arbiter@gmail.com',           TRUE, TRUE),
    -- Analyst on the second insurer: without someone on the other side there is no way
    -- to demonstrate that tenant isolation actually holds.
    (4, 'auth0|seed-analista-provincia',  'analista.provincia.arbiter@gmail.com',  TRUE, TRUE),
    -- Second BBVA policyholder: without one, every claim in the fixtures piles onto
    -- insured(1), which looks less like demo data and more like one very unlucky person.
    (5, 'auth0|6a71248c6b9165b91b479173',  'asegurado2.arbiter@gmail.com',          TRUE, TRUE),
    -- Referent on the second insurer, same reasoning as the analyst above: without one there is
    -- no way to check that the rules backoffice stays inside its own tenant.
    (6, 'auth0|seed-referente-provincia', 'referente.provincia.arbiter@gmail.com',  TRUE, TRUE),
    -- Real team accounts, one per insurer. They exist in Auth0, but the login reads the local
    -- row before validating there, so without these a re-init locks them out.
    (7, 'auth0|seed-analista-provincia-2', 'mocciafederico@hotmail.com',            TRUE, TRUE),
    (8, 'auth0|seed-analista-bbva-2',      'federico21433@hotmail.com',             TRUE, TRUE);

SELECT setval(pg_get_serial_sequence('arbiter_common.users', 'id'),
              (SELECT MAX(id) FROM arbiter_common.users));

-- code matches the UserRole enum values 1:1.
INSERT INTO arbiter_common.role (id, code, name) VALUES
    (1, 'ASEGURADO', 'Asegurado'),
    (2, 'ANALISTA_SINIESTROS', 'Analista de siniestros'),
    (3, 'REFERENTE_ASEGURADORA', 'Referente de aseguradora');

SELECT setval(pg_get_serial_sequence('arbiter_common.role', 'id'),
              (SELECT MAX(id) FROM arbiter_common.role));

INSERT INTO arbiter_common.user_role (user_id, role_id) VALUES
    (1, 1), (2, 2), (3, 3), (4, 2), (6, 3), (7, 2), (8, 2);

-- permission / role_permission stay empty on purpose — no permission catalog has been
-- defined yet, and seeding invented ones would be made-up data.

INSERT INTO arbiter_common.user_insurer (user_id, insurer_id) VALUES
    (1, 1), (2, 1), (3, 1), (4, 2), (6, 2), (7, 2), (8, 1);

-- Los dos ramos que el negocio cubre hoy. Hogar quedó fuera por ahora (no se trabaja con ese
-- ramo todavía), así que Tecnología Portátil pasa a ser el branch 2 y los ids quedan contiguos.
INSERT INTO arbiter_common.branch (id, name) VALUES
    (1, 'Celulares'),
    (2, 'Tecnología Portátil');

SELECT setval(pg_get_serial_sequence('arbiter_common.branch', 'id'),
              (SELECT MAX(id) FROM arbiter_common.branch));

-- Causes repeat across branches on purpose: a street robbery is the same event
-- whether the insured item is a phone or a laptop, but it is a different row because
-- the required documentation and the coverage differ per branch.
INSERT INTO arbiter_common.claim_cause (id, name, branch_id) VALUES
    (1, 'Rotura accidental',   1),   -- Celulares
    (2, 'Robo en vía pública', 1),
    (3, 'Hurto',               1),
    (4, 'Caída',               1),
    (6, 'Daño accidental',     2),   -- Tecnología Portátil (branch 2; Hogar quedó fuera)
    (7, 'Robo en vía pública', 2),
    (8, 'Hurto',               2);

SELECT setval(pg_get_serial_sequence('arbiter_common.claim_cause', 'id'),
              (SELECT MAX(id) FROM arbiter_common.claim_cause));

-- 1:1 with common-lib's CaseStatus. insured_status collapses the internal states into
-- what the insured is allowed to see.
INSERT INTO arbiter_common.case_status (id, name, description, insured_status, is_final) VALUES
    (1, 'PENDING_CLASSIFICATION', 'Denuncia registrada, clasificación en curso',      'En análisis',           FALSE),
    (2, 'PENDING_ANALYST_REVIEW', 'Clasificación lista, esperando al analista',       'En análisis',           FALSE),
    (3, 'AWAITING_DOCUMENTATION', 'Faltan documentos obligatorios de la agenda',      'Falta documentación',   FALSE),
    (4, 'CLASSIFICATION_FAILED',  'La clasificación falló tras agotar reintentos',    'En análisis',           FALSE),
    (5, 'APPROVED',               'El analista aprobó el siniestro',                  'Aprobado',              TRUE),
    (6, 'REJECTED',               'El analista rechazó el siniestro',                 'Rechazado',             TRUE);

SELECT setval(pg_get_serial_sequence('arbiter_common.case_status', 'id'),
              (SELECT MAX(id) FROM arbiter_common.case_status));

-- =============================================================================
-- TENANT SCHEMA TEMPLATE — 24 tables, created once per insurer
-- =============================================================================

-- Takes only the schema name: nothing inside a tenant schema references the insurer,
-- because the schema already is the insurer.
CREATE OR REPLACE FUNCTION arbiter_common.create_tenant_schema(
    p_schema TEXT
) RETURNS VOID AS $fn$
BEGIN
    EXECUTE format('CREATE SCHEMA %I', p_schema);

    -- ─── Role profiles: insured, claims_analyst, insurer_referent ────────────
    -- The DER splits the person out of `usuario`: identity is shared, the profile
    -- belongs to the insurer the person works for or is insured by.

    -- insured / "asegurado"
    EXECUTE format($ddl$
        CREATE TABLE %I.insured (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name            VARCHAR(255) NOT NULL,
            surname         VARCHAR(255) NOT NULL,
            dni             VARCHAR(20)  NOT NULL UNIQUE,
            email           VARCHAR(255),
            phone           VARCHAR(30),
            case_count      INTEGER      NOT NULL DEFAULT 0,  -- cantidad_expedientes
            pep             BOOLEAN      NOT NULL DEFAULT FALSE,
            -- Consent to use their images. Belongs to the person, not to each claim — the
            -- current code has it on the case, which is a bug pending a fix.
            image_consent   BOOLEAN      NOT NULL DEFAULT FALSE,
            user_id         BIGINT       NOT NULL REFERENCES arbiter_common.users(id)
        )$ddl$, p_schema);

    -- claims_analyst / "analista_seguro"
    -- The DER's aseguradora_id is dropped here and everywhere else in the tenant
    -- schema: the schema already identifies the insurer.
    EXECUTE format($ddl$
        CREATE TABLE %I.claims_analyst (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name            VARCHAR(255) NOT NULL,
            surname         VARCHAR(255) NOT NULL,
            email           VARCHAR(255) NOT NULL,
            user_id         BIGINT       NOT NULL REFERENCES arbiter_common.users(id)
        )$ddl$, p_schema);

    -- insurer_referent / "referente_aseguradora"
    EXECUTE format($ddl$
        CREATE TABLE %I.insurer_referent (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name            VARCHAR(255) NOT NULL,
            surname         VARCHAR(255) NOT NULL,
            user_id         BIGINT       NOT NULL REFERENCES arbiter_common.users(id)
        )$ddl$, p_schema);

    -- ─── coverage / "cobertura" ──────────────────────────────────────────────
    -- Local snapshot of the insurer's coverage definitions (decision #10: Arbiter
    -- persists what the BD Aseguradora hands over, it does not query it live).
    EXECUTE format($ddl$
        CREATE TABLE %I.coverage (
            id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name                            VARCHAR(100)  NOT NULL UNIQUE,
            description                     TEXT,
            report_deadline_hours           BIGINT,  -- plazo_denuncia_horas
            max_events_per_year             INTEGER,                 -- tope_eventos_por_anio
            covers_family_group             BOOLEAN       NOT NULL DEFAULT FALSE,
            deductible                      NUMERIC(15,2),           -- franquicia, en puntos porcentuales (10.00 = 10%%)
            claim_exhausts_coverage         BOOLEAN       NOT NULL DEFAULT FALSE,
            is_individual                   BOOLEAN       NOT NULL DEFAULT TRUE,
            waiting_period_days             INTEGER,                 -- carencia_dias
            branch_id                       BIGINT        NOT NULL REFERENCES arbiter_common.branch(id),
            -- clause y exclusions: sin respaldo en el DER (decisiones-reglas-a-validar.md, D3/D7).
            clause                          VARCHAR(20),
            exclusions                      JSONB
        )$ddl$, p_schema);

    -- ─── policy / "poliza" ───────────────────────────────────────────────────
    -- Local snapshot of the policy. external_policy_number is the key back to the
    -- insurer's own system; synced_at records when the snapshot was refreshed.
    EXECUTE format($ddl$
        CREATE TABLE %I.policy (
            id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            external_policy_number  VARCHAR(50)   NOT NULL,
            product                 VARCHAR(1000) NOT NULL,
            sum_insured             NUMERIC(15,2) NOT NULL,
            in_force                BOOLEAN       NOT NULL DEFAULT TRUE,   -- vigente
            synced_at               TIMESTAMPTZ   NOT NULL DEFAULT NOW(),  -- fecha_sincronizacion
            insured_id              BIGINT        NOT NULL REFERENCES %I.insured(id),
            coverage_id             BIGINT        NOT NULL REFERENCES %I.coverage(id),

            CONSTRAINT policy_external_number_unique UNIQUE (external_policy_number)
        )$ddl$, p_schema, p_schema, p_schema);

    -- ─── policy_snapshot / "poliza_consultada" ───────────────────────────────
    -- Point-in-time answer from the BD Aseguradora for one specific claim: what the
    -- policy looked like when the claim was filed. Keeps the classification auditable
    -- even if the insurer's data changes afterwards.
    EXECUTE format($ddl$
        CREATE TABLE %I.policy_snapshot (
            id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            external_policy_number  VARCHAR(50)   NOT NULL,
            sum_insured             NUMERIC(15,2) NOT NULL,
            in_force                BOOLEAN       NOT NULL,
            payments_up_to_date     BOOLEAN       NOT NULL,   -- al_dia → policy_standing factor
            previous_claims         INTEGER       NOT NULL DEFAULT 0,  -- → claim_frequency factor
            queried_at              TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
            insurer_db_payload      JSONB                     -- payload_bd_aseguradora
        )$ddl$, p_schema);

    -- ─── insurer_rule / "regla_aseguradora" ──────────────────────────────────
    -- The insurer's activation and parameterization of a rule. `configuration` is
    -- JSONB so the referente can change thresholds without a redeploy (decision #12).
    -- branch_id is nullable: branch_id IS NULL AND coverage_id IS NULL scopes the rule to
    -- the whole insurer (the schema already identifies it) instead of one branch/coverage —
    -- used by POLICY_IN_FORCE and POLICY_STANDING, which the BBVA HAR confirms are validated
    -- against the policy as a whole, not per coverage (error code 6, "Fecha de Ocurrencia de
    -- Siniestro Fuera de la Vigencia de la Operación Siniestrada", carries no coverage in the
    -- request payload).
    EXECUTE format($ddl$
        CREATE TABLE %I.insurer_rule (
            id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            active              BOOLEAN      NOT NULL DEFAULT TRUE,
            valid_from          TIMESTAMPTZ  NOT NULL,
            configuration       JSONB,
            name                VARCHAR(150) NOT NULL,
            rule_type           VARCHAR(20)  NOT NULL,
            effect              VARCHAR(20),
            priority            INTEGER,
            blocks_fast_track   BOOLEAN      NOT NULL DEFAULT FALSE,
            branch_id           BIGINT       REFERENCES arbiter_common.branch(id),
            coverage_id         BIGINT       REFERENCES %I.coverage(id)
        )$ddl$, p_schema, p_schema);

    -- ─── insurer_rule_history / "historial_regla_aseguradora" ────────────────
    EXECUTE format($ddl$
        CREATE TABLE %I.insurer_rule_history (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            config_version  JSONB        NOT NULL,
            changed_at      TIMESTAMPTZ  NOT NULL,
            reason          VARCHAR(255),
            valid_from      TIMESTAMPTZ  NOT NULL,
            valid_to        TIMESTAMPTZ,
            rule_id         BIGINT       NOT NULL REFERENCES %I.insurer_rule(id),
            changed_by      BIGINT       REFERENCES %I.insurer_referent(id)
        )$ddl$, p_schema, p_schema, p_schema);

    -- ─── scoring_configuration / "configuracion_scoring" + friends ───────────
    -- Data-driven backing for classification-service's RiskScoringService. Per tenant
    -- so each insurer calibrates its own weights and bands without a redeploy. Una sola
    -- fila por aseguradora: todos los ramos comparten el mismo scoring (decisión explícita,
    -- no por ramo — a diferencia de Fast Track y de la agenda documental).
    EXECUTE format($ddl$
        CREATE TABLE %I.scoring_configuration (
            id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name        VARCHAR(100) NOT NULL,
            active      BOOLEAN      NOT NULL DEFAULT TRUE,
            -- Si el Fast Track igual corre el análisis pesado (OCR + fraude de imágenes) para que su
            -- score salga completo. Default false: el Fast Track queda rápido, score parcial. No
            -- vetea el Fast Track — el score es señal paralela; solo decide cuánto análisis corre.
            full_analysis_on_fast_track BOOLEAN NOT NULL DEFAULT FALSE,
            valid_from  TIMESTAMPTZ  NOT NULL
        )$ddl$, p_schema);

    -- factor_code matches RiskFactorIds by string, not by FK — `factor` is an enum in
    -- the DER, not a table.
    EXECUTE format($ddl$
        CREATE TABLE %I.factor_weight (
            id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            factor_code              VARCHAR(80)  NOT NULL,
            weight                   NUMERIC(5,4) NOT NULL,
            scoring_configuration_id BIGINT       NOT NULL REFERENCES %I.scoring_configuration(id)
        )$ddl$, p_schema, p_schema);

    EXECUTE format($ddl$
        CREATE TABLE %I.score_band (
            id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            band                     VARCHAR(20)  NOT NULL,
            min_score_inclusive      NUMERIC(4,3) NOT NULL,
            active                   BOOLEAN      NOT NULL DEFAULT TRUE,
            scoring_configuration_id BIGINT       NOT NULL REFERENCES %I.scoring_configuration(id)
        )$ddl$, p_schema, p_schema);

    EXECUTE format($ddl$
        CREATE TABLE %I.scoring_configuration_history (
            id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            snapshot_config          JSONB        NOT NULL,
            valid_from               TIMESTAMPTZ  NOT NULL,
            valid_to                 TIMESTAMPTZ,
            changed_at               TIMESTAMPTZ  NOT NULL,
            reason                   VARCHAR(255),
            changed_by               BIGINT       REFERENCES %I.insurer_referent(id),
            scoring_configuration_id BIGINT       NOT NULL REFERENCES %I.scoring_configuration(id)
        )$ddl$, p_schema, p_schema, p_schema);

    -- ─── document_requirement / "requisito_documental" ───────────────────────
    -- The AgendaDocumental: which documents are required for a given branch + claim
    -- cause, optionally tightened for a risk band. This is the contract that decides
    -- whether a case is complete.
    EXECUTE format($ddl$
        CREATE TABLE %I.document_requirement (
            id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            document_type       VARCHAR(50)  NOT NULL,
            mandatory           BOOLEAN      NOT NULL DEFAULT TRUE,
            risk_band           VARCHAR(20),  -- banda_riesgo: NULL = applies to every band
            branch_id           BIGINT       NOT NULL REFERENCES arbiter_common.branch(id),
            claim_cause_id      BIGINT       NOT NULL REFERENCES arbiter_common.claim_cause(id)
        )$ddl$, p_schema);

    -- ─── cases / "expediente" ────────────────────────────────────────────────
    -- The case file. Far more normalized than the flat table it replaces: the branch,
    -- claim cause, policy and coverage are FKs now, not free text.
    -- classification_id closes a cycle (cases → case_classification → llm_analysis →
    -- cases), so its FK is added by ALTER TABLE once every table exists.
    -- No insurer_id: the DER draws aseguradora → expediente, and the schema satisfies
    -- that relationship by construction.
    EXECUTE format($ddl$
        CREATE TABLE %I.cases (
            id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            occurred_at                 TIMESTAMPTZ   NOT NULL,  -- fecha_hora_ocurrencia_siniestro
            reported_at                 TIMESTAMPTZ   NOT NULL,  -- fecha_hora_denuncia_siniestro
            police_report_at            TIMESTAMPTZ,             -- fecha_hora_denuncia_policial
            updated_at                  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
            response_deadline           DATE          NOT NULL,  -- fecha_limite_respuesta
            description                 TEXT          NOT NULL,
            was_fast_track              BOOLEAN       NOT NULL DEFAULT FALSE,
            fraud_determined            BOOLEAN       NOT NULL DEFAULT FALSE,
            destination                 VARCHAR(40),             -- destino (enum in the DER)
            -- What the insured claims, as opposed to what the insurer has on file.
            -- claimed_amount feeds AmountRatioEvaluator (the heaviest scoring factor);
            -- declared_item fills the {{insuredItem}} slot in the classification prompt.
            -- Both compare against policy_snapshot to surface declared-vs-recorded gaps.
            claimed_amount              NUMERIC(38,2),           -- monto_reclamado
            declared_item               VARCHAR(255),            -- bien_declarado
            -- ─── Read model for the analyst's inbox ──────────────────────────────
            -- The ONLY two denormalized columns, and only because the inbox filters, sorts
            -- and pages by risk band. risk_analysis is append-only (one row per scoring run),
            -- so reading the band off it means "the latest row per case" — a DISTINCT ON or a
            -- correlated subquery under the paging, which is far harder to index than this.
            -- risk_analysis remains the auditable source; these two are the copy you can put
            -- a WHERE on. Everything else the analyst UI needs (the recommendation, its
            -- confidence, the score breakdown) is read by joining llm_analysis / risk_analysis
            -- one case at a time, where latest-per-case costs nothing.
            risk_score                  NUMERIC(4,3),
            risk_band                   VARCHAR(20),
            -- Not denormalization: classification-service's own scratch space. The assembled
            -- report has no table of its own — the per-image findings are normalized into
            -- image_analysis, but nothing rebuilds the report from them yet. Remove this once
            -- something does.
            forensic_report             JSONB,
            -- Retry counter for the classification poller. Belongs to the case, not to
            -- case_classification: the analyst's row only exists once they decide, which is
            -- after this counter has done its job (marking CLASSIFICATION_FAILED).
            classification_attempts     INTEGER       NOT NULL DEFAULT 0,
            -- The analyst's note adjusting the score WITHOUT overwriting it. Distinct from
            -- case_classification.analyst_justification: this is written while the case is
            -- still open, that one is part of the verdict.
            manual_adjustment_note      TEXT,
            -- Where the event happened
            event_address               VARCHAR(120)  NOT NULL,
            event_latitude              NUMERIC(9,6),
            event_longitude             NUMERIC(9,6),
            locality                    VARCHAR(120),
            province                    VARCHAR(40),
            -- Relationships
            current_status_id           BIGINT        NOT NULL REFERENCES arbiter_common.case_status(id),
            analyst_id                  BIGINT        REFERENCES %I.claims_analyst(id),
            insured_id                  BIGINT        NOT NULL REFERENCES %I.insured(id),
            claim_cause_id              BIGINT        NOT NULL REFERENCES arbiter_common.claim_cause(id),
            coverage_id                 BIGINT        NOT NULL REFERENCES %I.coverage(id),
            policy_id                   BIGINT        NOT NULL REFERENCES %I.policy(id),
            policy_snapshot_id          BIGINT        REFERENCES %I.policy_snapshot(id),
            -- Which scoring configuration produced this case's risk score. The DER
            -- draws the relationship without the column; it is a real FK.
            scoring_configuration_id    BIGINT        REFERENCES %I.scoring_configuration(id),
            classification_id           BIGINT
        )$ddl$, p_schema, p_schema, p_schema, p_schema, p_schema, p_schema, p_schema);

    EXECUTE format('CREATE INDEX idx_cases_status ON %I.cases (current_status_id)', p_schema);
    EXECUTE format('CREATE INDEX idx_cases_insured ON %I.cases (insured_id)', p_schema);
    -- The analyst's inbox filters by risk band.
    EXECUTE format('CREATE INDEX idx_cases_risk_band ON %I.cases (risk_band)', p_schema);
    -- ...and by owner: the inbox's default lens is "Míos", so this filter runs on every load.
    EXECUTE format('CREATE INDEX idx_cases_analyst ON %I.cases (analyst_id)', p_schema);

    -- ─── case_documents / "documento_expediente" ─────────────────────────────
    EXECUTE format($ddl$
        CREATE TABLE %I.case_documents (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            type            VARCHAR(255) NOT NULL,
            filename        VARCHAR(255) NOT NULL,
            content_type    VARCHAR(255) NOT NULL,   -- MIME
            content         BYTEA        NOT NULL,
            uploaded_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            case_id         BIGINT       NOT NULL REFERENCES %I.cases(id) ON DELETE CASCADE,

            CONSTRAINT case_documents_case_type_unique UNIQUE (case_id, type)
        )$ddl$, p_schema, p_schema);

    -- ─── image_analysis / "analisis_imagen" ──────────────────────────────────
    -- Forensic analysis of an uploaded image: the CLIP embedding, the most similar
    -- document found (self-reference), and any external web match.
    -- Scoped per tenant so reuse detection never compares across insurers.
    EXECUTE format($ddl$
        CREATE TABLE %I.image_analysis (
            id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            embedding               public.vector(512),   -- CLIP ViT-B-32
            -- Which model produced the embedding. Not in the DER, added deliberately:
            -- vectors from different models are not comparable, so without this a model
            -- change would silently invalidate every stored vector with no way to tell.
            model                   VARCHAR(80)  NOT NULL,
            similarity_score        NUMERIC(5,2),
            is_suspicious           BOOLEAN      NOT NULL DEFAULT FALSE,
            analyzed_at             TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            external_source         VARCHAR(150),
            external_reference      TEXT,
            match_type              VARCHAR(20),
            external_hash           VARCHAR(64),
            case_document_id        BIGINT NOT NULL REFERENCES %I.case_documents(id) ON DELETE CASCADE,
            similar_document_id     BIGINT REFERENCES %I.case_documents(id)
        )$ddl$, p_schema, p_schema, p_schema);

    -- IVFFlat index for cosine distance — needs ~100 rows to be effective. For small
    -- datasets the sequential scan is fine; the index kicks in at scale.
    EXECUTE format($ddl$
        CREATE INDEX idx_image_analysis_cosine ON %I.image_analysis
            USING ivfflat (embedding public.vector_cosine_ops) WITH (lists = 100)
        $ddl$, p_schema);

    -- ─── case_status_history / "historial_estado_expediente" ─────────────────
    -- Append-only audit trail of every transition. The states are the global catalog;
    -- these transitions are this tenant's data.
    EXECUTE format($ddl$
        CREATE TABLE %I.case_status_history (
            id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            reason              VARCHAR(255) NOT NULL,   -- razon
            observation         TEXT,
            changed_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            -- Who drove the transition, as a role: INSURED / ANALYST / SYSTEM. Distinct from
            -- changed_by, which is nullable precisely because SYSTEM moves have no user behind
            -- them (the classification poller, the retry sweep). The analyst's timeline shows
            -- this, so it cannot be derived from changed_by being NULL alone. Falta en el DER.
            actor               VARCHAR(20)  NOT NULL,
            changed_by          BIGINT       REFERENCES arbiter_common.users(id),
            initial_status_id   BIGINT       REFERENCES arbiter_common.case_status(id),
            final_status_id     BIGINT       NOT NULL REFERENCES arbiter_common.case_status(id),
            case_id             BIGINT       NOT NULL REFERENCES %I.cases(id) ON DELETE CASCADE
        )$ddl$, p_schema, p_schema);

    -- ─── risk_analysis / "analisis_riesgo_expediente" ────────────────────────
    EXECUTE format($ddl$
        CREATE TABLE %I.risk_analysis (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            risk_score      NUMERIC(4,3) NOT NULL,
            risk_band       VARCHAR(20)  NOT NULL,
            risk_breakdown  JSONB        NOT NULL,
            analyzed_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            case_id         BIGINT       NOT NULL REFERENCES %I.cases(id) ON DELETE CASCADE
        )$ddl$, p_schema, p_schema);

    -- ─── rule_result / "resultado_regla" ─────────────────────────────────────
    EXECUTE format($ddl$
        CREATE TABLE %I.rule_result (
            id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            rule_type           VARCHAR(20)   NOT NULL,
            result              VARCHAR(20)   NOT NULL,
            evaluated_value     VARCHAR(150),
            score_contribution  NUMERIC(5,4),   -- aporte_score
            evaluated_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
            rule_id             BIGINT        NOT NULL REFERENCES %I.insurer_rule(id),
            case_id             BIGINT        NOT NULL REFERENCES %I.cases(id) ON DELETE CASCADE
        )$ddl$, p_schema, p_schema, p_schema);

    -- ─── llm_analysis / "analisis_llm" + llm_reason / "razon_llm" ────────────
    -- The model's non-binding recommendation, with its reasons as rows rather than a
    -- serialized blob. Immutable: required by Disposición SSN 2/2023.
    EXECUTE format($ddl$
        CREATE TABLE %I.llm_analysis (
            id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            recommendation      VARCHAR(50)  NOT NULL,
            model               VARCHAR(100) NOT NULL,
            prompt_version      VARCHAR(50)  NOT NULL,
            confidence          NUMERIC(5,3),
            latency_ms          INTEGER,
            analyzed_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            case_id             BIGINT       NOT NULL REFERENCES %I.cases(id) ON DELETE CASCADE,

            -- FAST_TRACK is decided by FastTrackValidator, never by the model
            -- (decision #6) — the DB refuses to record it as an LLM recommendation.
            CONSTRAINT llm_analysis_recommendation_check CHECK (
                recommendation IN (
                    'FALTA_DOCUMENTACION',
                    'LLM_RECOMIENDA_APROBAR',
                    'LLM_NO_RECOMIENDA_APROBAR',
                    'LLM_SOLICITA_REVISION_MANUAL'
                )
            )
        )$ddl$, p_schema, p_schema);

    EXECUTE format($ddl$
        CREATE TABLE %I.llm_reason (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            reason          TEXT   NOT NULL,
            analysis_id     BIGINT NOT NULL REFERENCES %I.llm_analysis(id) ON DELETE CASCADE
        )$ddl$, p_schema, p_schema);

    -- ─── case_classification / "clasificacion_expediente" ────────────────────
    -- The analyst's decision on top of the model's recommendation. Human-in-the-loop
    -- is mandatory (decision #5): there is no path from llm_analysis to a resolved
    -- case that does not pass through here.
    EXECUTE format($ddl$
        CREATE TABLE %I.case_classification (
            id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            decision                VARCHAR(20)  NOT NULL,
            analyst_justification   TEXT,
            decided_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            classification_attempts INTEGER      NOT NULL DEFAULT 0,
            llm_analysis_id         BIGINT       REFERENCES %I.llm_analysis(id),
            analyst_id              BIGINT       NOT NULL REFERENCES %I.claims_analyst(id)
        )$ddl$, p_schema, p_schema, p_schema);

    -- Closes the cases → case_classification cycle.
    EXECUTE format($ddl$
        ALTER TABLE %I.cases
            ADD CONSTRAINT cases_classification_fkey
            FOREIGN KEY (classification_id) REFERENCES %I.case_classification(id)
        $ddl$, p_schema, p_schema);

    -- ─── notification / "notificacion" ───────────────────────────────────────
    -- Outbound messages to the insured (SendGrid, decision #9).
    EXECUTE format($ddl$
        CREATE TABLE %I.notification (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            type            VARCHAR(60)  NOT NULL,
            channel         VARCHAR(30)  NOT NULL,
            content         TEXT         NOT NULL,
            sent            BOOLEAN      NOT NULL DEFAULT FALSE,   -- enviada
            read            BOOLEAN      NOT NULL DEFAULT FALSE,   -- leida
            -- When the notice was raised. Separate from sent_at, which stays NULL if the mail never
            -- went out: the notification still exists and the panel has to date it.
            created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
            sent_at         TIMESTAMPTZ,
            read_at         TIMESTAMPTZ,
            recipient_id    BIGINT       NOT NULL REFERENCES arbiter_common.users(id),
            case_id         BIGINT       REFERENCES %I.cases(id) ON DELETE CASCADE
        )$ddl$, p_schema, p_schema);

    -- ─── metric / "metrica" ──────────────────────────────────────────────────
    -- Precomputed aggregations for the referente's dashboards (reports-service).
    EXECUTE format($ddl$
        CREATE TABLE %I.metric (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            metric_name     VARCHAR(100) NOT NULL,
            period_from     DATE         NOT NULL,
            period_to       DATE         NOT NULL,
            value           NUMERIC(15,4) NOT NULL,
            granularity     VARCHAR(20)  NOT NULL
        )$ddl$, p_schema);

    -- ─── Per-tenant seed ─────────────────────────────────────────────────────
    EXECUTE format($ddl$
        INSERT INTO %I.coverage (id, name, description, report_deadline_hours,
                                 max_events_per_year, covers_family_group, deductible,
                                 claim_exhausts_coverage, is_individual, waiting_period_days, branch_id) VALUES
            (1, 'Robo de celular', 'Cobertura por robo en vía pública', 72, 2, FALSE, 10.00, FALSE, TRUE, 30, 1),
            (2, 'Hurto', 'Cobertura por hurto sin violencia', 72, 1, FALSE, 20.00, TRUE, TRUE, 30, 1)
        $ddl$, p_schema);

    -- No rule engine evaluates these yet — example rows, same as the previous script.
    EXECUTE format($ddl$
        INSERT INTO %I.insurer_rule (id, active, valid_from, name,
                                     rule_type, effect, priority, blocks_fast_track, branch_id) VALUES
            (1, TRUE, '2026-01-01 00:00:00+00',
             'Monto reclamado dentro del 50%% de la suma asegurada', 'FAST_TRACK', 'APROBAR', 1, FALSE, 1),
            (2, TRUE, '2026-01-01 00:00:00+00',
             'Póliza al día con sus pagos', 'FAST_TRACK', 'APROBAR', 2, FALSE, 1)
        $ddl$, p_schema);

    -- Regla dura EVALUABLE por código (a diferencia de las de arriba, que son ejemplos sin motor).
    -- Caso 6 del handoff, "Hurto no cubierto": la cobertura de robo (id 1) excluye el hecho generador
    -- Hurto (claim_cause id 3). `configuration` JSONB = lista negra de claim_cause; classification la
    -- lee por /internal/evaluable y matchea por id. blocks_fast_track = TRUE: una exclusión dura hace
    -- irrelevante al Fast Track. La evalúa CoverageRuleEvaluator y deja fila en rule_result (D3/D4c).
    -- OJO (handoff §8): confirmar los ids de coverage/claim_cause contra Railway antes de fijarlos —
    -- Tecnología pasó de branch 3 a 2 en el último reseed.
    EXECUTE format($ddl$
        INSERT INTO %I.insurer_rule (id, active, valid_from, name, rule_type, effect, priority,
                                     blocks_fast_track, branch_id, coverage_id, configuration) VALUES
            (3, TRUE, '2026-01-01 00:00:00+00',
             'La cobertura de robo no cubre el hurto', 'COVERAGE_EXCLUSION', 'RECHAZAR', 1,
             TRUE, 1, 1, '{"excludedClaimCauseIds":[3]}')
        $ddl$, p_schema);

    -- TEMPORAL hard rules, coverage-scoped: one row per rule and per coverage. The row is the
    -- switch: without it, TemporalRuleEvaluator doesn't evaluate that rule (so a new insurer
    -- doesn't inherit rules nobody configured). The threshold does NOT live here except for
    -- POLICE_DEADLINE: the waiting period, report deadline, and events cap are terms of the
    -- contract and are coverage columns, which the referente edits from the Coverages tab. The
    -- police-report deadline has no column of its own — coverage.report_deadline_hours is already
    -- the deadline for the report TO THE INSURER, a different deadline — so its threshold goes in
    -- the JSONB. Used to be the fixed property arbiter.rules.police-report-deadline-hours = 72,
    -- the same for every company, against decision #12. Each evaluation leaves a rule_result row
    -- pointing at these ids (SSN 2/2023). The ids mirror MockRulesAdapter's baseline.
    --
    -- Coverage window (POLICY_IN_FORCE) is NOT in this block: it's insurer-scoped, see the
    -- INSERT right below this one — a policy is or isn't in force regardless of which coverage
    -- the claim lands under (BBVA's real API confirms this: it rejects a claim against the whole
    -- "Operación Siniestrada", no coverage in the request payload).
    EXECUTE format($ddl$
        INSERT INTO %I.insurer_rule (id, active, valid_from, name, rule_type, effect, priority,
                                     blocks_fast_track, branch_id, coverage_id, configuration) VALUES
            (5,  TRUE, '2026-01-01 00:00:00+00', 'Carencia de la cobertura (cobertura 1)',
             'WAITING_PERIOD',  'DERIVAR', 2, TRUE, 1, 1, '{}'),
            (6,  TRUE, '2026-01-01 00:00:00+00', 'Plazo de denuncia a la aseguradora (cobertura 1)',
             'REPORT_DEADLINE', 'DERIVAR', 3, TRUE, 1, 1, '{}'),
            -- Apagada por defecto (17/08): Mar consultó y el plazo de 72hs no es tan rígido como
            -- para bloquear/derivar solo — importa más la fecha que tiene la denuncia policial en
            -- sí (chequeo de coherencia, que sigue estando) que cuándo se sube a Arbiter. Sigue
            -- existiendo como fila para que la aseguradora que la quiera estricta la prenda desde
            -- el panel, sin deploy — mismo criterio que POLICY_STANDING.
            (7,  FALSE, '2026-01-01 00:00:00+00', 'Plazo de la denuncia policial (cobertura 1)',
             'POLICE_DEADLINE', 'DERIVAR', 4, TRUE, 1, 1, '{"deadlineHours":72}'),
            (8,  TRUE, '2026-01-01 00:00:00+00', 'Tope de eventos por año (cobertura 1)',
             'MAX_EVENTS_YEAR', 'DERIVAR', 5, TRUE, 1, 1, '{}'),
            (10, TRUE, '2026-01-01 00:00:00+00', 'Carencia de la cobertura (cobertura 2)',
             'WAITING_PERIOD',  'DERIVAR', 2, TRUE, 1, 2, '{}'),
            (11, TRUE, '2026-01-01 00:00:00+00', 'Plazo de denuncia a la aseguradora (cobertura 2)',
             'REPORT_DEADLINE', 'DERIVAR', 3, TRUE, 1, 2, '{}'),
            (12, FALSE, '2026-01-01 00:00:00+00', 'Plazo de la denuncia policial (cobertura 2)',
             'POLICE_DEADLINE', 'DERIVAR', 4, TRUE, 1, 2, '{"deadlineHours":72}'),
            (13, TRUE, '2026-01-01 00:00:00+00', 'Tope de eventos por año (cobertura 2)',
             'MAX_EVENTS_YEAR', 'DERIVAR', 5, TRUE, 1, 2, '{}')
        $ddl$, p_schema);

    -- TEMPORAL hard rule, insurer-scoped: coverage window, one row for the whole insurer
    -- (branch_id and coverage_id both null). POLICY_STANDING (arrears) is NOT seeded here: unlike
    -- this one, it starts inactive on purpose (see RuleType#POLICY_STANDING's javadoc) — an
    -- insurer that wants it has to turn it on from the Hard Stop tab.
    EXECUTE format($ddl$
        INSERT INTO %I.insurer_rule (id, active, valid_from, name, rule_type, effect, priority,
                                     blocks_fast_track, branch_id, coverage_id, configuration) VALUES
            (14, TRUE, '2026-01-01 00:00:00+00', 'Vigencia de la póliza',
             'POLICY_IN_FORCE', 'DERIVAR', 1, TRUE, NULL, NULL, '{}')
        $ddl$, p_schema);

    -- AgendaDocumental sembrada con los códigos CANÓNICOS de tipo de documento — los mismos que usa
    -- el alta de denuncia y classification (police_report / purchase_proof / imei_deregistration /
    -- last_connection). Antes se sembraba con códigos ad-hoc (DNI/DENUNCIA_POLICIAL/…) que el front
    -- no reconocía, y por eso la solapa Documentación no mostraba los defaults. Se siembra para
    -- Celulares · "Robo en vía pública" (claim_cause 2) y Tecnología Portátil · "Daño accidental"
    -- (claim_cause 6). El referente la amplía/recorta desde la pantalla de reglas (solapa
    -- Documentación), que persiste sobre esta misma tabla.
    EXECUTE format($ddl$
        INSERT INTO %I.document_requirement (id, document_type, mandatory, risk_band, branch_id, claim_cause_id) VALUES
            (1, 'police_report',       TRUE, NULL, 1, 2),
            (2, 'purchase_proof',      TRUE, NULL, 1, 2),
            (3, 'imei_deregistration', TRUE, NULL, 1, 2),
            (4, 'last_connection',     TRUE, NULL, 1, 2),
            (5, 'police_report',       TRUE, NULL, 2, 6),
            (6, 'purchase_proof',      TRUE, NULL, 2, 6),
            (7, 'imei_deregistration', TRUE, NULL, 2, 6),
            (8, 'last_connection',     TRUE, NULL, 2, 6)
        $ddl$, p_schema);

    -- Same values as classification-service's MockRulesAdapter.DEFAULT_SCORING_CONFIG
    -- (the "faithful H0012 reference config"). Every tenant starts from this baseline
    -- and diverges from there.
    EXECUTE format($ddl$
        INSERT INTO %I.scoring_configuration (id, name, active, full_analysis_on_fast_track, valid_from) VALUES
            (1, 'Default (H0012 reference config)', TRUE, FALSE, '2026-01-01 00:00:00+00')
        $ddl$, p_schema);

    EXECUTE format($ddl$
        INSERT INTO %I.factor_weight (id, factor_code, weight, scoring_configuration_id) VALUES
            (1, 'amount_ratio', 0.45, 1),
            (2, 'claim_frequency', 0.35, 1),
            (3, 'policy_standing', 0.20, 1),
            (4, 'image_reuse', 0.50, 1),
            (5, 'image_web_match', 0.40, 1)
        $ddl$, p_schema);

    EXECUTE format($ddl$
        INSERT INTO %I.score_band (id, band, min_score_inclusive, active, scoring_configuration_id) VALUES
            (1, 'LOW', 0.00, TRUE, 1),
            (2, 'MEDIUM', 0.30, TRUE, 1),
            (3, 'HIGH', 0.60, TRUE, 1),
            (4, 'CRITICAL', 0.80, TRUE, 1)
        $ddl$, p_schema);

    -- Realign every identity sequence with the explicit ids seeded above.
    EXECUTE format($ddl$SELECT setval(pg_get_serial_sequence('%I.coverage','id'),
        (SELECT MAX(id) FROM %I.coverage))$ddl$, p_schema, p_schema);
    EXECUTE format($ddl$SELECT setval(pg_get_serial_sequence('%I.insurer_rule','id'),
        (SELECT MAX(id) FROM %I.insurer_rule))$ddl$, p_schema, p_schema);
    EXECUTE format($ddl$SELECT setval(pg_get_serial_sequence('%I.document_requirement','id'),
        (SELECT MAX(id) FROM %I.document_requirement))$ddl$, p_schema, p_schema);
    EXECUTE format($ddl$SELECT setval(pg_get_serial_sequence('%I.scoring_configuration','id'),
        (SELECT MAX(id) FROM %I.scoring_configuration))$ddl$, p_schema, p_schema);
    EXECUTE format($ddl$SELECT setval(pg_get_serial_sequence('%I.factor_weight','id'),
        (SELECT MAX(id) FROM %I.factor_weight))$ddl$, p_schema, p_schema);
    EXECUTE format($ddl$SELECT setval(pg_get_serial_sequence('%I.score_band','id'),
        (SELECT MAX(id) FROM %I.score_band))$ddl$, p_schema, p_schema);
END;
$fn$ LANGUAGE plpgsql;

-- =============================================================================
-- "BD ASEGURADORA" SCHEMA TEMPLATE — the external insurer system, simulated
--
-- Not Arbiter's data: this stands in for the insurer's own database, integrated by
-- shared database per the architecture doc. One schema per insurer, so the
-- aseguradora_id discriminator the single-schema version carried is gone.
-- Names stay in Spanish here — it simulates a third-party system with its own
-- vocabulary, and Arbiter only reads it through InsurerDatabaseAdapter.
-- =============================================================================

CREATE OR REPLACE FUNCTION arbiter_common.create_insurer_db_schema(
    p_schema       TEXT,
    p_legal_name   TEXT,
    p_tax_id       TEXT,
    p_ssn_registry TEXT
) RETURNS VOID AS $fn$
BEGIN
    EXECUTE format('CREATE SCHEMA %I', p_schema);

    EXECUTE format($ddl$
        CREATE TABLE %I.compania (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nombre          VARCHAR(255) NOT NULL,
            cuit            VARCHAR(20)  NOT NULL UNIQUE,
            ssn_registro    VARCHAR(20),
            created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW()
        )$ddl$, p_schema);

    EXECUTE format($ddl$
        CREATE TABLE %I.asegurado (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            documento       VARCHAR(20)  NOT NULL UNIQUE,
            cuil            VARCHAR(20),
            nombre          VARCHAR(120) NOT NULL,
            apellido        VARCHAR(120) NOT NULL,
            email           VARCHAR(255),
            telefono        VARCHAR(50),
            created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW()
        )$ddl$, p_schema);

    EXECUTE format($ddl$
        CREATE TABLE %I.poliza (
            id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            numero                VARCHAR(80)   NOT NULL UNIQUE,
            nro_certificado       VARCHAR(80),
            titular_id            BIGINT        NOT NULL REFERENCES %I.asegurado(id),
            rama                  VARCHAR(80)   NOT NULL,
            producto              VARCHAR(160)  NOT NULL,
            bien_asegurado        VARCHAR(255),
            -- Identificador del equipo cuando el ramo lo tiene (Celulares). NULL en los ramos donde
            -- no aplica. Es el operando que le faltaba al cruce "el IMEI del documento no coincide
            -- con el del bien" (D4b): sin esto, extraer el IMEI de la factura no servía de nada.
            imei                  VARCHAR(20),
            moneda                VARCHAR(3)    NOT NULL DEFAULT 'ARS',
            -- TIMESTAMP (sin timezone), no DATE: la póliza modelo (BBVA) fija la vigencia con hora
            -- exacta ("desde las 12:00 hs del..."), y con solo la fecha un siniestro dos horas
            -- antes de que arranque la vigencia, mismo día, pasaba el chequeo de
            -- PolicyEligibilityValidator / TemporalRuleEvaluator (D13) como si estuviera cubierto.
            -- Sin timezone a propósito: InsurerDatabaseAdapter la lee con JDBC crudo vía
            -- rs.getObject(col, LocalDateTime.class), que el driver de Postgres rechaza para
            -- TIMESTAMPTZ (pide OffsetDateTime/Instant) — y en el resto del dominio la fecha del
            -- hecho tampoco lleva timezone, es LocalDateTime a secas.
            vigencia_desde        TIMESTAMP     NOT NULL,
            vigencia_hasta        TIMESTAMP     NOT NULL,
            estado_contrato       VARCHAR(20)   NOT NULL,
            estado_pago           VARCHAR(20)   NOT NULL,
            cuotas_pagas          INTEGER       NOT NULL DEFAULT 0,
            cuotas_impagas        INTEGER       NOT NULL DEFAULT 0,
            saldo_deuda           NUMERIC(38,2) NOT NULL DEFAULT 0,
            forma_pago            VARCHAR(60),
            max_eventos_anuales   INTEGER,
            segundo_evento_pct    NUMERIC(5,2),
            cubre_grupo_familiar  BOOLEAN       NOT NULL DEFAULT FALSE,
            datos_proveedor       JSONB,
            created_at            TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

            CONSTRAINT poliza_rama_check CHECK (rama IN ('Celulares', 'Tecnología Portátil')),
            CONSTRAINT poliza_estado_pago_check CHECK (estado_pago IN ('AL_DIA','SUSPENDIDA','RESUELTA'))
        )$ddl$, p_schema, p_schema);

    EXECUTE format('CREATE INDEX idx_poliza_numero ON %I.poliza (numero)', p_schema);

    EXECUTE format($ddl$
        CREATE TABLE %I.cobertura (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            poliza_id       BIGINT        NOT NULL REFERENCES %I.poliza(id) ON DELETE CASCADE,
            orden           INTEGER       NOT NULL DEFAULT 1,
            nombre          VARCHAR(160)  NOT NULL,
            suma_asegurada  NUMERIC(38,2) NOT NULL,
            franquicia_pct  NUMERIC(5,2),
            created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

            CONSTRAINT cobertura_poliza_orden_unique UNIQUE (poliza_id, orden),
            CONSTRAINT cobertura_nombre_check
                CHECK (nombre IN ('Robo de celular', 'Hurto', 'Daño accidental'))
        )$ddl$, p_schema, p_schema);

    EXECUTE format('CREATE INDEX idx_cobertura_poliza ON %I.cobertura (poliza_id)', p_schema);

    -- Previous resolved claims; feeds the claim_frequency risk factor.
    EXECUTE format($ddl$
        CREATE TABLE %I.siniestro_historico (
            id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            poliza_id           BIGINT       NOT NULL REFERENCES %I.poliza(id),
            asegurado_id        BIGINT       NOT NULL REFERENCES %I.asegurado(id),
            fecha_ocurrencia    DATE         NOT NULL,
            causa               VARCHAR(120) NOT NULL,
            estado_resolucion   VARCHAR(40)  NOT NULL,
            monto_indemnizado   NUMERIC(38,2),
            created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW()
        )$ddl$, p_schema, p_schema, p_schema);

    EXECUTE format('CREATE INDEX idx_sinhist_asegurado ON %I.siniestro_historico (asegurado_id)',
                   p_schema);

    EXECUTE format($ddl$
        INSERT INTO %I.compania (id, nombre, cuit, ssn_registro) VALUES (1, %L, %L, %L)
        $ddl$, p_schema, p_legal_name, p_tax_id, p_ssn_registry);
END;
$fn$ LANGUAGE plpgsql;

-- =============================================================================
-- TENANT PROVISIONING
-- =============================================================================

SELECT arbiter_common.create_tenant_schema('arbiter_bbva');
SELECT arbiter_common.create_tenant_schema('arbiter_provincia');

-- CUITs and SSN registration numbers carried over from db/datos-aseguradoras.sql.
SELECT arbiter_common.create_insurer_db_schema(
    'aseguradora_bbva', 'BBVA Seguros Argentina S.A.', '30-50006423-0', '0396');
SELECT arbiter_common.create_insurer_db_schema(
    'aseguradora_provincia', 'Provincia Seguros S.A.', '30-57411408-6', '0326');

-- ─── Role profiles, per tenant ───────────────────────────────────────────────
-- The DER moves the person's name off `usuario` and onto the role profile, which is
-- tenant-scoped — so these cannot live in the shared seed above.
INSERT INTO arbiter_bbva.insured (id, name, surname, dni, email, phone, pep, user_id) VALUES
    (1, 'Martina', 'Soteras', '42.987.654', 'asegurado.arbiter@gmail.com', '+54 9 11 5555-0001', FALSE, 1);

SELECT setval(pg_get_serial_sequence('arbiter_bbva.insured', 'id'),
              (SELECT MAX(id) FROM arbiter_bbva.insured));

INSERT INTO arbiter_bbva.claims_analyst (id, name, surname, email, user_id) VALUES
    (1, 'Lucas', 'Gómez', 'analista.arbiter@gmail.com', 2),
    (2, 'Federico', 'Alvarez', 'federico21433@hotmail.com', 8);

SELECT setval(pg_get_serial_sequence('arbiter_bbva.claims_analyst', 'id'),
              (SELECT MAX(id) FROM arbiter_bbva.claims_analyst));

INSERT INTO arbiter_bbva.insurer_referent (id, name, surname, user_id) VALUES
    (1, 'Sofía', 'Martínez', 3);

SELECT setval(pg_get_serial_sequence('arbiter_bbva.insurer_referent', 'id'),
              (SELECT MAX(id) FROM arbiter_bbva.insurer_referent));

INSERT INTO arbiter_provincia.claims_analyst (id, name, surname, email, user_id) VALUES
    (1, 'Diego', 'Fernández', 'analista.provincia.arbiter@gmail.com', 4),
    (2, 'Federico', 'Moccia', 'mocciafederico@hotmail.com', 7);

SELECT setval(pg_get_serial_sequence('arbiter_provincia.claims_analyst', 'id'),
              (SELECT MAX(id) FROM arbiter_provincia.claims_analyst));

INSERT INTO arbiter_provincia.insurer_referent (id, name, surname, user_id) VALUES
    (1, 'Paula', 'Ríos', 6);

SELECT setval(pg_get_serial_sequence('arbiter_provincia.insurer_referent', 'id'),
              (SELECT MAX(id) FROM arbiter_provincia.insurer_referent));

COMMIT;

-- =============================================================================
-- Onboarding a third insurer needs no hand-written DDL:
--   INSERT INTO arbiter_common.insurer (legal_name, name, tax_id, active, schema_name)
--        VALUES ('La Segunda Seguros S.A.', 'La Segunda', '30-50001328-8', TRUE, 'arbiter_lasegunda');
--   SELECT arbiter_common.create_tenant_schema('arbiter_lasegunda');
--   SELECT arbiter_common.create_insurer_db_schema(
--       'aseguradora_lasegunda', 'La Segunda Seguros S.A.', '30-50001328-8', '0331');
--
-- Still to come, kept out of this file so it stays DDL + catalogs:
--   · policies / insured / claim history per aseguradora_* schema
--   · demo cases (db/seed-demo-bbva.sql)
-- =============================================================================
