-- =============================================================================
-- Arbiter — DB initialization script (multi-tenant by schema)
--
-- 48 tables: 10 shared + 33 per tenant + 5 per simulated insurer DB. Risk factors are
-- not a table: their codes live in classification-service's RiskFactorIds.
--
-- One schema per insurer, with NO tenant discriminator column anywhere in a tenant
-- schema: the schema is the tenant, and `insurer` exists only in the shared schema, as
-- the registry that says which tenants exist and which schema to route to.
--
-- Schema layout:
--   arbiter_common         Tenant registry, identity, RBAC, global catalogs.
--   arbiter_bbva           Tenant schema — BBVA Seguros.
--   arbiter_provincia      Tenant schema — Provincia Seguros.
--   aseguradora_bbva       Simulated insurer DB (external system) for BBVA.
--   aseguradora_provincia  Same, for Provincia.
--
-- Services must set the connection's search_path to "<tenant>, arbiter_common, public"
-- so unqualified names resolve tenant-first. With that, ddl-auto MUST be `validate`:
-- `update` recreates the arbiter_common tables inside each tenant schema.
--
-- Usage (Railway):  psql "$DATABASE_URL" -f db/init-multitenant.sql
-- Usage (local):    docker exec -i arbiter-postgres-1 psql -U arbiter -d arbiter < db/init-multitenant.sql
-- =============================================================================

-- Creates only, no DROP: targets an empty database and fails loudly on a populated one.
--
-- Extensions live in `public` so every tenant schema reaches them through the
-- search_path fallback (the `vector` type, and unaccent called unqualified by
-- CaseSpecifications.freeText).
CREATE EXTENSION IF NOT EXISTS vector SCHEMA public;

CREATE EXTENSION IF NOT EXISTS unaccent SCHEMA public;

BEGIN;

CREATE SCHEMA arbiter_common;

-- =============================================================================
-- ARBITER_COMMON — 10 tables
-- Tenant registry, centralized identity, RBAC and the platform-wide catalogs that
-- are identical for every insurer.
-- =============================================================================

-- ─── insurer ─────────────────────────────────────────────────────────────────
-- Shared because the tenant resolver reads it before it knows the tenant.
-- schema_name is the routing key.
CREATE TABLE arbiter_common.insurer (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legal_name      VARCHAR(200) NOT NULL,
    name            VARCHAR(150) NOT NULL,
    tax_id          VARCHAR(13)  NOT NULL UNIQUE,
    active          BOOLEAN      NOT NULL DEFAULT TRUE,
    schema_name     VARCHAR(60)  NOT NULL UNIQUE
);

-- ─── users ───────────────────────────────────────────────────────────────────
-- Identity backed by Auth0. Shared because login happens before the tenant is known;
-- names live on the per-tenant role profiles (insured, claims_analyst, insurer_referent).
CREATE TABLE arbiter_common.users (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth0_sub               VARCHAR(255) NOT NULL,
    email                   VARCHAR(255) NOT NULL,
    active                  BOOLEAN      NOT NULL DEFAULT TRUE,
    failed_attempts         INTEGER      NOT NULL DEFAULT 0,
    locked_until            TIMESTAMPTZ,
    invite_token            VARCHAR(128) UNIQUE,
    invite_expires_at       TIMESTAMPTZ,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    last_access_at          TIMESTAMPTZ,
    activated               BOOLEAN      NOT NULL DEFAULT FALSE
);

-- Bulk provisioning de-duplicates insureds by email, case-insensitively.
CREATE UNIQUE INDEX users_email_lower_uq ON arbiter_common.users (lower(email));

-- ─── role, permission, role_permission, user_role / RBAC ─────────────────────
-- Platform-wide: the same roles and permissions apply across every insurer.
CREATE TABLE arbiter_common.role (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code    VARCHAR(80)  NOT NULL UNIQUE,
    name    VARCHAR(255) NOT NULL
);

CREATE TABLE arbiter_common.permission (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE arbiter_common.role_permission (
    role_id       BIGINT NOT NULL REFERENCES arbiter_common.role(id),
    permission_id BIGINT NOT NULL REFERENCES arbiter_common.permission(id),
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE arbiter_common.user_role (
    user_id BIGINT NOT NULL REFERENCES arbiter_common.users(id),
    role_id BIGINT NOT NULL REFERENCES arbiter_common.role(id),
    PRIMARY KEY (user_id, role_id)
);

-- ─── user_insurer ────────────────────────────────────────────────────────────
-- Membership and routing: joined with insurer.schema_name it tells the resolver which
-- schema serves a request.
CREATE TABLE arbiter_common.user_insurer (
    user_id     BIGINT NOT NULL REFERENCES arbiter_common.users(id),
    insurer_id  BIGINT NOT NULL REFERENCES arbiter_common.insurer(id),
    PRIMARY KEY (user_id, insurer_id)
);

-- ─── branch ──────────────────────────────────────────────────────────────────
-- Global catalog; an insurer restricts which ones it sells through its own
-- document_requirement rows.
CREATE TABLE arbiter_common.branch (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(100) NOT NULL UNIQUE
);

-- ─── claim_cause ─────────────────────────────────────────────────────────────
-- Global catalog; which causes an insurer accepts, and under which coverage, is
-- per tenant.
CREATE TABLE arbiter_common.claim_cause (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- The same cause repeats across branches: the natural key is (branch_id, name).
    name        VARCHAR(100) NOT NULL,
    branch_id   BIGINT       NOT NULL REFERENCES arbiter_common.branch(id),

    CONSTRAINT claim_cause_branch_name_unique UNIQUE (branch_id, name)
);

-- ─── case_status ─────────────────────────────────────────────────────────────
-- Lifecycle state definitions; each case's transitions are per tenant.
-- insured_status is the simplified label shown to the insured, who must not see the
-- internal analyst-facing state.
CREATE TABLE arbiter_common.case_status (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(60)  NOT NULL UNIQUE,   -- matches common-lib's CaseStatus
    description     VARCHAR(255) NOT NULL,
    insured_status  VARCHAR(60)  NOT NULL,
    is_final        BOOLEAN      NOT NULL DEFAULT FALSE
);

-- =============================================================================
-- ARBITER_COMMON — seed data
-- =============================================================================

INSERT INTO arbiter_common.insurer (id, legal_name, name, tax_id, active, schema_name) VALUES
    (1, 'BBVA Seguros Argentina S.A.', 'BBVA Seguros', '30-50006423-0', TRUE, 'arbiter_bbva'),
    (2, 'Provincia Seguros S.A.',      'Provincia Seguros', '30-57411408-6', TRUE, 'arbiter_provincia');

SELECT setval(pg_get_serial_sequence('arbiter_common.insurer', 'id'),
              (SELECT MAX(id) FROM arbiter_common.insurer));

-- 'auth0|seed-*' subs are placeholders. Passwords live only in Auth0.
INSERT INTO arbiter_common.users (id, auth0_sub, email, active, activated) VALUES
    (1, 'auth0|seed-asegurado',           'asegurado.arbiter@gmail.com',           TRUE, TRUE),
    (2, 'auth0|seed-analista',            'analista.arbiter@gmail.com',            TRUE, TRUE),
    (3, 'auth0|seed-referente',           'referente.arbiter@gmail.com',           TRUE, TRUE),
    -- Users on the second insurer exist to demonstrate tenant isolation.
    (4, 'auth0|seed-analista-provincia',  'analista.provincia.arbiter@gmail.com',  TRUE, TRUE),
    (5, 'auth0|6a71248c6b9165b91b479173',  'asegurado2.arbiter@gmail.com',          TRUE, TRUE),
    (6, 'auth0|seed-referente-provincia', 'referente.provincia.arbiter@gmail.com',  TRUE, TRUE),
    -- Real Auth0 accounts: login reads the local row first, so a re-init without them
    -- locks them out.
    (7, 'auth0|seed-analista-provincia-2', 'mocciafederico@hotmail.com',            TRUE, TRUE),
    (8, 'auth0|seed-analista-bbva-2',      'federico21433@hotmail.com',             TRUE, TRUE),
    -- Insured for the unbranded test documents; needs his own policies (seed-demo.sql) or
    -- his claims fail the DNI/policy holder check.
    -- TODO: placeholder sub; replace it with the real one once the Auth0 account exists.
    -- Until then this user can't log in.
    (9, 'auth0|seed-asegurado-roman',      'asandoval01228@gmail.com',               TRUE, TRUE);

SELECT setval(pg_get_serial_sequence('arbiter_common.users', 'id'),
              (SELECT MAX(id) FROM arbiter_common.users));

-- code matches the UserRole enum 1:1.
INSERT INTO arbiter_common.role (id, code, name) VALUES
    (1, 'ASEGURADO', 'Asegurado'),
    (2, 'ANALISTA_SINIESTROS', 'Analista de siniestros'),
    (3, 'REFERENTE_ASEGURADORA', 'Referente de aseguradora');

SELECT setval(pg_get_serial_sequence('arbiter_common.role', 'id'),
              (SELECT MAX(id) FROM arbiter_common.role));

INSERT INTO arbiter_common.user_role (user_id, role_id) VALUES
    (1, 1), (2, 2), (3, 3), (4, 2), (6, 3), (7, 2), (8, 2), (9, 1);

-- permission / role_permission stay empty on purpose: no permission catalog is defined yet.

INSERT INTO arbiter_common.user_insurer (user_id, insurer_id) VALUES
    (1, 1), (2, 1), (3, 1), (4, 2), (6, 2), (7, 2), (8, 1), (9, 1), (9, 2);

INSERT INTO arbiter_common.branch (id, name) VALUES
    (1, 'Celulares'),
    (2, 'Tecnología Portátil');

SELECT setval(pg_get_serial_sequence('arbiter_common.branch', 'id'),
              (SELECT MAX(id) FROM arbiter_common.branch));

-- Causes repeat across branches on purpose: required documents and coverage differ
-- per branch, so each branch gets its own row.
INSERT INTO arbiter_common.claim_cause (id, name, branch_id) VALUES
    (1, 'Rotura accidental',   1),   -- Celulares
    (2, 'Robo en vía pública', 1),
    (3, 'Hurto',               1),
    (4, 'Caída',               1),
    (6, 'Daño accidental',     2),   -- Tecnología Portátil
    (7, 'Robo en vía pública', 2),
    (8, 'Hurto',               2);

SELECT setval(pg_get_serial_sequence('arbiter_common.claim_cause', 'id'),
              (SELECT MAX(id) FROM arbiter_common.claim_cause));

-- 1:1 with common-lib's CaseStatus.
INSERT INTO arbiter_common.case_status (id, name, description, insured_status, is_final) VALUES
    (1, 'PENDING_CLASSIFICATION', 'Denuncia registrada, clasificación en curso',      'En análisis',           FALSE),
    (2, 'PENDING_ANALYST_REVIEW', 'Clasificación lista, esperando al analista',       'En análisis',           FALSE),
    (3, 'AWAITING_DOCUMENTATION', 'Faltan documentos obligatorios de la agenda',      'Falta documentación',   FALSE),
    (4, 'CLASSIFICATION_FAILED',  'La clasificación falló tras agotar reintentos',    'En análisis',           FALSE),
    (5, 'APPROVED',               'El analista aprobó el siniestro',                  'Aprobado',              TRUE),
    (6, 'REJECTED',               'El analista rechazó el siniestro',                 'Rechazado',             TRUE),
    -- The expert will contact the insured anyway, so the derivation is shown; the reason never is.
    (7, 'PENDING_EXPERT_REPORT',  'Derivado a peritaje, esperando el informe',        'En verificación',       FALSE),
    -- Closed after 18 months without activity from the insured; unlike a rejection, shown to them.
    (8, 'LAPSED',                 'Caducado por 18 meses de inacción del asegurado',  'Caducado',              TRUE),
    -- Shown to the insured: a repair reveals no suspicion and explains why the case is idle.
    (9, 'PENDING_REPAIR',         'Derivado a servicio técnico, esperando su respuesta', 'En reparación',      FALSE);

SELECT setval(pg_get_serial_sequence('arbiter_common.case_status', 'id'),
              (SELECT MAX(id) FROM arbiter_common.case_status));

-- =============================================================================
-- TENANT SCHEMA TEMPLATE — 33 tables, created once per insurer
-- =============================================================================

-- Takes only the schema name: the schema itself identifies the insurer.
CREATE OR REPLACE FUNCTION arbiter_common.create_tenant_schema(
    p_schema TEXT
) RETURNS VOID AS $fn$
BEGIN
    EXECUTE format('CREATE SCHEMA %I', p_schema);

    -- ─── Role profiles: insured, claims_analyst, insurer_referent ────────────────
    -- The DER splits the person out of `usuario`: identity is shared, the profile
    -- belongs to the insurer the person works for or is insured by.

    -- insured / "asegurado"
    EXECUTE format($ddl$
        CREATE TABLE %I.insured (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name            VARCHAR(255) NOT NULL,
            surname         VARCHAR(255) NOT NULL,
            dni             VARCHAR(20)  NOT NULL UNIQUE,
            email           VARCHAR(255),
            phone           VARCHAR(30),
            case_count      INTEGER      NOT NULL DEFAULT 0,
            pep             BOOLEAN      NOT NULL DEFAULT FALSE,
            image_consent           BOOLEAN      NOT NULL DEFAULT FALSE,
            image_consent_version   VARCHAR(20),
            image_consent_at        TIMESTAMPTZ,
            onboarding_complete     BOOLEAN      NOT NULL DEFAULT FALSE,
            onboarding_completed_at TIMESTAMPTZ,
            user_id         BIGINT       NOT NULL REFERENCES arbiter_common.users(id)
        )$ddl$, p_schema);

    -- claims_analyst
    EXECUTE format($ddl$
        CREATE TABLE %I.claims_analyst (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name            VARCHAR(255) NOT NULL,
            surname         VARCHAR(255) NOT NULL,
            email           VARCHAR(255) NOT NULL,
            user_id         BIGINT       NOT NULL REFERENCES arbiter_common.users(id)
        )$ddl$, p_schema);

    -- insurer_referent
    EXECUTE format($ddl$
        CREATE TABLE %I.insurer_referent (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name            VARCHAR(255) NOT NULL,
            surname         VARCHAR(255) NOT NULL,
            user_id         BIGINT       NOT NULL REFERENCES arbiter_common.users(id)
        )$ddl$, p_schema);

    -- ─── coverage ────────────────────────────────────────────────────────────────
    -- Coverage definitions, administered by the referent and shared by every policy.
    EXECUTE format($ddl$
        CREATE TABLE %I.coverage (
            id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name                            VARCHAR(100)  NOT NULL UNIQUE,
            description                     TEXT,
            report_deadline_hours           BIGINT,
            max_events_per_year             INTEGER,
            covers_family_group             BOOLEAN       NOT NULL DEFAULT FALSE,
            deductible                      NUMERIC(15,2),           -- percentage points: 10.00 = 10%%
            claim_exhausts_coverage         BOOLEAN       NOT NULL DEFAULT FALSE,
            is_individual                   BOOLEAN       NOT NULL DEFAULT TRUE,
            waiting_period_days             INTEGER,
            branch_id                       BIGINT        NOT NULL REFERENCES arbiter_common.branch(id),
            clause                          VARCHAR(20),
            exclusions                      JSONB,
            -- ─── Settlement terms ────────────────────────────────────────────────────────
            -- Whether a claim settles as a total loss or a repair. Lives on the coverage because
            -- the insurer's catalog already splits losses from damage.
            settlement_formula              VARCHAR(20)   NOT NULL DEFAULT 'TOTAL_LOSS',
            -- TOTAL_LOSS only; a repair is capped by its quote. LESSER_OF_SUM_AND_REPLACEMENT is
            -- what clause 340 art. 7 requires for Tecnología Portátil.
            settlement_basis                VARCHAR(30)   NOT NULL DEFAULT 'SUM_INSURED',
            -- Share of the cap paid for the second and later events of the year.
            -- NULL = the event number reduces nothing.
            second_event_percentage         NUMERIC(5,2),
            -- Configured separately because they have different grounds: pending installments
            -- come from the product manual, since the policy ends with a total loss; the overdue
            -- balance from clause 102 art. 5.
            deduct_pending_installments     BOOLEAN       NOT NULL DEFAULT FALSE,
            deduct_overdue_balance          BOOLEAN       NOT NULL DEFAULT FALSE,

            CONSTRAINT coverage_settlement_basis_check
                CHECK (settlement_basis IN ('SUM_INSURED', 'LESSER_OF_SUM_AND_REPLACEMENT')),
            CONSTRAINT coverage_settlement_formula_check
                CHECK (settlement_formula IN ('TOTAL_LOSS', 'REPAIR'))
        )$ddl$, p_schema);

    -- ─── policy ──────────────────────────────────────────────────────────────────
    -- Local snapshot of the insurer's policy; external_policy_number is the key back to it.
    -- Sum insured and deductible belong to each contracted coverage, see policy_coverage.
    EXECUTE format($ddl$
        CREATE TABLE %I.policy (
            id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            external_policy_number  VARCHAR(50)   NOT NULL,
            product                 VARCHAR(1000) NOT NULL,
            in_force                BOOLEAN       NOT NULL DEFAULT TRUE,
            synced_at               TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
            insured_id              BIGINT        NOT NULL REFERENCES %I.insured(id),

            CONSTRAINT policy_external_number_unique UNIQUE (external_policy_number)
        )$ddl$, p_schema, p_schema);

    -- ─── policy_coverage ─────────────────────────────────────────────────────────
    -- What one policy contracted and for how much; mirrors the insurer DB's cobertura.
    -- Kept apart from coverage, which defines the risk for the whole insurer: merging them
    -- would need one catalog row per policy.
    EXECUTE format($ddl$
        CREATE TABLE %I.policy_coverage (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            policy_id       BIGINT        NOT NULL REFERENCES %I.policy(id) ON DELETE CASCADE,
            coverage_id     BIGINT        NOT NULL REFERENCES %I.coverage(id),
            display_order   INTEGER       NOT NULL DEFAULT 1,
            sum_insured     NUMERIC(15,2) NOT NULL,
            -- Percentage points, like coverage.deductible. The absolute amount is derived on read
            -- so it can never drift from sum_insured.
            deductible_pct  NUMERIC(5,2),

            CONSTRAINT policy_coverage_unique UNIQUE (policy_id, coverage_id)
        )$ddl$, p_schema, p_schema, p_schema);

    EXECUTE format('CREATE INDEX idx_policy_coverage_policy ON %I.policy_coverage (policy_id)', p_schema);

    -- ─── policy_snapshot ─────────────────────────────────────────────────────────
    -- The policy as the insurer DB described it when the claim was filed. Keeps the
    -- classification and the settlement auditable after the insurer's data changes.
    EXECUTE format($ddl$
        CREATE TABLE %I.policy_snapshot (
            id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            external_policy_number  VARCHAR(50)   NOT NULL,
            sum_insured             NUMERIC(15,2) NOT NULL,
            in_force                BOOLEAN       NOT NULL,
            payments_up_to_date     BOOLEAN       NOT NULL,   -- feeds the policy_standing factor
            previous_claims         INTEGER       NOT NULL DEFAULT 0,  -- feeds claim_frequency
            -- Nullable unlike previous_claims: a 0 would read as "never claimed anything".
            total_amount_claimed    NUMERIC(15,2),
            -- ─── Settlement inputs ───────────────────────────────────────────────────────
            effective_to            TIMESTAMPTZ,              -- to count pending installments
            installment_amount      NUMERIC(15,2),
            overdue_balance         NUMERIC(15,2),            -- as of queried_at
            -- 1 = first event in the rolling year. Uses the same 12-month window as
            -- MAX_EVENTS_YEAR so the events cap and the paid percentage never disagree.
            events_in_year          INTEGER,
            queried_at              TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
            insurer_db_payload      JSONB
        )$ddl$, p_schema);

    -- ─── insurer_rule ────────────────────────────────────────────────────────────
    -- `configuration` is JSONB so the referent can change thresholds without a redeploy.
    -- branch_id and coverage_id both NULL scope the rule to the whole insurer, used by
    -- rules checked against the policy as a whole (POLICY_IN_FORCE, POLICY_STANDING).
    EXECUTE format($ddl$
        CREATE TABLE %I.insurer_rule (
            id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            active              BOOLEAN      NOT NULL DEFAULT TRUE,
            valid_from          TIMESTAMPTZ  NOT NULL,
            configuration       JSONB,
            name                VARCHAR(150) NOT NULL,
            rule_type           VARCHAR(20)  NOT NULL,
            effect              VARCHAR(20),
            priority            INTEGER,
            blocks_fast_track   BOOLEAN      NOT NULL DEFAULT FALSE,
            branch_id           BIGINT       REFERENCES arbiter_common.branch(id),
            coverage_id         BIGINT       REFERENCES %I.coverage(id)
        )$ddl$, p_schema, p_schema);

    -- ─── insurer_rule_history ────────────────────────────────────────────────────
    EXECUTE format($ddl$
        CREATE TABLE %I.insurer_rule_history (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            config_version  JSONB        NOT NULL,
            changed_at      TIMESTAMPTZ  NOT NULL,
            reason          VARCHAR(255),
            valid_from      TIMESTAMPTZ  NOT NULL,
            valid_to        TIMESTAMPTZ,
            rule_id         BIGINT       NOT NULL REFERENCES %I.insurer_rule(id),
            changed_by      BIGINT       REFERENCES %I.insurer_referent(id)
        )$ddl$, p_schema, p_schema, p_schema);

    -- ─── scoring_configuration ───────────────────────────────────────────────────
    -- Backs RiskScoringService, so each insurer calibrates weights and bands without a
    -- redeploy. One per insurer: unlike Fast Track and the document schedule, scoring is
    -- not per branch.
    EXECUTE format($ddl$
        CREATE TABLE %I.scoring_configuration (
            id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name        VARCHAR(100) NOT NULL,
            active      BOOLEAN      NOT NULL DEFAULT TRUE,
            -- Whether Fast Track cases still run the heavy analysis, OCR and image fraud, for a
            -- complete score. It only decides how much runs; it never vetoes Fast Track.
            full_analysis_on_fast_track BOOLEAN NOT NULL DEFAULT FALSE,
            valid_from  TIMESTAMPTZ  NOT NULL
        )$ddl$, p_schema);

    -- factor_code matches RiskFactorIds by string: factors are an enum, not a table.
    EXECUTE format($ddl$
        CREATE TABLE %I.factor_weight (
            id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            factor_code              VARCHAR(80)  NOT NULL,
            weight                   NUMERIC(5,4) NOT NULL,
            scoring_configuration_id BIGINT       NOT NULL REFERENCES %I.scoring_configuration(id)
        )$ddl$, p_schema, p_schema);

    EXECUTE format($ddl$
        CREATE TABLE %I.score_band (
            id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            band                     VARCHAR(20)  NOT NULL,
            min_score_inclusive      NUMERIC(4,3) NOT NULL,
            active                   BOOLEAN      NOT NULL DEFAULT TRUE,
            scoring_configuration_id BIGINT       NOT NULL REFERENCES %I.scoring_configuration(id)
        )$ddl$, p_schema, p_schema);

    EXECUTE format($ddl$
        CREATE TABLE %I.scoring_configuration_history (
            id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            snapshot_config          JSONB        NOT NULL,
            valid_from               TIMESTAMPTZ  NOT NULL,
            valid_to                 TIMESTAMPTZ,
            changed_at               TIMESTAMPTZ  NOT NULL,
            reason                   VARCHAR(255),
            changed_by               BIGINT       REFERENCES %I.insurer_referent(id),
            scoring_configuration_id BIGINT       NOT NULL REFERENCES %I.scoring_configuration(id)
        )$ddl$, p_schema, p_schema, p_schema);

    -- ─── document_requirement ────────────────────────────────────────────────────
    -- The document schedule: required documents per branch and claim cause, optionally
    -- tightened for a risk band. It decides whether a case is complete.
    EXECUTE format($ddl$
        CREATE TABLE %I.document_requirement (
            id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            document_type       VARCHAR(50)  NOT NULL,
            mandatory           BOOLEAN      NOT NULL DEFAULT TRUE,
            risk_band           VARCHAR(20),  -- NULL = applies to every band
            branch_id           BIGINT       NOT NULL REFERENCES arbiter_common.branch(id),
            claim_cause_id      BIGINT       NOT NULL REFERENCES arbiter_common.claim_cause(id)
        )$ddl$, p_schema);

    -- ─── settlement_authority ────────────────────────────────────────────────────
    -- The most an analyst can authorize alone per branch; above it the settlement waits
    -- for the referent. Per branch, not per analyst, because there is a single analyst
    -- level. No row for a branch means no cap.
    EXECUTE format($ddl$
        CREATE TABLE %I.settlement_authority (
            id          BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            branch_id   BIGINT        NOT NULL REFERENCES arbiter_common.branch(id),
            max_amount  NUMERIC(15,2) NOT NULL,
            updated_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
            -- NULL on rows older than the tracking of this column.
            updated_by  BIGINT        REFERENCES arbiter_common.users(id),

            CONSTRAINT settlement_authority_branch_unique UNIQUE (branch_id),
            CONSTRAINT settlement_authority_amount_check CHECK (max_amount >= 0)
        )$ddl$, p_schema);

    -- ─── cases ───────────────────────────────────────────────────────────────────
    -- classification_id closes a cycle cases → case_classification → llm_analysis →
    -- cases, so its FK is added by ALTER TABLE once every table exists.
    EXECUTE format($ddl$
        CREATE TABLE %I.cases (
            id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            occurred_at                 TIMESTAMPTZ   NOT NULL,
            reported_at                 TIMESTAMPTZ   NOT NULL,
            police_report_at            TIMESTAMPTZ,
            updated_at                  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
            response_deadline           DATE          NOT NULL,
            description                 TEXT          NOT NULL,
            was_fast_track              BOOLEAN       NOT NULL DEFAULT FALSE,
            fraud_determined            BOOLEAN       NOT NULL DEFAULT FALSE,
            destination                 VARCHAR(40),
            -- What the insured claims, compared against policy_snapshot to surface gaps with
            -- what the insurer has on file.
            claimed_amount              NUMERIC(38,2),
            declared_item               VARCHAR(255),
            -- ─── Read model for the analyst's inbox ──────────────────────────────────────
            -- The only denormalized columns: the inbox filters, sorts and pages by risk band,
            -- and "latest risk_analysis row per case" is hard to index under paging.
            -- risk_analysis stays the auditable source.
            risk_score                  NUMERIC(4,3),
            risk_band                   VARCHAR(20),
            -- classification-service's assembled report. Per-image findings are also in
            -- image_analysis, but nothing rebuilds the report from them yet.
            forensic_report             JSONB,
            -- Retry counter for the classification poller. On the case because
            -- case_classification only exists once the analyst decides.
            classification_attempts     INTEGER       NOT NULL DEFAULT 0,
            -- Cause of the last failed classification run, cleared once a run succeeds.
            -- cases-service's startup recovery only requeues INFRASTRUCTURE failures.
            classification_failure_reason  VARCHAR(20),
            classification_failure_message TEXT,
            -- Set when the claim was filed while the document schedule was unreadable;
            -- DocumentRecheckScheduler checks it later. NULL once verified.
            documents_unverified_since  TIMESTAMPTZ,
            -- The analyst's note on the score, which it never overwrites. Written while the
            -- case is open, unlike case_classification.analyst_justification.
            manual_adjustment_note      TEXT,
            event_address               VARCHAR(120)  NOT NULL,
            event_latitude              NUMERIC(9,6),
            event_longitude             NUMERIC(9,6),
            locality                    VARCHAR(120),
            province                    VARCHAR(40),
            current_status_id           BIGINT        NOT NULL REFERENCES arbiter_common.case_status(id),
            analyst_id                  BIGINT        REFERENCES %I.claims_analyst(id),
            insured_id                  BIGINT        NOT NULL REFERENCES %I.insured(id),
            claim_cause_id              BIGINT        NOT NULL REFERENCES arbiter_common.claim_cause(id),
            coverage_id                 BIGINT        NOT NULL REFERENCES %I.coverage(id),
            policy_id                   BIGINT        NOT NULL REFERENCES %I.policy(id),
            policy_snapshot_id          BIGINT        REFERENCES %I.policy_snapshot(id),
            scoring_configuration_id    BIGINT        REFERENCES %I.scoring_configuration(id),
            classification_id           BIGINT
        )$ddl$, p_schema, p_schema, p_schema, p_schema, p_schema, p_schema, p_schema);

    EXECUTE format('CREATE INDEX idx_cases_status ON %I.cases (current_status_id)', p_schema);
    EXECUTE format('CREATE INDEX idx_cases_insured ON %I.cases (insured_id)', p_schema);
    -- The analyst's inbox filters by risk band and, by default, by owner.
    EXECUTE format('CREATE INDEX idx_cases_risk_band ON %I.cases (risk_band)', p_schema);
    EXECUTE format('CREATE INDEX idx_cases_analyst ON %I.cases (analyst_id)', p_schema);

    -- ─── case_documents ──────────────────────────────────────────────────────────
    EXECUTE format($ddl$
        CREATE TABLE %I.case_documents (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            type            VARCHAR(255) NOT NULL,
            filename        VARCHAR(255) NOT NULL,
            content_type    VARCHAR(255) NOT NULL,
            content         BYTEA        NOT NULL,
            uploaded_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            case_id         BIGINT       NOT NULL REFERENCES %I.cases(id) ON DELETE CASCADE,

            CONSTRAINT case_documents_case_type_unique UNIQUE (case_id, type)
        )$ddl$, p_schema, p_schema);

    -- ─── image_analysis ──────────────────────────────────────────────────────────
    -- Per tenant so image reuse detection never compares across insurers.
    EXECUTE format($ddl$
        CREATE TABLE %I.image_analysis (
            id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            embedding               public.vector(512),   -- CLIP ViT-B-32
            -- Vectors from different models are not comparable; without this a model change
            -- would silently invalidate every stored vector.
            model                   VARCHAR(80)  NOT NULL,
            similarity_score        NUMERIC(5,2),
            is_suspicious           BOOLEAN      NOT NULL DEFAULT FALSE,
            analyzed_at             TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            external_source         VARCHAR(150),
            external_reference      TEXT,
            match_type              VARCHAR(20),
            external_hash           VARCHAR(64),
            case_document_id        BIGINT NOT NULL REFERENCES %I.case_documents(id) ON DELETE CASCADE,
            similar_document_id     BIGINT REFERENCES %I.case_documents(id)
        )$ddl$, p_schema, p_schema, p_schema);

    -- IVFFlat only pays off from ~100 rows; below that a sequential scan is fine.
    EXECUTE format($ddl$
        CREATE INDEX idx_image_analysis_cosine ON %I.image_analysis
            USING ivfflat (embedding public.vector_cosine_ops) WITH (lists = 100)
        $ddl$, p_schema);

    -- ─── document_analysis ───────────────────────────────────────────────────────
    -- What the vision pass read out of one attachment. NULL means "the document doesn't
    -- say it", never "it doesn't match": a missing field must not read as an inconsistency.
    -- One row per document, upserted on every reclassification.
    EXECUTE format($ddl$
        CREATE TABLE %I.document_analysis (
            id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            transcription       TEXT         NOT NULL,
            document_date       DATE,
            amount              NUMERIC(14,2),
            -- Unbounded on purpose: an overflow fails the whole extraction silently, and
            -- brand/model are compared against the insured item, so truncating them would
            -- produce false findings.
            item_description    TEXT,
            -- What documents are matched on outside Celulares, where there is no IMEI.
            brand               TEXT,
            model               TEXT,
            imei                VARCHAR(20),
            affected_party      VARCHAR(20)  NOT NULL,
            extracted_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            case_document_id    BIGINT       NOT NULL REFERENCES %I.case_documents(id) ON DELETE CASCADE,

            CONSTRAINT document_analysis_document_unique UNIQUE (case_document_id),
            -- DESCONOCIDO is valid: the covers_family_group rule then stays out of it.
            CONSTRAINT document_analysis_affected_party_valid CHECK (
                affected_party IN ('TITULAR', 'FAMILIAR', 'TERCERO', 'DESCONOCIDO'))
        )$ddl$, p_schema, p_schema);

    -- ─── document_visual_finding ─────────────────────────────────────────────────
    -- Signs of tampering noticed by the vision model. Usually empty, and their absence is
    -- not evidence of authenticity.
    EXECUTE format($ddl$
        CREATE TABLE %I.document_visual_finding (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            finding         TEXT   NOT NULL,
            analysis_id     BIGINT NOT NULL REFERENCES %I.document_analysis(id) ON DELETE CASCADE
        )$ddl$, p_schema, p_schema);

    -- ─── document_detail ─────────────────────────────────────────────────────────
    -- Other data the document states, shown but never compared: the name is whatever the
    -- model called it. Data a rule compares gets a typed column in document_analysis.
    EXECUTE format($ddl$
        CREATE TABLE %I.document_detail (
            id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name            VARCHAR(100) NOT NULL,
            value           VARCHAR(500) NOT NULL,
            analysis_id     BIGINT       NOT NULL REFERENCES %I.document_analysis(id) ON DELETE CASCADE
        )$ddl$, p_schema, p_schema);

    -- ─── case_status_history ─────────────────────────────────────────────────────
    -- Append-only audit trail of every transition.
    EXECUTE format($ddl$
        CREATE TABLE %I.case_status_history (
            id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            reason              VARCHAR(255) NOT NULL,
            observation         TEXT,
            changed_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            -- INSURED / ANALYST / SYSTEM. Not derivable from changed_by: that is NULL for
            -- SYSTEM moves, which have no user behind them.
            actor               VARCHAR(20)  NOT NULL,
            changed_by          BIGINT       REFERENCES arbiter_common.users(id),
            initial_status_id   BIGINT       REFERENCES arbiter_common.case_status(id),
            final_status_id     BIGINT       NOT NULL REFERENCES arbiter_common.case_status(id),
            case_id             BIGINT       NOT NULL REFERENCES %I.cases(id) ON DELETE CASCADE
        )$ddl$, p_schema, p_schema);

    -- ─── expert_firm ─────────────────────────────────────────────────────────────
    -- External providers the analyst derives a case to. Not Arbiter users: they are
    -- reached by email, hence the address here. branch_id NULL = covers every branch;
    -- zone is an informative label with no assignment logic.
    EXECUTE format($ddl$
        CREATE TABLE %I.expert_firm (
            id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name        VARCHAR(120) NOT NULL,
            email       VARCHAR(150) NOT NULL,
            zone        VARCHAR(80),
            active      BOOLEAN      NOT NULL DEFAULT TRUE,
            branch_id   BIGINT       REFERENCES arbiter_common.branch(id),
            -- A loss adjuster investigates the cause, a repair shop handles the repair. One
            -- catalog because both are administered and derived to the same way.
            provider_type VARCHAR(20) NOT NULL DEFAULT 'ESTUDIO_LIQUIDADOR',
            CONSTRAINT expert_firm_provider_type_valid CHECK (
                provider_type IN ('ESTUDIO_LIQUIDADOR', 'SERVICIO_TECNICO'))
        )$ddl$, p_schema);

    -- ─── expert_assessment ───────────────────────────────────────────────────────
    -- One derivation to an external provider and the report that comes back. Name and
    -- email are copied so the record survives catalog edits. One row per case and
    -- provider type: a case may go to the loss adjuster and later to a repair shop,
    -- but never twice to the same kind.
    EXECUTE format($ddl$
        CREATE TABLE %I.expert_assessment (
            id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            expert_name         VARCHAR(120) NOT NULL,
            expert_email        VARCHAR(150) NOT NULL,
            reason              TEXT         NOT NULL,   -- why the analyst derived it
            derived_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            -- NULL = the best-effort email never went out, so nobody was actually asked.
            notified_at         TIMESTAMPTZ,
            -- derived_at → report_received_at is the round trip that pauses the art. 56 term.
            report_received_at  TIMESTAMPTZ,
            provider_type       VARCHAR(20)  NOT NULL DEFAULT 'ESTUDIO_LIQUIDADOR',
            verdict             VARCHAR(20),
            -- Separate from verdict, which is fraud vocabulary: a repair must never leave a
            -- fraud record on the insured.
            repair_outcome      VARCHAR(20),
            verdict_note        TEXT,
            -- Transcribed by the analyst from the expert's report. NULL = the expert gave no
            -- amount, which is not the same as saying zero.
            indemnifiable_amount NUMERIC(15,2),
            repair_cost         NUMERIC(15,2),
            derived_by          BIGINT       NOT NULL REFERENCES %I.claims_analyst(id),
            -- ON DELETE SET NULL: the assessment outlives the catalog row.
            expert_firm_id      BIGINT       REFERENCES %I.expert_firm(id) ON DELETE SET NULL,
            report_document_id  BIGINT       REFERENCES %I.case_documents(id),
            case_id             BIGINT       NOT NULL REFERENCES %I.cases(id) ON DELETE CASCADE,

            CONSTRAINT expert_assessment_case_unique UNIQUE (case_id, provider_type),
            CONSTRAINT expert_assessment_provider_type_valid CHECK (
                provider_type IN ('ESTUDIO_LIQUIDADOR', 'SERVICIO_TECNICO')),
            -- Matches common-lib's ExpertVerdict.
            CONSTRAINT expert_assessment_verdict_valid CHECK (
                verdict IS NULL
                OR verdict IN ('FRAUD_CONFIRMED', 'FRAUD_DISCARDED', 'INCONCLUSIVE')),
            CONSTRAINT expert_assessment_repair_outcome_valid CHECK (
                repair_outcome IS NULL
                OR repair_outcome IN ('REPAIRED', 'IRREPARABLE', 'QUOTE_SENT')),
            -- A report is all-or-nothing, and each provider type returns only its own result.
            -- repair_cost is required for QUOTE_SENT, optional for REPAIRED since the invoice
            -- may come later, and forbidden for IRREPARABLE.
            CONSTRAINT expert_assessment_report_complete CHECK (
                (report_received_at IS NULL AND verdict IS NULL AND repair_outcome IS NULL
                 AND repair_cost IS NULL)
                OR (report_received_at IS NOT NULL AND provider_type = 'ESTUDIO_LIQUIDADOR'
                    AND verdict IS NOT NULL AND repair_outcome IS NULL
                    AND repair_cost IS NULL)
                OR (report_received_at IS NOT NULL AND provider_type = 'SERVICIO_TECNICO'
                    AND verdict IS NULL
                    AND ((repair_outcome = 'QUOTE_SENT' AND repair_cost IS NOT NULL)
                         OR repair_outcome = 'REPAIRED'
                         OR (repair_outcome = 'IRREPARABLE' AND repair_cost IS NULL))))
        )$ddl$, p_schema, p_schema, p_schema, p_schema, p_schema);

    -- ─── insured_fraud_record ────────────────────────────────────────────────────
    -- Fraud memory about the person across claims. Owned by classification-service,
    -- which reads it when scoring, although the analyst confirms it from cases-service.
    -- Never updated: it is a statement about a person and must stay readable for audit.
    -- It stops counting when the FRAUD_RECORD rule's window expires.
    -- EXPERT_BACKED scores and can veto Fast Track; ANALYST_DECLARED only alerts the
    -- analyst, so a suspicion never feeds back into the next score.
    EXECUTE format($ddl$
        CREATE TABLE %I.insured_fraud_record (
            id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            -- DNI rather than insured_id: it is the identity the engine has at hand when the
            -- next claim arrives.
            insured_dni              VARCHAR(20)  NOT NULL,
            source                   VARCHAR(20)  NOT NULL,
            reason                   TEXT         NOT NULL,
            declared_by_analyst_id   BIGINT       NOT NULL REFERENCES %I.claims_analyst(id),
            -- Copied so the record stays readable after the analyst leaves.
            declared_by_analyst_name VARCHAR(255) NOT NULL,
            declared_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            expert_assessment_id     BIGINT       REFERENCES %I.expert_assessment(id),
            case_id                  BIGINT       NOT NULL REFERENCES %I.cases(id) ON DELETE CASCADE,

            CONSTRAINT insured_fraud_record_case_unique UNIQUE (case_id),
            CONSTRAINT insured_fraud_record_source_valid CHECK (
                source IN ('EXPERT_BACKED', 'ANALYST_DECLARED')),
            -- EXPERT_BACKED must point at an assessment, or it would be just a label.
            CONSTRAINT insured_fraud_record_backing_valid CHECK (
                (source = 'EXPERT_BACKED'    AND expert_assessment_id IS NOT NULL)
                OR (source = 'ANALYST_DECLARED' AND expert_assessment_id IS NULL))
        )$ddl$, p_schema, p_schema, p_schema, p_schema);

    -- Read by insured on every classification.
    EXECUTE format($ddl$
        CREATE INDEX idx_insured_fraud_record_dni ON %I.insured_fraud_record (insured_dni)
        $ddl$, p_schema);

    -- ─── risk_analysis ───────────────────────────────────────────────────────────
    EXECUTE format($ddl$
        CREATE TABLE %I.risk_analysis (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            risk_score      NUMERIC(4,3) NOT NULL,
            risk_band       VARCHAR(20)  NOT NULL,
            risk_breakdown  JSONB        NOT NULL,
            analyzed_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            case_id         BIGINT       NOT NULL REFERENCES %I.cases(id) ON DELETE CASCADE
        )$ddl$, p_schema, p_schema);

    -- ─── rule_result ─────────────────────────────────────────────────────────────
    EXECUTE format($ddl$
        CREATE TABLE %I.rule_result (
            id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            rule_type           VARCHAR(40)   NOT NULL,
            result              VARCHAR(20)   NOT NULL,
            evaluated_value     VARCHAR(150),
            score_contribution  NUMERIC(5,4),
            evaluated_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
            -- NULL for coverage-scope rules, which are columns of coverage rather than
            -- insurer_rule rows.
            rule_id             BIGINT        REFERENCES %I.insurer_rule(id),
            case_id             BIGINT        NOT NULL REFERENCES %I.cases(id) ON DELETE CASCADE
        )$ddl$, p_schema, p_schema, p_schema);

    -- ─── llm_analysis ────────────────────────────────────────────────────────────
    -- The model's non-binding recommendation, reasons as rows. Immutable for audit
    -- purposes, per SSN Disposición 2/2023.
    EXECUTE format($ddl$
        CREATE TABLE %I.llm_analysis (
            id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            recommendation      VARCHAR(50)  NOT NULL,
            model               VARCHAR(100) NOT NULL,
            prompt_version      VARCHAR(50)  NOT NULL,
            confidence          NUMERIC(5,3),
            latency_ms          INTEGER,
            analyzed_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            case_id             BIGINT       NOT NULL REFERENCES %I.cases(id) ON DELETE CASCADE,
            -- Whether the narrative matches the declared claim cause. NULL when not assessed.
            -- suggested_claim_cause is a claim_cause name but deliberately not an FK: this
            -- audit row must keep what the model answered even if the cause is renamed.
            cause_consistency       VARCHAR(20),
            suggested_claim_cause   VARCHAR(120),
            cause_evidence          TEXT,

            CONSTRAINT llm_analysis_cause_consistency_check CHECK (
                cause_consistency IS NULL
                OR cause_consistency IN ('MATCHES', 'AMBIGUOUS', 'CONTRADICTS')
            ),

            -- FAST_TRACK is decided by FastTrackValidator, never by the model.
            CONSTRAINT llm_analysis_recommendation_check CHECK (
                recommendation IN (
                    'FALTA_DOCUMENTACION',
                    'LLM_RECOMIENDA_APROBAR',
                    'LLM_NO_RECOMIENDA_APROBAR',
                    'LLM_SOLICITA_REVISION_MANUAL'
                )
            )
        )$ddl$, p_schema, p_schema);

    EXECUTE format($ddl$
        CREATE TABLE %I.llm_reason (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            reason          TEXT   NOT NULL,
            analysis_id     BIGINT NOT NULL REFERENCES %I.llm_analysis(id) ON DELETE CASCADE
        )$ddl$, p_schema, p_schema);

    -- ─── case_classification ─────────────────────────────────────────────────────
    -- The analyst's decision. Every resolved case passes through here: the model never
    -- resolves a case on its own.
    EXECUTE format($ddl$
        CREATE TABLE %I.case_classification (
            id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            decision                VARCHAR(20)  NOT NULL,
            analyst_justification   TEXT,
            decided_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            classification_attempts INTEGER      NOT NULL DEFAULT 0,
            llm_analysis_id         BIGINT       REFERENCES %I.llm_analysis(id),
            analyst_id              BIGINT       NOT NULL REFERENCES %I.claims_analyst(id)
        )$ddl$, p_schema, p_schema, p_schema);

    -- Closes the cases → case_classification cycle.
    EXECUTE format($ddl$
        ALTER TABLE %I.cases
            ADD CONSTRAINT cases_classification_fkey
            FOREIGN KEY (classification_id) REFERENCES %I.case_classification(id)
        $ddl$, p_schema, p_schema);

    -- ─── case_settlement ─────────────────────────────────────────────────────────
    -- How much is paid and how it was computed. Stores the inputs as well as the result,
    -- so the math is reproducible after the policy or the referent's parameters change.
    -- calculated_amount is the formula's result, settled_amount what the analyst
    -- authorized; if they differ the service requires adjustment_reason.
    -- One row per case, written only on confirmation: the proposal is recomputed.
    EXECUTE format($ddl$
        CREATE TABLE %I.case_settlement (
            id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            case_id                     BIGINT        NOT NULL REFERENCES %I.cases(id),
            formula                     VARCHAR(20)   NOT NULL DEFAULT 'TOTAL_LOSS',
            -- ─── Frozen inputs ───────────────────────────────────────────────────────────
            sum_insured                 NUMERIC(15,2) NOT NULL,
            settlement_basis            VARCHAR(30)   NOT NULL,
            replacement_value           NUMERIC(15,2),
            deductible_rate             NUMERIC(5,2),            -- percentage points
            event_ordinal               INTEGER       NOT NULL DEFAULT 1,
            event_percentage            NUMERIC(5,2)  NOT NULL DEFAULT 100,
            pending_installments        INTEGER       NOT NULL DEFAULT 0,
            installment_amount          NUMERIC(15,2),
            -- ─── Applied deductions ──────────────────────────────────────────────────────
            deductible_amount           NUMERIC(15,2) NOT NULL DEFAULT 0,
            pending_installments_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
            overdue_balance_amount      NUMERIC(15,2) NOT NULL DEFAULT 0,
            -- ─── Result ──────────────────────────────────────────────────────────────────
            calculated_amount           NUMERIC(15,2) NOT NULL,
            settled_amount              NUMERIC(15,2) NOT NULL,
            adjustment_reason           TEXT,
            -- ─── Settlement authority ────────────────────────────────────────────────────
            -- PENDING_AUTHORIZATION: above the analyst's cap, waiting for the referent. The
            -- case keeps its status meanwhile: this step is internal to the insurer.
            status                      VARCHAR(25)   NOT NULL DEFAULT 'AUTHORIZED',
            -- The cap in force at confirmation, frozen. NULL = the branch had no cap.
            authority_limit             NUMERIC(15,2),
            -- NULL when within the analyst's cap. Points at users because cases-service
            -- does not map insurer_referent.
            authorized_by_user_id       BIGINT        REFERENCES arbiter_common.users(id),
            authorized_at               TIMESTAMPTZ,
            -- Overwritten on the next confirmation; no history of round trips is kept.
            return_reason               TEXT,
            -- The analyst's justification held while authorization is pending: the decision
            -- is only recorded in case_classification once the referent authorizes.
            pending_justification       TEXT,
            -- ─── Traceability ────────────────────────────────────────────────────────────
            coverage_id                 BIGINT        NOT NULL REFERENCES %I.coverage(id),
            policy_snapshot_id          BIGINT        REFERENCES %I.policy_snapshot(id),
            analyst_id                  BIGINT        NOT NULL REFERENCES %I.claims_analyst(id),
            calculated_at               TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
            confirmed_at                TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

            CONSTRAINT case_settlement_case_unique UNIQUE (case_id),
            CONSTRAINT case_settlement_formula_check CHECK (formula IN ('TOTAL_LOSS', 'REPAIR')),
            CONSTRAINT case_settlement_status_check
                CHECK (status IN ('AUTHORIZED', 'PENDING_AUTHORIZATION', 'RETURNED')),
            CONSTRAINT case_settlement_basis_check
                CHECK (settlement_basis IN ('SUM_INSURED', 'LESSER_OF_SUM_AND_REPLACEMENT'))
        )$ddl$, p_schema, p_schema, p_schema, p_schema, p_schema);

    -- ─── notification ────────────────────────────────────────────────────────────
    -- Outbound messages to the insured.
    EXECUTE format($ddl$
        CREATE TABLE %I.notification (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            type            VARCHAR(60)  NOT NULL,
            channel         VARCHAR(30)  NOT NULL,
            content         TEXT         NOT NULL,
            sent            BOOLEAN      NOT NULL DEFAULT FALSE,
            read            BOOLEAN      NOT NULL DEFAULT FALSE,
            -- Separate from sent_at, which stays NULL if the mail never went out.
            created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
            sent_at         TIMESTAMPTZ,
            read_at         TIMESTAMPTZ,
            recipient_id    BIGINT       NOT NULL REFERENCES arbiter_common.users(id),
            case_id         BIGINT       REFERENCES %I.cases(id) ON DELETE CASCADE
        )$ddl$, p_schema, p_schema);

    -- ─── case_message ────────────────────────────────────────────────────────────
    -- Insured-analyst conversation about one case.
    EXECUTE format($ddl$
        CREATE TABLE %I.case_message (
            id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            case_id         BIGINT       NOT NULL REFERENCES %I.cases(id) ON DELETE CASCADE,
            sender_id       BIGINT       NOT NULL REFERENCES arbiter_common.users(id),
            -- INSURED | ANALYST, frozen at write time.
            sender_role     VARCHAR(30)  NOT NULL,
            body            TEXT         NOT NULL,
            created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
            -- When the other side read it; NULL counts toward the unread badge.
            read_at         TIMESTAMPTZ
        )$ddl$, p_schema, p_schema);

    EXECUTE format('CREATE INDEX idx_case_message_case ON %I.case_message (case_id, created_at)',
                   p_schema);

    -- ─── Per-tenant seed ─────────────────────────────────────────────────────────
    EXECUTE format($ddl$
        INSERT INTO %I.coverage (id, name, description, report_deadline_hours,
                                 max_events_per_year, covers_family_group, deductible,
                                 claim_exhausts_coverage, is_individual, waiting_period_days, branch_id,
                                 settlement_formula, settlement_basis, second_event_percentage,
                                 deduct_pending_installments, deduct_overdue_balance) VALUES
            -- Total loss: sum insured minus deductible minus the year's pending installments,
            -- since the policy ends with the claim. Two events a year, the second at 50%%.
            (1, 'Robo de celular', 'Cobertura por robo en vía pública', 72, 2, FALSE, 10.00, FALSE, TRUE, 30, 1,
             'TOTAL_LOSS', 'SUM_INSURED', 50.00, TRUE, TRUE),
            -- One event a year, so no second-event percentage.
            (2, 'Hurto', 'Cobertura por hurto sin violencia', 72, 1, FALSE, 20.00, TRUE, TRUE, 30, 1,
             'TOTAL_LOSS', 'SUM_INSURED', NULL, TRUE, TRUE)
        $ddl$, p_schema);

    -- Per-branch caps sized to each branch's typical sum insured, so small claims stay with
    -- the analyst and large ones go to the referent.
    EXECUTE format($ddl$
        INSERT INTO %I.settlement_authority (branch_id, max_amount) VALUES
            (1, 500000.00),
            (2,  50000.00)
        $ddl$, p_schema);

    -- Fast Track gate thresholds, one row per coverage; values match MockRulesAdapter's
    -- baseline. requiredDocumentTypes is only the first batch asked at filing: the full
    -- document schedule is required only if the case does not fast-track.
    -- The gate reads the text extracted from these documents, not their presence, so an
    -- unreadable attachment loses Fast Track. Hence never item_photo: a photo has no text.
    EXECUTE format($ddl$
        INSERT INTO %I.insurer_rule (id, active, valid_from, name, rule_type, effect, priority,
                                     blocks_fast_track, branch_id, coverage_id, configuration) VALUES
            (1, TRUE, '2026-01-01 00:00:00+00',
             'Fast Track — Robo de celular', 'FAST_TRACK', 'APROBAR', 1, FALSE, 1, 1,
             '{"maxClaimedAmountRatio":0.5,"maxPriorClaims":0,"requiresUpToDatePolicy":true,
               "requiredDocumentTypes":["police_report","purchase_proof"],
               "criteria":["Primer siniestro del asegurado",
                           "Monto reclamado inferior al 50%% de la suma asegurada",
                           "Póliza al día con sus pagos"]}'),
            (2, TRUE, '2026-01-01 00:00:00+00',
             'Fast Track — Hurto', 'FAST_TRACK', 'APROBAR', 2, FALSE, 1, 2,
             '{"maxClaimedAmountRatio":0.3,"maxPriorClaims":0,"requiresUpToDatePolicy":true,
               "requiredDocumentTypes":["police_report","purchase_proof"],
               "criteria":["Primer siniestro del asegurado",
                           "Monto reclamado inferior al 30%% de la suma asegurada",
                           "Póliza al día con sus pagos"]}')
        $ddl$, p_schema);

    -- COVERAGE_EXCLUSION is a deny-list of claim causes the coverage does not cover; unlike
    -- the rows above, it is evaluated against the claim and leaves a rule_result row.
    -- Each claim cause of a branch must be covered by exactly one coverage, which is how
    -- PolicyCoverageResolver picks the coverage when a policy has several.
    -- Celulares causes: 1 Rotura accidental, 2 Robo en vía pública, 3 Hurto, 4 Caída.
    EXECUTE format($ddl$
        INSERT INTO %I.insurer_rule (id, active, valid_from, name, rule_type, effect, priority,
                                     blocks_fast_track, branch_id, coverage_id, configuration) VALUES
            (3, TRUE, '2026-01-01 00:00:00+00',
             'La cobertura de robo solo cubre robo en vía pública', 'COVERAGE_EXCLUSION', 'RECHAZAR', 1,
             TRUE, 1, 1, '{"excludedClaimCauseIds":[1,3,4]}'),
            (4, TRUE, '2026-01-01 00:00:00+00',
             'La cobertura de hurto solo cubre hurto', 'COVERAGE_EXCLUSION', 'RECHAZAR', 1,
             TRUE, 1, 2, '{"excludedClaimCauseIds":[1,2,4]}')
        $ddl$, p_schema);

    -- Coverage-scoped temporal rules. The row is the switch: without it TemporalRuleEvaluator
    -- skips the rule, so a new insurer inherits nothing unconfigured. Thresholds are coverage
    -- columns, except POLICE_DEADLINE's: report_deadline_hours is the deadline to report to
    -- the insurer, a different one. Ids mirror MockRulesAdapter's baseline.
    EXECUTE format($ddl$
        INSERT INTO %I.insurer_rule (id, active, valid_from, name, rule_type, effect, priority,
                                     blocks_fast_track, branch_id, coverage_id, configuration) VALUES
            (5,  TRUE, '2026-01-01 00:00:00+00', 'Carencia de la cobertura (cobertura 1)',
             'WAITING_PERIOD',  'DERIVAR', 2, TRUE, 1, 1, '{}'),
            (6,  TRUE, '2026-01-01 00:00:00+00', 'Plazo de denuncia a la aseguradora (cobertura 1)',
             'REPORT_DEADLINE', 'DERIVAR', 3, TRUE, 1, 1, '{}'),
            -- Off by default: the deadline is not strict enough to derive on its own. An insurer
            -- that wants it can turn it on from the panel.
            (7,  FALSE, '2026-01-01 00:00:00+00', 'Plazo de la denuncia policial (cobertura 1)',
             'POLICE_DEADLINE', 'DERIVAR', 4, TRUE, 1, 1, '{"deadlineHours":72}'),
            (8,  TRUE, '2026-01-01 00:00:00+00', 'Tope de eventos por año (cobertura 1)',
             'MAX_EVENTS_YEAR', 'DERIVAR', 5, TRUE, 1, 1, '{}'),
            (10, TRUE, '2026-01-01 00:00:00+00', 'Carencia de la cobertura (cobertura 2)',
             'WAITING_PERIOD',  'DERIVAR', 2, TRUE, 1, 2, '{}'),
            (11, TRUE, '2026-01-01 00:00:00+00', 'Plazo de denuncia a la aseguradora (cobertura 2)',
             'REPORT_DEADLINE', 'DERIVAR', 3, TRUE, 1, 2, '{}'),
            (12, FALSE, '2026-01-01 00:00:00+00', 'Plazo de la denuncia policial (cobertura 2)',
             'POLICE_DEADLINE', 'DERIVAR', 4, TRUE, 1, 2, '{"deadlineHours":72}'),
            (13, TRUE, '2026-01-01 00:00:00+00', 'Tope de eventos por año (cobertura 2)',
             'MAX_EVENTS_YEAR', 'DERIVAR', 5, TRUE, 1, 2, '{}')
        $ddl$, p_schema);

    -- Insurer-scoped: a policy is in force or not regardless of the coverage. POLICY_STANDING
    -- is not seeded on purpose; an insurer turns it on from the Hard Stop tab.
    EXECUTE format($ddl$
        INSERT INTO %I.insurer_rule (id, active, valid_from, name, rule_type, effect, priority,
                                     blocks_fast_track, branch_id, coverage_id, configuration) VALUES
            (14, TRUE, '2026-01-01 00:00:00+00', 'Vigencia de la póliza',
             'POLICY_IN_FORCE', 'DERIVAR', 1, TRUE, NULL, NULL, '{}')
        $ddl$, p_schema);

    -- Expert derivation policy, opt-in per branch: an assessment has a fixed cost, so below a
    -- minimum claim it costs more than the claim. Without a row the option is not offered.
    -- DERIVAR here means "to an external expert"; the temporal rules above use the same
    -- literal for "to analyst review". rule_type tells them apart.
    EXECUTE format($ddl$
        INSERT INTO %I.insurer_rule (id, active, valid_from, name, rule_type, effect, priority,
                                     blocks_fast_track, branch_id, coverage_id, configuration) VALUES
            (15, TRUE, '2026-01-01 00:00:00+00',
             'Derivar a peritaje desde $500.000 reclamados', 'EXPERT_DERIVATION', 'DERIVAR', 1,
             FALSE, 1, NULL, '{"minClaimedAmount":500000}'),
            (16, TRUE, '2026-01-01 00:00:00+00',
             'Derivar a peritaje desde $700.000 reclamados', 'EXPERT_DERIVATION', 'DERIVAR', 1,
             FALSE, 2, NULL, '{"minClaimedAmount":700000}')
        $ddl$, p_schema);

    -- Fraud record policy, insurer-scoped: the record belongs to the person. The window keeps
    -- old records from weighing forever, and is the insurer's call.
    -- It blocks Fast Track but never rejects: a past fraud is a reason for a human to look,
    -- not an exclusion of this claim. Without an active row records are still kept and
    -- shown, but neither score nor veto.
    EXECUTE format($ddl$
        INSERT INTO %I.insurer_rule (id, active, valid_from, name, rule_type, effect, priority,
                                     blocks_fast_track, branch_id, coverage_id, configuration) VALUES
            (17, TRUE, '2026-01-01 00:00:00+00', 'Antecedente de fraude del asegurado',
             'FRAUD_RECORD', 'DERIVAR', 1, TRUE, NULL, NULL, '{"windowMonths":36}')
        $ddl$, p_schema);

    -- Claim causes that can go to a repair shop; opt-in like expert derivation. Only damage
    -- causes: a stolen item has nothing to repair.
    EXECUTE format($ddl$
        INSERT INTO %I.insurer_rule (id, active, valid_from, name, rule_type, effect, priority,
                                     blocks_fast_track, branch_id, coverage_id, configuration) VALUES
            (18, TRUE, '2026-01-01 00:00:00+00',
             'Derivar a reparación: rotura accidental y caída', 'REPAIR_DERIVATION', 'DERIVAR', 1,
             FALSE, 1, NULL, '{"claimCauseIds":[1,4]}'),
            (19, TRUE, '2026-01-01 00:00:00+00',
             'Derivar a reparación: daño accidental', 'REPAIR_DERIVATION', 'DERIVAR', 1,
             FALSE, 2, NULL, '{"claimCauseIds":[6]}')
        $ddl$, p_schema);

    -- The insurer's own resolution target, not the legal deadline in cases.response_deadline.
    -- Nothing enforces it; only the dashboard reads it.
    EXECUTE format($ddl$
        INSERT INTO %I.insurer_rule (id, active, valid_from, name, rule_type, effect, priority,
                                     blocks_fast_track, branch_id, coverage_id, configuration) VALUES
            (20, TRUE, '2026-01-01 00:00:00+00', 'Objetivo de resolución',
             'RESOLUTION_TARGET', NULL, NULL, FALSE, NULL, NULL, '{"targetDays":21}')
        $ddl$, p_schema);

    -- Document types use the same codes as claim filing and classification. Every claim
    -- cause is seeded: a cause with no rows means "requires nothing".
    -- Theft asks for police report and proof of purchase, plus IMEI deregistration and last
    -- connection only for Celulares. Damage asks for proof of purchase, repair quote and a
    -- photo of the item.
    EXECUTE format($ddl$
        INSERT INTO %I.document_requirement (id, document_type, mandatory, risk_band, branch_id, claim_cause_id) VALUES
            -- Celulares · Robo en vía pública
            ( 1, 'police_report',       TRUE, NULL, 1, 2),
            ( 2, 'purchase_proof',      TRUE, NULL, 1, 2),
            ( 3, 'imei_deregistration', TRUE, NULL, 1, 2),
            ( 4, 'last_connection',     TRUE, NULL, 1, 2),
            -- Celulares · Hurto
            ( 5, 'police_report',       TRUE, NULL, 1, 3),
            ( 6, 'purchase_proof',      TRUE, NULL, 1, 3),
            ( 7, 'imei_deregistration', TRUE, NULL, 1, 3),
            ( 8, 'last_connection',     TRUE, NULL, 1, 3),
            -- Celulares · Caída
            ( 9, 'purchase_proof',      TRUE, NULL, 1, 4),
            (10, 'repair_quote',        TRUE, NULL, 1, 4),
            (11, 'item_photo',          TRUE, NULL, 1, 4),
            -- Celulares · Rotura accidental
            (12, 'purchase_proof',      TRUE, NULL, 1, 1),
            (13, 'repair_quote',        TRUE, NULL, 1, 1),
            (14, 'item_photo',          TRUE, NULL, 1, 1),
            -- Tecnología Portátil · Daño accidental
            (15, 'purchase_proof',      TRUE, NULL, 2, 6),
            (16, 'repair_quote',        TRUE, NULL, 2, 6),
            (17, 'item_photo',          TRUE, NULL, 2, 6),
            -- Tecnología Portátil · Robo en vía pública
            (18, 'police_report',       TRUE, NULL, 2, 7),
            (19, 'purchase_proof',      TRUE, NULL, 2, 7),
            (20, 'item_photo',          TRUE, NULL, 2, 7),
            -- Tecnología Portátil · Hurto
            (21, 'police_report',       TRUE, NULL, 2, 8),
            (22, 'purchase_proof',      TRUE, NULL, 2, 8),
            (23, 'item_photo',          TRUE, NULL, 2, 8)
        $ddl$, p_schema);

    -- Same values as MockRulesAdapter.DEFAULT_SCORING_CONFIG; each tenant diverges from here.
    EXECUTE format($ddl$
        INSERT INTO %I.scoring_configuration (id, name, active, full_analysis_on_fast_track, valid_from) VALUES
            (1, 'Default (H0012 reference config)', TRUE, FALSE, '2026-01-01 00:00:00+00')
        $ddl$, p_schema);

    EXECUTE format($ddl$
        INSERT INTO %I.factor_weight (id, factor_code, weight, scoring_configuration_id) VALUES
            (1, 'amount_ratio', 0.45, 1),
            (2, 'claim_frequency', 0.35, 1),
            (3, 'policy_standing', 0.20, 1),
            (4, 'image_reuse', 0.50, 1),
            (5, 'image_web_match', 0.40, 1),
            -- Heaviest factor, being the only one backed by a human-verified fact, but not
            -- enough alone to reach CRITICAL. Skipped without an active FRAUD_RECORD rule.
            (6, 'fraud_history', 0.60, 1)
        $ddl$, p_schema);

    EXECUTE format($ddl$
        INSERT INTO %I.score_band (id, band, min_score_inclusive, active, scoring_configuration_id) VALUES
            (1, 'LOW', 0.00, TRUE, 1),
            (2, 'MEDIUM', 0.30, TRUE, 1),
            (3, 'HIGH', 0.60, TRUE, 1),
            (4, 'CRITICAL', 0.80, TRUE, 1)
        $ddl$, p_schema);

    -- Realign every identity sequence with the explicit ids seeded above.
    EXECUTE format($ddl$SELECT setval(pg_get_serial_sequence('%I.coverage','id'),
        (SELECT MAX(id) FROM %I.coverage))$ddl$, p_schema, p_schema);
    EXECUTE format($ddl$SELECT setval(pg_get_serial_sequence('%I.insurer_rule','id'),
        (SELECT MAX(id) FROM %I.insurer_rule))$ddl$, p_schema, p_schema);
    EXECUTE format($ddl$SELECT setval(pg_get_serial_sequence('%I.document_requirement','id'),
        (SELECT MAX(id) FROM %I.document_requirement))$ddl$, p_schema, p_schema);
    EXECUTE format($ddl$SELECT setval(pg_get_serial_sequence('%I.scoring_configuration','id'),
        (SELECT MAX(id) FROM %I.scoring_configuration))$ddl$, p_schema, p_schema);
    EXECUTE format($ddl$SELECT setval(pg_get_serial_sequence('%I.factor_weight','id'),
        (SELECT MAX(id) FROM %I.factor_weight))$ddl$, p_schema, p_schema);
    EXECUTE format($ddl$SELECT setval(pg_get_serial_sequence('%I.score_band','id'),
        (SELECT MAX(id) FROM %I.score_band))$ddl$, p_schema, p_schema);
END;
$fn$ LANGUAGE plpgsql;

-- =============================================================================
-- "BD ASEGURADORA" SCHEMA TEMPLATE — the external insurer system, simulated
--
-- Stands in for the insurer's own database, one schema per insurer. Names stay in
-- Spanish: it simulates a third-party system, read only through InsurerDatabaseAdapter.
-- =============================================================================

CREATE OR REPLACE FUNCTION arbiter_common.create_insurer_db_schema(
    p_schema       TEXT,
    p_legal_name   TEXT,
    p_tax_id       TEXT,
    p_ssn_registry TEXT
) RETURNS VOID AS $fn$
BEGIN
    EXECUTE format('CREATE SCHEMA %I', p_schema);

    EXECUTE format($ddl$
        CREATE TABLE %I.compania (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nombre          VARCHAR(255) NOT NULL,
            cuit            VARCHAR(20)  NOT NULL UNIQUE,
            ssn_registro    VARCHAR(20),
            created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW()
        )$ddl$, p_schema);

    EXECUTE format($ddl$
        CREATE TABLE %I.asegurado (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            documento       VARCHAR(20)  NOT NULL UNIQUE,
            cuil            VARCHAR(20),
            nombre          VARCHAR(120) NOT NULL,
            apellido        VARCHAR(120) NOT NULL,
            email           VARCHAR(255),
            telefono        VARCHAR(50),
            created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW()
        )$ddl$, p_schema);

    EXECUTE format($ddl$
        CREATE TABLE %I.poliza (
            id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            numero                VARCHAR(80)   NOT NULL UNIQUE,
            nro_certificado       VARCHAR(80),
            titular_id            BIGINT        NOT NULL REFERENCES %I.asegurado(id),
            rama                  VARCHAR(80)   NOT NULL,
            producto              VARCHAR(160)  NOT NULL,
            bien_asegurado        VARCHAR(255),
            -- Celulares only; compared against the IMEI extracted from the documents.
            imei                  VARCHAR(20),
            moneda                VARCHAR(3)    NOT NULL DEFAULT 'ARS',
            -- TIMESTAMP, not DATE: coverage starts at an exact hour, so a claim earlier that same
            -- day must fail the in-force check. Without time zone because InsurerDatabaseAdapter
            -- reads it as LocalDateTime, which the driver rejects for TIMESTAMPTZ.
            vigencia_desde        TIMESTAMP     NOT NULL,
            vigencia_hasta        TIMESTAMP     NOT NULL,
            estado_contrato       VARCHAR(20)   NOT NULL,
            estado_pago           VARCHAR(20)   NOT NULL,
            cuotas_pagas          INTEGER       NOT NULL DEFAULT 0,
            cuotas_impagas        INTEGER       NOT NULL DEFAULT 0,
            saldo_deuda           NUMERIC(38,2) NOT NULL DEFAULT 0,
            forma_pago            VARCHAR(60),
            -- Needed to deduct pending installments; saldo_deuda only covers what is overdue.
            importe_cuota         NUMERIC(38,2),
            max_eventos_anuales   INTEGER,
            segundo_evento_pct    NUMERIC(5,2),
            cubre_grupo_familiar  BOOLEAN       NOT NULL DEFAULT FALSE,
            datos_proveedor       JSONB,
            created_at            TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

            CONSTRAINT poliza_rama_check CHECK (rama IN ('Celulares', 'Tecnología Portátil')),
            CONSTRAINT poliza_estado_pago_check CHECK (estado_pago IN ('AL_DIA','SUSPENDIDA','RESUELTA'))
        )$ddl$, p_schema, p_schema);

    EXECUTE format('CREATE INDEX idx_poliza_numero ON %I.poliza (numero)', p_schema);

    EXECUTE format($ddl$
        CREATE TABLE %I.cobertura (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            poliza_id       BIGINT        NOT NULL REFERENCES %I.poliza(id) ON DELETE CASCADE,
            orden           INTEGER       NOT NULL DEFAULT 1,
            nombre          VARCHAR(160)  NOT NULL,
            suma_asegurada  NUMERIC(38,2) NOT NULL,
            franquicia_pct  NUMERIC(5,2),
            created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

            CONSTRAINT cobertura_poliza_orden_unique UNIQUE (poliza_id, orden),
            CONSTRAINT cobertura_nombre_check
                CHECK (nombre IN ('Robo de celular', 'Hurto', 'Daño accidental'))
        )$ddl$, p_schema, p_schema);

    EXECUTE format('CREATE INDEX idx_cobertura_poliza ON %I.cobertura (poliza_id)', p_schema);

    -- Previous resolved claims; feeds the claim_frequency risk factor.
    EXECUTE format($ddl$
        CREATE TABLE %I.siniestro_historico (
            id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            poliza_id           BIGINT       NOT NULL REFERENCES %I.poliza(id),
            -- What consumes a coverage's sum insured is what was paid against that coverage.
            -- NULL makes the rule skip the row instead of charging the wrong coverage.
            cobertura_id        BIGINT       REFERENCES %I.cobertura(id),
            asegurado_id        BIGINT       NOT NULL REFERENCES %I.asegurado(id),
            fecha_ocurrencia    DATE         NOT NULL,
            causa               VARCHAR(120) NOT NULL,
            estado_resolucion   VARCHAR(40)  NOT NULL,
            monto_indemnizado   NUMERIC(38,2),
            created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW()
        )$ddl$, p_schema, p_schema, p_schema, p_schema);

    EXECUTE format('CREATE INDEX idx_sinhist_asegurado ON %I.siniestro_historico (asegurado_id)',
                   p_schema);

    EXECUTE format($ddl$
        INSERT INTO %I.compania (id, nombre, cuit, ssn_registro) VALUES (1, %L, %L, %L)
        $ddl$, p_schema, p_legal_name, p_tax_id, p_ssn_registry);
END;
$fn$ LANGUAGE plpgsql;

-- =============================================================================
-- TENANT PROVISIONING
-- =============================================================================

SELECT arbiter_common.create_tenant_schema('arbiter_bbva');
SELECT arbiter_common.create_tenant_schema('arbiter_provincia');

SELECT arbiter_common.create_insurer_db_schema(
    'aseguradora_bbva', 'BBVA Seguros Argentina S.A.', '30-50006423-0', '0396');
SELECT arbiter_common.create_insurer_db_schema(
    'aseguradora_provincia', 'Provincia Seguros S.A.', '30-57411408-6', '0326');

-- ─── Role profiles, per tenant ───────────────────────────────────────────────
INSERT INTO arbiter_bbva.insured (id, name, surname, dni, email, phone, pep, user_id) VALUES
    (1, 'Martina', 'Soteras', '42.987.654', 'asegurado.arbiter@gmail.com', '+54 9 11 5555-0001', FALSE, 1);

SELECT setval(pg_get_serial_sequence('arbiter_bbva.insured', 'id'),
              (SELECT MAX(id) FROM arbiter_bbva.insured));

INSERT INTO arbiter_bbva.claims_analyst (id, name, surname, email, user_id) VALUES
    (1, 'Lucas', 'Gómez', 'analista.arbiter@gmail.com', 2),
    (2, 'Federico', 'Alvarez', 'federico21433@hotmail.com', 8);

SELECT setval(pg_get_serial_sequence('arbiter_bbva.claims_analyst', 'id'),
              (SELECT MAX(id) FROM arbiter_bbva.claims_analyst));

INSERT INTO arbiter_bbva.insurer_referent (id, name, surname, user_id) VALUES
    (1, 'Sofía', 'Martínez', 3);

SELECT setval(pg_get_serial_sequence('arbiter_bbva.insurer_referent', 'id'),
              (SELECT MAX(id) FROM arbiter_bbva.insurer_referent));

INSERT INTO arbiter_provincia.claims_analyst (id, name, surname, email, user_id) VALUES
    (1, 'Diego', 'Fernández', 'analista.provincia.arbiter@gmail.com', 4),
    (2, 'Federico', 'Moccia', 'mocciafederico@hotmail.com', 7);

SELECT setval(pg_get_serial_sequence('arbiter_provincia.claims_analyst', 'id'),
              (SELECT MAX(id) FROM arbiter_provincia.claims_analyst));

INSERT INTO arbiter_provincia.insurer_referent (id, name, surname, user_id) VALUES
    (1, 'Paula', 'Ríos', 6);

SELECT setval(pg_get_serial_sequence('arbiter_provincia.insurer_referent', 'id'),
              (SELECT MAX(id) FROM arbiter_provincia.insurer_referent));

COMMIT;

-- =============================================================================
-- Onboarding a third insurer needs no hand-written DDL:
--   INSERT INTO arbiter_common.insurer (legal_name, name, tax_id, active, schema_name)
--        VALUES ('La Segunda Seguros S.A.', 'La Segunda', '30-50001328-8', TRUE, 'arbiter_lasegunda');
--   SELECT arbiter_common.create_tenant_schema('arbiter_lasegunda');
--   SELECT arbiter_common.create_insurer_db_schema(
--       'aseguradora_lasegunda', 'La Segunda Seguros S.A.', '30-50001328-8', '0331');
--
-- Policies, insured, claim history and demo cases live in db/seed-demo.sql.
-- =============================================================================
