-- =============================================================================
-- Arbiter — script de inicialización de BD
-- Dropea tablas legacy + actuales, recrea el schema limpio y seedea datos de prueba.
--
-- Uso:
--   docker exec -i arbiter-postgres-1 psql -U arbiter -d arbiter < db/init.sql
-- =============================================================================

-- Alinea la versión de collation de la base con la del SO del contenedor. Sin esto,
-- si la imagen de Postgres actualizó su libc respecto a cuando se creó el volumen,
-- cada conexión tira un WARNING de "collation version mismatch". Fuera del BEGIN:
-- ALTER DATABASE es su propia transacción.
ALTER DATABASE arbiter REFRESH COLLATION VERSION;

BEGIN;

-- ─── Limpiar tablas legacy y actuales ────────────────────────────────────────
DROP TABLE IF EXISTS adjunto CASCADE;
DROP TABLE IF EXISTS claim CASCADE;
DROP TABLE IF EXISTS clasificacion_log CASCADE;
DROP TABLE IF EXISTS siniestro CASCADE;
DROP TABLE IF EXISTS classification_log CASCADE;
DROP TABLE IF EXISTS case_status_history CASCADE;
DROP TABLE IF EXISTS case_documents CASCADE;
DROP TABLE IF EXISTS cases CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- ─── users (auth-service) ────────────────────────────────────────────────────
-- H0001 - Inicio de sesión. Login propio como paso transitorio hasta integrar Auth0
-- (ver CLAUDE.md, decisión #8).
CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(255) NOT NULL UNIQUE,
    password_hash   VARCHAR(255) NOT NULL,
    nombre          VARCHAR(255) NOT NULL,
    apellido        VARCHAR(255) NOT NULL,
    rol             VARCHAR(40)  NOT NULL,
    sector          VARCHAR(255),
    fecha_ingreso   DATE,
    insured_id      VARCHAR(255),
    failed_attempts INTEGER      NOT NULL DEFAULT 0,
    locked_until    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT users_rol_check CHECK (
        rol IN ('ASEGURADO', 'ANALISTA_SINIESTROS', 'REFERENTE_ASEGURADORA')
    )
);

-- ─── cases (cases-service) ───────────────────────────────────────────────────
CREATE TABLE cases (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch                  VARCHAR(255) NOT NULL,
    product                 VARCHAR(255) NOT NULL,
    claim_cause             VARCHAR(255) NOT NULL,
    insured_item            VARCHAR(255) NOT NULL,
    insured_id              VARCHAR(255) NOT NULL,
    insured_name            VARCHAR(255),
    policy_number           VARCHAR(255) NOT NULL,
    description             TEXT         NOT NULL,
    event_date              TIMESTAMP(6) NOT NULL,
    event_location          VARCHAR(255) NOT NULL,
    claimed_amount          NUMERIC(38,2),
    pep                     BOOLEAN      NOT NULL DEFAULT FALSE,
    contact_email           VARCHAR(255),
    contact_phone           VARCHAR(50),
    status                  VARCHAR(40)  NOT NULL,
    analysis_classification VARCHAR(40),
    analysis_confidence     DOUBLE PRECISION,
    analysis_detail         TEXT,
    deterministic_fast_track BOOLEAN,
    risk_score              DOUBLE PRECISION,
    risk_band               VARCHAR(20),
    risk_breakdown          TEXT,
    manual_adjustment_note  TEXT,
    classification_attempts INTEGER      NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_cases_risk_band ON cases (risk_band);

-- ─── case_documents (cases-service) ──────────────────────────────────────────
-- Adjuntos del expediente: un registro por tipo de documento por caso (upsert por tipo).
CREATE TABLE case_documents (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id         BIGINT       NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
    type            VARCHAR(80)  NOT NULL,
    filename        VARCHAR(255) NOT NULL,
    content_type    VARCHAR(255) NOT NULL,
    content         BYTEA        NOT NULL,
    uploaded_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT case_documents_case_type_unique UNIQUE (case_id, type)
);

-- ─── case_status_history (cases-service) ─────────────────────────────────────
-- Registro append-only de cada transición de estado del expediente (trazabilidad).
CREATE TABLE case_status_history (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id     BIGINT       NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
    from_status VARCHAR(40),
    to_status   VARCHAR(40)  NOT NULL,
    actor       VARCHAR(20)  NOT NULL,
    reason      VARCHAR(255) NOT NULL,
    changed_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ─── classification_log (classification-service) ─────────────────────────────
CREATE TABLE classification_log (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id             BIGINT,
    model               VARCHAR(80),
    prompt_version      VARCHAR(80),
    source              VARCHAR(40)  NOT NULL,
    classification      VARCHAR(40)  NOT NULL,
    confidence          NUMERIC(4,3),
    factors             TEXT         NOT NULL,
    latency_ms          BIGINT,
    risk_score          NUMERIC(4,3),
    risk_band           VARCHAR(20),
    risk_breakdown      TEXT,
    insured_name        VARCHAR(255),
    analyst_id          VARCHAR(80),
    decision            VARCHAR(20),
    decision_timestamp  TIMESTAMPTZ,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT classification_log_classification_check CHECK (
        classification IN (
            'FAST_TRACK',
            'FALTA_DOCUMENTACION',
            'LLM_RECOMIENDA_APROBAR',
            'LLM_NO_RECOMIENDA_APROBAR',
            'LLM_SOLICITA_REVISION_MANUAL'
        )
    )
);

-- ─── Datos de prueba: users ───────────────────────────────────────────────────
-- password_hash queda fijo/sin uso real: con AUTH_PROVIDER=auth0 el login valida contra Auth0,
-- no contra este hash (columna NOT NULL, se completa igual). Las contraseñas reales están
-- cargadas en el tenant de Auth0 con la convención '<rol>.arbiter123' (ej. analista.arbiter123).
-- Los emails usan un dominio real (gmail.com) porque el alta valida registros MX —
-- .test (RFC 2606) nunca resuelve, por eso no se usa más acá.
INSERT INTO users (id, email, password_hash, nombre, apellido, rol, sector, fecha_ingreso, insured_id)
VALUES
    -- El asegurado queda vinculado a su DNI: el portal lo saca del login, sin pedirlo.
    -- 42.987.654 matchea sus casos seedeados y sus pólizas mock (BBVA + Zurich).
    -- Mismo nombre que en la BD aseguradora (datos-aseguradoras.sql, documento 42.987.654)
    (1, 'asegurado.arbiter@gmail.com', '$2a$10$/hsOFJuuoiB23a3Gr.zgYO9UuOSopLRsiiu37CMAIIL1yMFr8EGlq',
     'Martina', 'Soteras', 'ASEGURADO', NULL, NULL, '42.987.654'),
    (2, 'analista.arbiter@gmail.com', '$2a$10$/hsOFJuuoiB23a3Gr.zgYO9UuOSopLRsiiu37CMAIIL1yMFr8EGlq',
     'Lucas', 'Gómez', 'ANALISTA_SINIESTROS', 'Siniestros Celulares', '2024-03-01', NULL),
    (3, 'referente.arbiter@gmail.com', '$2a$10$/hsOFJuuoiB23a3Gr.zgYO9UuOSopLRsiiu37CMAIIL1yMFr8EGlq',
     'Sofía', 'Martínez', 'REFERENTE_ASEGURADORA', 'Administración', '2022-06-15', NULL);

SELECT setval('users_id_seq', (SELECT MAX(id) FROM users));

-- ─── Datos de prueba: cases ──────────────────────────────────────────────────
INSERT INTO cases (id, branch, product, claim_cause, insured_item, insured_id, insured_name, policy_number,
                   description, event_date, event_location, claimed_amount,
                   pep, contact_email, contact_phone,
                   status, analysis_classification, analysis_confidence, analysis_detail,
                   deterministic_fast_track, risk_score, risk_band, risk_breakdown,
                   manual_adjustment_note, classification_attempts)
VALUES
    -- Case 1: Fast Track determinístico (rotura accidental, monto bajo, primer siniestro) → riesgo BAJO real (scoreado)
    (1, 'Celulares', 'Celular Protegido Premium', 'Rotura accidental',
     'Samsung Galaxy S25 Ultra', '42.987.654', 'Sofía Martínez', 'POL-CEL-2026-042',
     'Se me cayó el celular de las manos en mi casa. Se rompió la pantalla pero el equipo funciona normalmente',
     '2026-06-14 08:30:00', 'Casa', 285000.00,
     FALSE, 'martina.soteras@example.com', '11-5555-0001',
     'PENDING_ANALYST_REVIEW', 'FAST_TRACK', 1.0,
     'Monto reclamado (21.9% de la suma asegurada) dentro del límite de Fast Track (50.0%), Póliza al día con sus pagos',
     TRUE,
     0.099, 'LOW',
     '[{"factorId":"amount_ratio","rawScore":0.2192,"weight":0.45,"weightedContribution":0.0986,"rationale":"Monto reclamado es 22% de la suma asegurada"},{"factorId":"claim_frequency","rawScore":0.0,"weight":0.35,"weightedContribution":0.0,"rationale":"Siniestros previos del asegurado: 0"},{"factorId":"policy_standing","rawScore":0.0,"weight":0.2,"weightedContribution":0.0,"rationale":"Póliza al día con sus pagos"}]',
     NULL, 0),

    -- Case 2: LLM no recomienda aprobar (reincidente, monto alto) → riesgo ALTO + nota del analista (no sobrescribe el score)
    (2, 'Celulares', 'Celular Protegido Premium', 'Robo en vía pública',
     'iPhone 16 Pro Max', '30.555.777', 'Marcelo Gómez', 'POL-CEL-2025-099',
     'Me robaron el celular pero no me acuerdo bien dónde ni cuándo. Fue el martes o miércoles pasado, creo que cerca de Palermo',
     '2026-06-10 23:00:00', 'Palermo o Belgrano (no precisa)', 950000.00,
     FALSE, 'julian.perez@example.com', '11-5555-0002',
     'PENDING_ANALYST_REVIEW', 'LLM_NO_RECOMIENDA_APROBAR', 0.95,
     'Más de 2 claims en los últimos 12 meses: el asegurado tiene 3 claims previos (Nov 2025, Feb 2026 y Abr 2026). La descripción del incidente presenta inconsistencias con el reporte policial.',
     FALSE,
     0.706, 'HIGH',
     '[{"factorId":"amount_ratio","rawScore":0.7917,"weight":0.45,"weightedContribution":0.3563,"rationale":"Monto reclamado es 79% de la suma asegurada"},{"factorId":"claim_frequency","rawScore":1.0,"weight":0.35,"weightedContribution":0.35,"rationale":"Siniestros previos del asegurado: 3"},{"factorId":"policy_standing","rawScore":0.0,"weight":0.2,"weightedContribution":0.0,"rationale":"Póliza al día con sus pagos"}]',
     'Score elevado por reincidencia; verifiqué las 3 denuncias previas — dos con resolución legítima. Mantengo el caso en revisión estándar, sin sobrescribir el valor calculado.', 0),

    -- Case 3: Falta documentación, póliza fuera del catálogo mock → SIN SCOREAR (riesgo NULL, no LOW) → sin nombre resuelto tampoco
    (3, 'Celulares', 'Bolso – Compra Protegida', 'Robo en vía pública',
     'Samsung Galaxy A50', '44655366', NULL, '2030405',
     'Estaba saliendo de la facultad y me robaron desde una moto.',
     '2026-06-30 00:00:00', 'Medrano 951', 120000.00,
     FALSE, 'lucas.martinez@example.com', '11-5555-0003',
     'AWAITING_DOCUMENTATION', 'FALTA_DOCUMENTACION', 1.0,
     'Falta documento requerido: police_report, Falta documento requerido: item_photo',
     FALSE, NULL, NULL, NULL, NULL, 0),

    -- Case 4: Falta documentación (sin foto del bien), monto muy alto → riesgo MEDIO
    (4, 'Celulares', 'Celular Protegido Premium', 'Robo en vía pública',
     'iPhone 16 Pro', '42.987.654', 'Sofía Martínez', 'POL-CEL-2026-042',
     'El celular desapareció pero no sé si me lo robaron o lo perdí. No estoy seguro qué pasó exactamente',
     '2026-06-12 18:30:00', 'Colectivo línea 159', 1200000.00,
     FALSE, 'martina.soteras@example.com', '11-5555-0001',
     'AWAITING_DOCUMENTATION', 'FALTA_DOCUMENTACION', 1.0,
     'Falta documento requerido: item_photo',
     FALSE,
     0.415, 'MEDIUM',
     '[{"factorId":"amount_ratio","rawScore":0.9231,"weight":0.45,"weightedContribution":0.4154,"rationale":"Monto reclamado es 92% de la suma asegurada"},{"factorId":"claim_frequency","rawScore":0.0,"weight":0.35,"weightedContribution":0.0,"rationale":"Siniestros previos del asegurado: 0"},{"factorId":"policy_standing","rawScore":0.0,"weight":0.2,"weightedContribution":0.0,"rationale":"Póliza al día con sus pagos"}]',
     NULL, 0),

    -- Case 5: Pendiente de clasificación (recién ingresado) → aún sin scorear ni nombre resuelto (riesgo NULL)
    (5, 'Celulares', 'Celular Protegido Premium', 'Robo en vía pública',
     'iPhone 16 Pro', '42.987.654', NULL, 'POL-CEL-2026-042',
     'El celular desapareció pero no sé si me lo robaron o lo perdí. No estoy seguro qué pasó exactamente',
     '2026-06-12 18:30:00', 'Colectivo línea 159', 1200000.00,
     FALSE, 'martina.soteras@example.com', '11-5555-0001',
     'PENDING_CLASSIFICATION', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);

-- Resetear la secuencia para que el próximo INSERT use id=6
SELECT setval('cases_id_seq', (SELECT MAX(id) FROM cases));

-- ─── Datos de prueba: classification_log ─────────────────────────────────────
INSERT INTO classification_log (id, case_id, model, prompt_version, source, classification,
                                confidence, factors, latency_ms, risk_score, risk_band, risk_breakdown,
                                insured_name, created_at)
VALUES
    -- Log 1: Fast Track por reglas (case 1) → riesgo BAJO
    (1, 1, NULL, NULL, 'RULES_FAST_TRACK', 'FAST_TRACK',
     1.000,
     '["Monto reclamado (21.9% de la suma asegurada) dentro del límite de Fast Track (50.0%)", "Póliza al día con sus pagos"]',
     5, 0.099, 'LOW',
     '[{"factorId":"amount_ratio","rawScore":0.2192,"weight":0.45,"weightedContribution":0.0986,"rationale":"Monto reclamado es 22% de la suma asegurada"},{"factorId":"claim_frequency","rawScore":0.0,"weight":0.35,"weightedContribution":0.0,"rationale":"Siniestros previos del asegurado: 0"},{"factorId":"policy_standing","rawScore":0.0,"weight":0.2,"weightedContribution":0.0,"rationale":"Póliza al día con sus pagos"}]',
     'Sofía Martínez', '2026-06-29 00:27:15.751928+00'),

    -- Log 2: LLM no recomienda (case 2, reincidente) → riesgo ALTO
    (2, 2, 'qwen3-vl', 'classification-v1', 'LLM', 'LLM_NO_RECOMIENDA_APROBAR',
     0.950,
     '["Más de 2 claims en los últimos 12 meses: el asegurado tiene 3 claims previos (Nov 2025, Feb 2026 y Abr 2026). Esto activa la regla ''derivad a investigación'' según las cláusulas de la póliza.", "La descripción del incidente presenta inconsistencias con el reporte policial."]',
     3079602, 0.706, 'HIGH',
     '[{"factorId":"amount_ratio","rawScore":0.7917,"weight":0.45,"weightedContribution":0.3563,"rationale":"Monto reclamado es 79% de la suma asegurada"},{"factorId":"claim_frequency","rawScore":1.0,"weight":0.35,"weightedContribution":0.35,"rationale":"Siniestros previos del asegurado: 3"},{"factorId":"policy_standing","rawScore":0.0,"weight":0.2,"weightedContribution":0.0,"rationale":"Póliza al día con sus pagos"}]',
     'Marcelo Gómez', '2026-06-29 01:21:21.157741+00'),

    -- Log 3: Falta documentación (case 3) → sin scorear ni nombre resuelto (póliza fuera del catálogo mock)
    (3, 3, 'qwen3-vl', 'classification-v1', 'LLM', 'FALTA_DOCUMENTACION',
     1.000,
     '["Falta documento requerido: police_report", "Falta documento requerido: item_photo"]',
     7, NULL, NULL, NULL, NULL, '2026-07-01 22:57:48.286276+00'),

    -- Log 4: Clasificación aislada (sin case, test endpoint) → sin scorear ni nombre
    (4, NULL, 'qwen3-vl', 'classification-v1', 'LLM', 'FALTA_DOCUMENTACION',
     1.000,
     '["Falta documento requerido: police_report", "Falta documento requerido: item_photo"]',
     1, NULL, NULL, NULL, NULL, '2026-07-01 23:13:37.365684+00'),

    -- Log 5: Falta documentación (case 4) → riesgo MEDIO
    (5, 4, 'qwen3-vl', 'classification-v1', 'LLM', 'FALTA_DOCUMENTACION',
     1.000,
     '["Falta documento requerido: item_photo"]',
     0, 0.415, 'MEDIUM',
     '[{"factorId":"amount_ratio","rawScore":0.9231,"weight":0.45,"weightedContribution":0.4154,"rationale":"Monto reclamado es 92% de la suma asegurada"},{"factorId":"claim_frequency","rawScore":0.0,"weight":0.35,"weightedContribution":0.0,"rationale":"Siniestros previos del asegurado: 0"},{"factorId":"policy_standing","rawScore":0.0,"weight":0.2,"weightedContribution":0.0,"rationale":"Póliza al día con sus pagos"}]',
     'Sofía Martínez', '2026-07-01 23:24:15.188195+00');

-- Resetear la secuencia
SELECT setval('classification_log_id_seq', (SELECT MAX(id) FROM classification_log));

-- ─── Datos de prueba: case_status_history ────────────────────────────────────
-- Línea de tiempo de estados por caso (alta + resultado de la clasificación).
INSERT INTO case_status_history (id, case_id, from_status, to_status, actor, reason, changed_at)
VALUES
    -- Case 1: alta → Fast Track a bandeja del analista
    (1, 1, NULL, 'PENDING_CLASSIFICATION', 'INSURED', 'denuncia registrada', '2026-06-29 00:27:10+00'),
    (2, 1, 'PENDING_CLASSIFICATION', 'PENDING_ANALYST_REVIEW', 'SYSTEM', 'clasificación: FAST_TRACK', '2026-06-29 00:27:16+00'),

    -- Case 2: alta → LLM no recomienda a bandeja del analista
    (3, 2, NULL, 'PENDING_CLASSIFICATION', 'INSURED', 'denuncia registrada', '2026-06-29 01:20:00+00'),
    (4, 2, 'PENDING_CLASSIFICATION', 'PENDING_ANALYST_REVIEW', 'SYSTEM', 'clasificación: LLM_NO_RECOMIENDA_APROBAR', '2026-06-29 01:21:21+00'),

    -- Case 3: alta → falta documentación (espera al asegurado)
    (5, 3, NULL, 'PENDING_CLASSIFICATION', 'INSURED', 'denuncia registrada', '2026-07-01 22:57:40+00'),
    (6, 3, 'PENDING_CLASSIFICATION', 'AWAITING_DOCUMENTATION', 'SYSTEM', 'clasificación: FALTA_DOCUMENTACION', '2026-07-01 22:57:48+00'),

    -- Case 4: alta → falta documentación (espera al asegurado)
    (7, 4, NULL, 'PENDING_CLASSIFICATION', 'INSURED', 'denuncia registrada', '2026-07-01 23:24:00+00'),
    (8, 4, 'PENDING_CLASSIFICATION', 'AWAITING_DOCUMENTATION', 'SYSTEM', 'clasificación: FALTA_DOCUMENTACION', '2026-07-01 23:24:15+00'),

    -- Case 5: recién ingresado, sin clasificar todavía
    (9, 5, NULL, 'PENDING_CLASSIFICATION', 'INSURED', 'denuncia registrada', '2026-07-02 10:00:00+00');

-- Resetear la secuencia
SELECT setval('case_status_history_id_seq', (SELECT MAX(id) FROM case_status_history));

-- ─── Datos de prueba: case_documents ─────────────────────────────────────────
-- Adjuntos de ejemplo por expediente. Se usa el PDF de test (docs/postman/test-docs/denuncia_policial_ambigua.pdf)
-- como contenido base64 para todos — en dev importa tener filas, no el contenido real.
-- El PDF pesa ~5.6 KB; se reutiliza el mismo blob para no inflar el script.

-- Variable con el contenido del PDF para no repetir el literal en cada INSERT.
DO $$
DECLARE
    pdf_content BYTEA := decode('JVBERi0xLjQNCiWTjIueIFJlcG9ydExhYiBHZW5lcmF0ZWQgUERGIGRvY3VtZW50IChvcGVuc291cmNlKQ0KMSAwIG9iag0KPDwNCi9GMSAyIDAgUiAvRjIgMyAwIFINCj4+DQplbmRvYmoNCjIgMCBvYmoNCjw8DQovQmFzZUZvbnQgL0hlbHZldGljYSAvRW5jb2RpbmcgL1dpbkFuc2lFbmNvZGluZyAvTmFtZSAvRjEgL1N1YnR5cGUgL1R5cGUxIC9UeXBlIC9Gb250DQo+Pg0KZW5kb2JqDQozIDAgb2JqDQo8PA0KL0Jhc2VGb250IC9IZWx2ZXRpY2EtQm9sZCAvRW5jb2RpbmcgL1dpbkFuc2lFbmNvZGluZyAvTmFtZSAvRjIgL1N1YnR5cGUgL1R5cGUxIC9UeXBlIC9Gb250DQo+Pg0KZW5kb2JqDQo0IDAgb2JqDQo8PA0KL0NvbnRlbnRzIDkgMCBSIC9NZWRpYUJveCBbIDAgMCA1OTUuMjc1NiA4NDEuODg5OCBdIC9QYXJlbnQgOCAwIFIgL1Jlc291cmNlcyA8PA0KL0ZvbnQgMSAwIFIgL1Byb2NTZXQgWyAvUERGIC9UZXh0IC9JbWFnZUIgL0ltYWdlQyAvSW1hZ2VJIF0NCj4+IC9Sb3RhdGUgMCAvVHJhbnMgPDwNCg0KPj4gDQogIC9UeXBlIC9QYWdlDQo+Pg0KZW5kb2JqDQo1IDAgb2JqDQo8PA0KL0NvbnRlbnRzIDEwIDAgUiAvTWVkaWFCb3ggWyAwIDAgNTk1LjI3NTYgODQxLjg4OTggXSAvUGFyZW50IDggMCBSIC9SZXNvdXJjZXMgPDwNCi9Gb250IDEgMCBSIC9Qcm9jU2V0IFsgL1BERiAvVGV4dCAvSW1hZ2VCIC9JbWFnZUMgL0ltYWdlSSBdDQo+PiAvUm90YXRlIDAgL1RyYW5zIDw8DQoNCj4+IA0KICAvVHlwZSAvUGFnZQ0KPj4NCmVuZG9iag0KNiAwIG9iag0KPDwNCi9QYWdlTW9kZSAvVXNlTm9uZSAvUGFnZXMgOCAwIFIgL1R5cGUgL0NhdGFsb2cNCj4+DQplbmRvYmoNCjcgMCBvYmoNCjw8DQovQXV0aG9yIChcKGFub255bW91c1wpKSAvQ3JlYXRpb25EYXRlIChEOjIwMjYwNzAxMjAyMjM5LTAzJzAwJykgL0NyZWF0b3IgKFwodW5zcGVjaWZpZWRcKSkgL0tleXdvcmRzICgpIC9Nb2REYXRlIChEOjIwMjYwNzAxMjAyMjM5LTAzJzAwJykgL1Byb2R1Y2VyIChSZXBvcnRMYWIgUERGIExpYnJhcnkgLSBcKG9wZW5zb3VyY2VcKSkgDQogIC9TdWJqZWN0IChcKHVuc3BlY2lmaWVkXCkpIC9UaXRsZSAoXChhbm9ueW1vdXNcKSkgL1RyYXBwZWQgL0ZhbHNlDQo+Pg0KZW5kb2JqDQo4IDAgb2JqDQo8PA0KL0NvdW50IDIgL0tpZHMgWyA0IDAgUiA1IDAgUiBdIC9UeXBlIC9QYWdlcw0KPj4NCmVuZG9iag0KOSAwIG9iag0KPDwNCi9GaWx0ZXIgWyAvQVNDSUk4NURlY29kZSAvRmxhdGVEZWNvZGUgXSAvTGVuZ3RoIDE5NDUNCj4+DQpzdHJlYW0NCkdhdTBEPnVUYFInUmZeV2d0TEhlQWRedE1ePm1aSExiaF5KQDNBWlY+UCQ4aVhpOl1eLU5SbDg/YmEnMyE8R0ozbVJqSitGRGRgSkZqQkFOK1NfWXFCMDZGXzdhU11BNV1xbSNKWFcjNmQxQ29ubSlMIUc9JCFlUGcsOmhZX1U1O3BIaFxUO2VndUUmOnRZX1BnbXQtNV0mIVcjY0lFXTVnLU0pIVdHLStjWlEtVXUtLihxNF4iSEM+TUYtTTMwVjZMP1hxMFxMJDZkJiVvRVA8YScxPD9CcjtsKjljUVVHTHB0OlJpWSomLVpAIUVXbiY5Vz05XDZCIWMmWm5JKC8qJG9eRkBwQU03UXE8OyZ1ITYsb1YiNDJwJi4pTFpSP2ZJPTZkUVY9WUwyXGkiJTBORlJAKVZPWjIoQmt1IVtlJ2phS2tpYlEmbURML0FZcDtCJ0Y9Y2tKTGsmSGlyOVkpSzo0RCNIYWsySV0kPkwwdGBONDloQi4vXyRQWTtPLDtrSGVFIWJlWi04QXNuQylJcTE1ckFCYWJLXCEoQzhScGdQST5aQjdUYXFUc209OVQkPi5pP04jMS1bI042OTIiSFYmJEozRzxOcnRvJDtIUWdaTzUsWTNFImhFUyw+WldzO0Q5MTdfX0hQPG5zXmEnXyMhSG0jK1YsREUjZEREW1ssJjVDS0Nwc0VwO15QNFBhOHRGKDFTOm9dMDNZOzMoOiZPPEMjaUFocCcjKS81XyVKNjNJc01ANFhZKVs9aElZKDJaM009KyYtNG1FbzJOZD0pNjVbUF1bLXU/UWdfX2I0KVwyaGpaLGdNYzw4VV9lU3FcYFUiL2xeRCJFKjBsalJJXz0oTz1KSyZgTFRPKGU0a1g0R087TGdFa3AwP1o2KHA5dGVzUlYxbEYlNDhCPl4iO004YloocyQ6MkdVIyMmNF9mTjBhTGJaUmVmUjRNc182RFtMcnVpViNsTyViZFVJZWZNKXRbNW1UO0JKOWVtRFNvSC8sJi1paklwZFAiWVsrOyJjbCdETShUITAiUjNrUygwQjIpYGs2b1pLQFZyRzkpSVY+V2NaTSkhMS9HaFc8VW1PTkgkaDgsJDpaUkFrTk40OmVIVyMnK1wlNjVTcCkocWNXNioiKF1xWiI5aiNnUDg4WkYkbWEpZ3NNOjVpbDhvUyEjXFI4TjNeJTxidVJfYnAzOWdzZUlGV3ErJy5gIjp1QXQzSSgxREElUF9QZzMpOkR1bzBeMGtwJV85YEwmX2AwNE9RbDopJGQuPW1LQmFEdHBXZDJVJjdCVWtoKDIsbUw+IUI+WzkkXSplM2QyVEM1N05gXVEhWzwkIlcpXiFpXkckXTFpQSxJMkhTMSxKT1JOV25bcSpUanQrY2E9TmpRN1ZEOGsqYj0+UmQlRlxEbzZzQi4kbGBzbzs9MFVGOWhRM2IiTUw1KidZPVpEKm0oNkcvMzhPXTBJQ0o6UShLQVJzWFpIRk1cRUZjaVlyMF0oZjpsZC1wM3JpRE0lOTQ2IiVtb0ZGUjFVVWJoc1BHUlNtZDhOOVZFbUdOOmswYS4xMTpyKD8tJ0A4XFFMZXRobWloNVUyNE1fKC8xPj41OiFCI1QtcEU2KS48ZnRTWDRvaDhZPG8ocCdnZClaP04iXSJlPDN1UDUuJl8xaUdhLDVVIkNELWRZPS04QSxQMHUqVT9CU1FUNHQyWjsoaEQ6RSR0RmFcNSNHM1Y/R1lkYC0pKys0PzxcP1ReaiVHVk9ZQkEiXmpkTV1WTWYjW18sdXJkOXVeMyxKXWwsUW4rOWZZLmVpOGgnSUthJDFTZms0Uz5eclFaN2FFKDpiS3BbXy9RQDxuNl5HMVBXIV47ZmInMTFCP1E1S09IL2N1Yz5ha2AkZGs5Xl9TZmpjKGYmW1FyMmxlSUI4Xj87WjhVcSE3XEA7UEZEUG4yJHBMSWtSKV9db0VfS0Y6JCFVZWdBMiJnN2BpSTk4aVY+NmlkaD0qWz4pJzJKJGsiXikrIjRcUmVGLFhbZTozR2hkUjssIiQwIl5FKy1BOGRlaWVBL1Q2KnMpIS9JYG89RV9VMmROZlwrZV8/Wj04c2tkRmwjRytGVllAaXNQVUs8IURlXy1VakpaKlwjREEpNFcmJCdWPmElLk0hUlhbXzlYMj9QX0dwX0ZTUiMpQThnUyRUKmRAPCFFX0ElTCpHNXFSLEVYIk4nUChLNlUqMi1ePkYsKWxAK20pZDZ1SSssVjVFOURrR2hmaFZsSlE/PD8kQjwtL2tObS1mIjRtNDhQZSFwYlMoOV9KZGsrJFImNypCSjhQQCJKOzIvPTU5WVs5SUA0QURPJ0lXMXFWQyQkUV1TZFZySSxKTFlpKiIwKzJyMCxaKD11UmQza3RvJlMpc1FPOWJyXVklNT1tRyJwVU0sWU0tZko+MjdaPiFAZURGPUI+QEZeQExQPGJySlswailgXDRZWkhdKmFmWWJSS1RwImhTMklfOWtyb0VAJCRBUzwyQjcqZV9jJj5FWXNCLlprRXEnW0JNcitCYjc0MW0hX0BtR1tHNzxeYFdyQmwuVSNtbENocXArSENdMEFIfj5lbmRzdHJlYW0NCmVuZG9iag0KMTAgMCBvYmoNCjw8DQovRmlsdGVyIFsgL0FTQ0lJODVEZWNvZGUgL0ZsYXRlRGVjb2RlIF0gL0xlbmd0aCAxODU2DQo+Pg0Kc3RyZWFtDQpHYXRtO0QvXERuJkg6Tm4xJFUuW2U5LGNmbzkkS0dNR2pvPU9LTT9WUHRpWVxlPmpqbEcvQS5rZkFHM104bmBPTzN1cGo7T1JgKzZSSEt0bSdaVHBGcCtybFBYdG1OIlYqSCdCPF44aC02JDxLKUc0cDtRR0V1WiZVKi0qTSJFJG5IKjVvPnMrNixcNm4zdS5mQS8uciNHYkgock9GOVcrYG1hJU8iKkFALE82cC9SQDhvbHI0RSViWykiOEg4PjdNVUxSLy1ILmpVSjg4aD0ocjpJSSEhSmVZPExbYEUmcCw4QSFmNiFQMnVpL0shW2VEYkBhLHBlL29VW1VdX2M9X2s6LmA0Ric+X2pxQVApOTNkLUh1aENHTiklYEtlKypSTDdtJyx1MStlJENZTU1rXS8lIWQtREEzYjxLRUBidUFaNnRIQSNtLXBhaztTdDtFKFUzYUNXS2I3VmpCVFpGQFM5cixEIlVKSFxtQC9aVGhmZCJiY0JacDUuYkotIShkSVwvWmJZcTYwPzBvTEE2ZWRPSEFCbyxuQ29uTVgqO1I9aSJVJDZANC5fLTpab3JuNiFNLj1qSUNXKF4xS1hLPCtbITZHdDhdK1Q1RG5IME8pUk4vZzkrSTgqUU9RZlhxIjcucFEmbD9KMGJwWnVyWmsqWkA7UE0jUGxpYjM1XUw4akVAZEtbWExbN11eIzs4NDdqKDNZIyNlZzhbRSoyI1ovZk5XXHVkcS1AVWhUXmlMXUpgRl5sVikpbidANCo4XWZvUWxSR08nYDRSLUlBJDM9TE5gUTYkWjcwc1kpakVEXkQtRCg1YUY+NFpqYl1yYUxXYi1qSmsmdHFSMjAqNnRtUV5OMGBSKydfcEkiYENjcDQ4QWlOUz5wSFY6aUtjZEFXYTsoOmcmKkRrQDNLRDspP09hYkIvLWU0ZV5pO0BCQlFoYmdhV2ZNUFVDZ2lJX1RGVj8uT3UuZzlOR2Jlb0liVjtSOExuJHFqUFROSmFdM25AR2ZoJGBJL1o8bC0tK21QcGpAYEU9WD1SXFs1MSdNQEFpbiRucG9mJyNFQEhGVGFVYypOQy8tcEs2cz4tREtCay9pRlkxTCpMT0A0T1hWLUArPjssVTtsZ2NCNFVaXENhM3QiIzI6WkptbXM2ZmxPV2RrLkMmWTQ2WCxaPWVacmxqSURiL2gtZi49TjozSXNsXCgmTTQpIVFtaURGW1EycXJlSiVTYCJtJClQKWI4I0FZN2sjW0hkckEocFRjPWI2I0ROWylLYzUnUlpHYiorLj9OXW9bMGFTP2UmZytpX2Mwb201N1BrZlNZTl9za2c6RjV1by1qLGxmPlRCaC9EZyVBXEhpL1AjMVBkO2QjMGllNmNnS0hHV00pUVMiWzRJPGFNKiklQzhKVV0nPlJJOmo1aSQ5LUAzZUA6aVYuJF5KM3VLaCMpdG1TNnFUJjROYlZNJ2hEY2lCSjMyUkFHZi4nSVgxIilfS14pKWlGY29naik5JVU3M11AN25QRHFqXHIydXE9T2oyU1hGP1QuISxON0k9WlhdJUlpSiU0UklwUS4wNj0/YWpfTGZLXGY2T2xvbUJ0cCZaREEwWEQ2VFs4bXIjO21dTVVtN0NVKicxb2NGZjYrKCc1OCpLUlJPZkxtZmM4SDllSnAxYnEnL05bP2AqRVJtRVs4Q2oqNEtcIzhJX09QVF5CaD0qQltWU19HYCcxKCtNaytqR2ZucUpoUydgMDpRUUZFVWhaJS50L2ZJcjw0cGcyZE85RUs3MEY6azwxLE9UPylYZyNSSS4la2lILVgmOGZmPVJqKlhdSTxibGhLaSVALGhXLSgzKnRlWkcpWEtpQGxKUXVuL1Y6ImEiVihcRDIzKFJWbmpUXEdxS0U6ZllKTklXLCklV0hgczFhKkEuIlExM1RDUjY/Y2xZaCRSL01aQlVeU2wzc2orJSFdLDRvSWFCczU9cjNHL0dcbD0oMzUrbFNXTWZRVGd1dFUsM1pmcF05dUEqNSlIJXIiTVFoLWA6M3JoSD9gUWhEZklnODVRWCZibWMwZl5VQkhUYUpSKFVNR3BDamRnSCgjIW9GVHNfJWdvYCQmQ2VsdDNyU1xhQF9IQXUpVVJwV2xiakJUVUkyODAldEpZR1kmZS5QQ2ZyUjgpYFJjOFVpQm1vWWlBNUtra1JkJVBPI3QxWSdXISZMKC9hLSNATFhmVm8rUSJoPU8mPF1NXVxdN3RgYm45c1o3MChcP3Q1cW8hVFNnWmBpPWBLOkZ1UCQqckNEV15GQjhMTyJoNHNqP3BERnVPWU1fKUUyXmEtVV5Ba0BrM3EoXEFURDBlJ2pPNzhoJyRRYSgvZ2txUGM/VSdvIV5YIytiSFVzLTBcIzE2K1UxbXQuIitRU2Q0WVBJXU1iVDJLKD0sLElzK3U0YWYoY1I3aFFdSEQ1PmlDM2NRIz9UYj9cJXVaYkhOaGFPdUZ+PmVuZHN0cmVhbQ0KZW5kb2JqDQp4cmVmDQowIDExDQowMDAwMDAwMDAwIDY1NTM1IGYgDQowMDAwMDAwMDYxIDAwMDAwIG4gDQowMDAwMDAwMTAyIDAwMDAwIG4gDQowMDAwMDAwMjA5IDAwMDAwIG4gDQowMDAwMDAwMzIxIDAwMDAwIG4gDQowMDAwMDAwNTI0IDAwMDAwIG4gDQowMDAwMDAwNzI4IDAwMDAwIG4gDQowMDAwMDAwNzk2IDAwMDAwIG4gDQowMDAwMDAxMDc2IDAwMDAwIG4gDQowMDAwMDAxMTQxIDAwMDAwIG4gDQowMDAwMDAzMTc3IDAwMDAwIG4gDQp0cmFpbGVyDQo8PA0KL0lEIA0KWzw5OTc2OWZlMDkyNDdjMGY4YzAzZDJhZWJhZjIzNzQ0Nj48OTk3NjlmZTA5MjQ3YzBmOGMwM2QyYWViYWYyMzc0NDY+XQ0KJSBSZXBvcnRMYWIgZ2VuZXJhdGVkIFBERiBkb2N1bWVudCAtLSBkaWdlc3QgKG9wZW5zb3VyY2UpDQoNCi9JbmZvIDcgMCBSDQovUm9vdCA2IDAgUg0KL1NpemUgMTENCj4+DQpzdGFydHhyZWYNCjUxMjUNCiUlRU9GDQo=', 'base64');
    -- JPEG mínimo válido (1x1 pixel rojo) para simular fotos.
    jpg_content BYTEA := decode('/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAP//////////////////////////////////////////////////////////////////////////////////////2wBDAf//////////////////////////////////////////////////////////////////////////////////////wAARCAABAAEDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYI4Q/RFhHRUYnJCk6NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/aAAwDAQACEQMRAD8APQD/2Q==', 'base64');
BEGIN
    INSERT INTO case_documents (case_id, type, filename, content_type, content, uploaded_at)
    VALUES
        -- Case 1 (Fast Track, robo celular): documentación completa
        (1, 'police_report', 'denuncia-policial-martinez.pdf', 'application/pdf', pdf_content, '2026-06-29 00:27:10+00'),
        (1, 'item_photo',    'foto-celular-roto.jpg',          'image/jpeg',      jpg_content, '2026-06-29 00:27:10+00'),

        -- Case 2 (LLM no recomienda, robo sospechoso): documentación completa
        (2, 'police_report', 'denuncia-policial-gomez.pdf',    'application/pdf', pdf_content, '2026-06-29 01:20:00+00'),
        (2, 'item_photo',    'foto-notebook-danada.jpg',       'image/jpeg',      jpg_content, '2026-06-29 01:20:00+00'),
        (2, 'invoice',       'factura-compra-notebook.pdf',    'application/pdf', pdf_content, '2026-06-29 01:20:00+00'),

        -- Case 3 (Falta documentación): solo tiene denuncia policial, falta item_photo
        (3, 'police_report', 'denuncia-policial-lopez.pdf',    'application/pdf', pdf_content, '2026-07-01 22:57:40+00'),

        -- Case 4 (Falta documentación, monto alto): solo tiene denuncia policial, falta item_photo
        (4, 'police_report', 'denuncia-policial-fernandez.pdf','application/pdf', pdf_content, '2026-07-01 23:24:00+00'),

        -- Case 5 (recién ingresado): subió la foto del bien, falta denuncia policial
        (5, 'item_photo',    'foto-iphone-roto.jpg',           'image/jpeg',      jpg_content, '2026-07-02 10:00:00+00');
END $$;

-- Resetear la secuencia
SELECT setval('case_documents_id_seq', (SELECT MAX(id) FROM case_documents));

COMMIT;
