-- =============================================================================
-- Arbiter — script de inicialización de BD
-- Dropea tablas legacy + actuales, recrea el schema limpio y seedea datos de prueba.
--
-- Uso:
--   docker exec -i arbiter-postgres-1 psql -U arbiter -d arbiter < db/init.sql
-- =============================================================================

BEGIN;

-- ─── Limpiar tablas legacy y actuales ────────────────────────────────────────
DROP TABLE IF EXISTS adjunto CASCADE;
DROP TABLE IF EXISTS claim CASCADE;
DROP TABLE IF EXISTS clasificacion_log CASCADE;
DROP TABLE IF EXISTS siniestro CASCADE;
DROP TABLE IF EXISTS classification_log CASCADE;
DROP TABLE IF EXISTS case_documents CASCADE;
DROP TABLE IF EXISTS cases CASCADE;

-- ─── cases (cases-service) ───────────────────────────────────────────────────
CREATE TABLE cases (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch                  VARCHAR(255) NOT NULL,
    product                 VARCHAR(255) NOT NULL,
    claim_cause             VARCHAR(255) NOT NULL,
    insured_item            VARCHAR(255) NOT NULL,
    insured_id              VARCHAR(255) NOT NULL,
    policy_number           VARCHAR(255) NOT NULL,
    description             TEXT         NOT NULL,
    event_date              TIMESTAMP(6) NOT NULL,
    event_location          VARCHAR(255) NOT NULL,
    claimed_amount          NUMERIC(38,2),
    status                  VARCHAR(40)  NOT NULL,
    analysis_classification VARCHAR(40),
    analysis_confidence     DOUBLE PRECISION,
    analysis_detail         TEXT,
    deterministic_fast_track BOOLEAN,
    classification_attempts INTEGER      NOT NULL DEFAULT 0
);

-- ─── case_documents (cases-service) ──────────────────────────────────────────
-- Adjuntos del expediente: un registro por tipo de documento por caso (upsert por tipo).
CREATE TABLE case_documents (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id         BIGINT       NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
    type            VARCHAR(80)  NOT NULL,
    filename        VARCHAR(255) NOT NULL,
    content_type    VARCHAR(255) NOT NULL,
    content         BYTEA        NOT NULL,
    uploaded_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT case_documents_case_type_unique UNIQUE (case_id, type)
);

-- ─── classification_log (classification-service) ─────────────────────────────
CREATE TABLE classification_log (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id             BIGINT,
    model               VARCHAR(80),
    prompt_version      VARCHAR(80),
    source              VARCHAR(40)  NOT NULL,
    classification      VARCHAR(40)  NOT NULL,
    confidence          NUMERIC(4,3),
    factors             TEXT         NOT NULL,
    latency_ms          BIGINT,
    analyst_id          VARCHAR(80),
    decision            VARCHAR(20),
    decision_timestamp  TIMESTAMPTZ,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT classification_log_classification_check CHECK (
        classification IN (
            'FAST_TRACK',
            'FALTA_DOCUMENTACION',
            'LLM_RECOMIENDA_APROBAR',
            'LLM_NO_RECOMIENDA_APROBAR',
            'LLM_SOLICITA_REVISION_MANUAL'
        )
    )
);

-- ─── Datos de prueba: cases ──────────────────────────────────────────────────
INSERT INTO cases (id, branch, product, claim_cause, insured_item, insured_id, policy_number,
                   description, event_date, event_location, claimed_amount,
                   status, analysis_classification, analysis_confidence, analysis_detail,
                   deterministic_fast_track, classification_attempts)
VALUES
    -- Case 1: Fast Track determinístico (rotura accidental, monto bajo, primer siniestro)
    (1, 'Celulares', 'Celular Protegido Premium', 'Rotura accidental',
     'Samsung Galaxy S25 Ultra', '42.987.654', 'POL-CEL-2026-042',
     'Se me cayó el celular de las manos en mi casa. Se rompió la pantalla pero el equipo funciona normalmente',
     '2026-06-14 08:30:00', 'Casa', 285000.00,
     'PENDING_ANALYST_REVIEW', 'FAST_TRACK', 1.0,
     'Monto reclamado (21.9% de la suma asegurada) dentro del límite de Fast Track (50.0%), Póliza al día con sus pagos',
     TRUE, 0),

    -- Case 2: LLM no recomienda aprobar (reincidente, descripción vaga)
    (2, 'Celulares', 'Celular Protegido Premium', 'Robo en vía pública',
     'iPhone 16 Pro Max', '30.555.777', 'POL-CEL-2025-099',
     'Me robaron el celular pero no me acuerdo bien dónde ni cuándo. Fue el martes o miércoles pasado, creo que cerca de Palermo',
     '2026-06-10 23:00:00', 'Palermo o Belgrano (no precisa)', 950000.00,
     'PENDING_ANALYST_REVIEW', 'LLM_NO_RECOMIENDA_APROBAR', 0.95,
     'Más de 2 claims en los últimos 12 meses: el asegurado tiene 3 claims previos (Nov 2025, Feb 2026 y Abr 2026). La descripción del incidente presenta inconsistencias con el reporte policial.',
     FALSE, 0),

    -- Case 3: Falta documentación (sin denuncia policial ni foto)
    (3, 'Celulares', 'Bolso – Compra Protegida', 'Robo en vía pública',
     'Samsung Galaxy A50', '44655366', '2030405',
     'Estaba saliendo de la facultad y me robaron desde una moto.',
     '2026-06-30 00:00:00', 'Medrano 951', 120000.00,
     'PENDING_ANALYST_REVIEW', 'FALTA_DOCUMENTACION', 1.0,
     'Falta documento requerido: police_report, Falta documento requerido: item_photo',
     FALSE, 0),

    -- Case 4: Falta documentación (sin foto del bien)
    (4, 'Celulares', 'Celular Protegido Premium', 'Robo en vía pública',
     'iPhone 16 Pro', '42.987.654', 'POL-CEL-2026-042',
     'El celular desapareció pero no sé si me lo robaron o lo perdí. No estoy seguro qué pasó exactamente',
     '2026-06-12 18:30:00', 'Colectivo línea 159', 1200000.00,
     'PENDING_ANALYST_REVIEW', 'FALTA_DOCUMENTACION', 1.0,
     'Falta documento requerido: item_photo',
     FALSE, 0),

    -- Case 5: Pendiente de clasificación (recién ingresado)
    (5, 'Celulares', 'Celular Protegido Premium', 'Robo en vía pública',
     'iPhone 16 Pro', '42.987.654', 'POL-CEL-2026-042',
     'El celular desapareció pero no sé si me lo robaron o lo perdí. No estoy seguro qué pasó exactamente',
     '2026-06-12 18:30:00', 'Colectivo línea 159', 1200000.00,
     'PENDING_CLASSIFICATION', NULL, NULL, NULL, NULL, 0);

-- Resetear la secuencia para que el próximo INSERT use id=6
SELECT setval('cases_id_seq', (SELECT MAX(id) FROM cases));

-- ─── Datos de prueba: classification_log ─────────────────────────────────────
INSERT INTO classification_log (id, case_id, model, prompt_version, source, classification,
                                confidence, factors, latency_ms, created_at)
VALUES
    -- Log 1: Fast Track por reglas (case 1)
    (1, 1, NULL, NULL, 'RULES_FAST_TRACK', 'FAST_TRACK',
     1.000,
     '["Monto reclamado (21.9% de la suma asegurada) dentro del límite de Fast Track (50.0%)", "Póliza al día con sus pagos"]',
     5, '2026-06-29 00:27:15.751928+00'),

    -- Log 2: LLM no recomienda (case 2, reincidente)
    (2, 2, 'qwen3-vl', 'classification-v1', 'LLM', 'LLM_NO_RECOMIENDA_APROBAR',
     0.950,
     '["Más de 2 claims en los últimos 12 meses: el asegurado tiene 3 claims previos (Nov 2025, Feb 2026 y Abr 2026). Esto activa la regla ''derivad a investigación'' según las cláusulas de la póliza.", "La descripción del incidente presenta inconsistencias con el reporte policial."]',
     3079602, '2026-06-29 01:21:21.157741+00'),

    -- Log 3: Falta documentación (case 3)
    (3, 3, 'qwen3-vl', 'classification-v1', 'LLM', 'FALTA_DOCUMENTACION',
     1.000,
     '["Falta documento requerido: police_report", "Falta documento requerido: item_photo"]',
     7, '2026-07-01 22:57:48.286276+00'),

    -- Log 4: Clasificación aislada (sin case, test endpoint)
    (4, NULL, 'qwen3-vl', 'classification-v1', 'LLM', 'FALTA_DOCUMENTACION',
     1.000,
     '["Falta documento requerido: police_report", "Falta documento requerido: item_photo"]',
     1, '2026-07-01 23:13:37.365684+00'),

    -- Log 5: Falta documentación (case 4)
    (5, 4, 'qwen3-vl', 'classification-v1', 'LLM', 'FALTA_DOCUMENTACION',
     1.000,
     '["Falta documento requerido: item_photo"]',
     0, '2026-07-01 23:24:15.188195+00');

-- Resetear la secuencia
SELECT setval('classification_log_id_seq', (SELECT MAX(id) FROM classification_log));

COMMIT;
